---
title: "Mathematical Foundations"
abstract: |
  
date: 2025-08-10
categories: [Mathematics, Undergraduate-level]
keywords:
- MS01-001-G
---

## Informations sur le cours

- **Rattachement** : Opérations Management and Decision Science 
- **Semestre** : 01
- **Campus d’enseignement** : Aix-en-Provence, Angers, Bordeaux, Boulogne-Billancourt,
 Lyon, Strasbourg
- **Heures totales** : 30,00
- **Crédits ECTS** : 4,00
- **Langue d'enseignement** : Français et/ou Anglais
- **Ouvert aux Étudiants d’Échange** : Non

## Présentation Générale

Ce cours de « Fondamentaux mathématiques et Analyse des données » a pour objectif
de fournir aux étudiants les outils mathématiques nécessaires pour analyser et
résoudre des problèmes quantitatifs qu’ils soient financiers, économiques ou de
gestion:

- Manipulation des expressions algébriques ;
- Résolution d’équations des premier et second degrés et d’inéquations pour modéliser
  des questions économiques ;
- Visualisation graphique des fonctions économiques et interprétation ;
- Suites et fonctions usuelles ;
- Optimisation simple pour prendre des décisions stratégiques.

## Compétences Visées

**2 - Capacités intellectuelles**

  **2.3** :  Choisir les méthodes de calcul et les outils de résolution de
  problèmes pertinents

**5 - Compétences technologiques**

  **5.2** Utiliser les outils dédiés à la recherche et au traitement de l’information,
  ainsi qu’à la communication en entreprise (notamment : traitement de texte, 
  tableaux de bords, outils de gestion de projet, outils en ligne)

## Organisation & Planning

### Module 1 : [Calculs mathématiques essentiels pour l’économie et la gestion](module-1.qmd)

Maîtriser les opérations et propriétés fondamentales des nombres réels, dans une optique appliquée à l’économie et à la gestion.
date: 2025-09-17
Opérations et propriétés fondamentales des nombres réels (priorité des
opérations, valeur absolue, puissance, racine carrée, fractions, pourcentage,
règle de proportionnalité)

### Module 2 : [Maîtrise des équations pour une meilleure prise de décision](module-2.qmd)
Factorisation, développement, identités remarquables et résolution d’équation
du premier degré

### Module 3 : [Analyse de courbes en économie et en gestion](module-3.qmd)
Représentation graphique (lecture graphique, droite, signe, sens de variation,
parité), point d’intersection de deux droites, système d’équations et inéquations
du premier degré

### Module 4 : [Introduction aux outils de mathématiques financières](module-4.qmd)
Etude des suites numériques (définition générale, suite arithmétique, suite
géométrique).

### Module 5 : [Application des mathématiques financières](module-5.qmd)
Intérêts simples et composés.

### Module 6 : [Présentation des fonctions utiles en économie et en gestion](module-6.qmd)
Présentation de la fonction à 1 variable (exemple, signification, domaine de
définition, valeurs interdites) et fonctions usuelles (affine, polynomiale,
logarithme, exponentielle), équation du second degré simple ($x^2 = 2 par
exemple) et plus complexe.

### Module 7 : [Introduction à l’optimisation](module-7.qmd)
Taux de variation moyen et instantané, présentation « intuitive » de la notion
de dérivée, application sur la fonction affine et la fonction polynomiale

### Module 8 : Préparation à l’examen final
Révisions générales et consolidation des acquis

## Evaluation

|      Examens      | % évaluation globale | Mode d'évaluation | Durée (minutes) |
| ----------------- | -------------------- | ----------------- | --------------- |
| Contrôle Continu  |         50           |  écrit individuel |        45       |
| Examen final (EF) |         50           |  écrit individuel |        90       |

## Travail personnel attendu

- Réaliser le travail et les exercices associés avant chaque séance de cours.
- **Volume horaire** : 50 heures

## Lecture recomandé

- Ian Jacques, _Mathematics for Economics And Business_, Pearson Education Limited; 5e édition, 2006
- Jean-Luc Dorier, Marc Duc-Jacquet, _Mathématiques pour l'économie et la gestion_, Gualino Ed, 1996
- Stéphane Rossignol, _Mathématiques en économie-gestion_, 2ème ed, Dunod Éditons, 2022

