##----------------------------------------------------------------------------##
#                           Quarto Render Information                          #
##----------------------------------------------------------------------------##
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.md"
  post-render:
    - scripts/update-profile-readme.sh
  resources:
    - CNAME
    - assets/giscus-retro-blackboard.css

execute:
  freeze: auto

# ------------------------------------------------------------------- #
#                         Website Configuration                       #
# ------------------------------------------------------------------- #
website:
  title: "Guillaume Gilles"

  # -------------------------- NAVIGATION --------------------------- #
  # offer the user the ability to navigate to the next page (or
  # previous page) at the bottom of the page that they’ve just finished
  # reading
  page-navigation: true

  # Search is enabled by default for websites (you can disable it with
  # search: false).
  search: true

  # RSS feed
  site-url: https://ggilles.dev

  navbar:
    logo: assets/favicon.png
    title: "Guillaume Gilles"
    left:
      - href: about.qmd
      - href: index.qmd
      - href: teaching.qmd
    tools:
      - icon: translate
        text: "Langue / Language"
        menu:
          - text: "🇬🇧 English"
            href: /teaching.html
          - text: "🇫🇷 Français"
            href: /fr/teaching.html

  sidebar:
    #---------------------------- Graduate courses ---------------------------#
    #-------------------------------------------------------------------------#

    #--- Financial Analysis
    - id: inseec-finane
      contents:
        - teaching/inseec-finance/index.qmd

    #------------------------- Undergraduate courses -------------------------#
    #-------------------------------------------------------------------------#

    #--- EN --- Mathematical Fundamentals
    - id: mathematical-fundamentals
      title: "Mathematical Fundamentals"
      contents:
        - teaching/mathematical-fundamentals/index.qmd
        - teaching/mathematical-fundamentals/module-1.qmd
        - teaching/mathematical-fundamentals/module-2.qmd
        - teaching/mathematical-fundamentals/module-3.qmd
        - teaching/mathematical-fundamentals/module-4.qmd
        - teaching/mathematical-fundamentals/module-5.qmd
        - teaching/mathematical-fundamentals/module-6.qmd
        - teaching/mathematical-fundamentals/module-7.qmd
        - teaching/mathematical-fundamentals/module-8.qmd
        - section: "**Resources**"
          contents:
            - teaching/mathematical-fundamentals/glossary.qmd
            - teaching/mathematical-fundamentals/formula-sheet.qmd

    #--- FR --- Mathematical Fundamentals
    - id: fr-mathematical-fundamentals
      title: "Fondements Mathématiques"
      contents:
        - fr/teaching/mathematical-fundamentals/index.qmd
        - fr/teaching/mathematical-fundamentals/module-1.qmd
        - fr/teaching/mathematical-fundamentals/module-2.qmd
        - fr/teaching/mathematical-fundamentals/module-3.qmd
        - fr/teaching/mathematical-fundamentals/module-4.qmd
        - fr/teaching/mathematical-fundamentals/module-5.qmd
        - fr/teaching/mathematical-fundamentals/module-6.qmd
        - fr/teaching/mathematical-fundamentals/module-7.qmd
        - fr/teaching/mathematical-fundamentals/module-8.qmd
        - section: "**Ressources**"
          contents:
            - fr/teaching/mathematical-fundamentals/glossary.qmd
            - fr/teaching/mathematical-fundamentals/formula-sheet.qmd
            - fr/teaching/mathematical-fundamentals/learning-guide.qmd

    #--- EN --- Mathematics Finance
    - id: en-mathematics-finance
      title: "Financial Mathematics"
      contents:
        - teaching/mathematical-finance/index.qmd

    #--- FR --- Mathematics Finance
    - id: fr-mathematics-finance
      title: "Mathématiques financières"
      contents:
        - fr/teaching/mathematical-finance/index.qmd
        - fr/teaching/mathematical-finance/module-01.qmd
        - fr/teaching/mathematical-finance/module-02.qmd
        - fr/teaching/mathematical-finance/module-03.qmd
        - section: "**Ressources**"
          contents:
            - fr/teaching/mathematical-finance/glossaire.qmd
            - fr/teaching/mathematical-finance/formulaire.qmd

    #--- Data Description
    - id: data-description
      title: "Data Description"
      contents:
        - teaching/data-description/index.qmd
        - section: "**Part I — Excel Fundamentals**"
          contents:
            - teaching/data-description/session-01.qmd
            - teaching/data-description/session-02.qmd
        - section: "**Part II — Univariate Data Treatment**"
          contents:
            - teaching/data-description/session-03.qmd
            - teaching/data-description/session-04.qmd
            - teaching/data-description/session-05.qmd
            - teaching/data-description/session-06.qmd
            - teaching/data-description/session-07.qmd
            - teaching/data-description/session-08.qmd
            - teaching/data-description/session-09.qmd
        - section: "**Part III — Bivariate Data Treatment**"
          contents:
            - teaching/data-description/session-10.qmd
            - teaching/data-description/session-11.qmd
            - teaching/data-description/session-12.qmd
        - section: "**Resources**"
          contents:
            - teaching/data-description/glossary.qmd

    #--- Decision Making Statistics
    - id: decision-making
      contents:
        - teaching/decision-making-stat/index.qmd
        - teaching/decision-making-stat/session-01.qmd
        - teaching/decision-making-stat/session-02.qmd
        - teaching/decision-making-stat/session-03.qmd
        - teaching/decision-making-stat/session-04.qmd
        - teaching/decision-making-stat/session-05.qmd
        - teaching/decision-making-stat/session-06.qmd
        - teaching/decision-making-stat/session-07.qmd
        - teaching/decision-making-stat/session-08.qmd
        - teaching/decision-making-stat/session-09.qmd
        - teaching/decision-making-stat/session-10.qmd
        - teaching/decision-making-stat/session-11.qmd
        - teaching/decision-making-stat/session-12.qmd
        - teaching/decision-making-stat/session-13.qmd
        - teaching/decision-making-stat/session-14.qmd
        - teaching/decision-making-stat/session-15.qmd


    # Probability & Statistics
    - id: ece-proba
      contents:
        - teaching/ece-proba/index.qmd
        - section: "Une variable"
          contents:
            - teaching/ece-proba/univariate-data-analysis.qmd
            - teaching/ece-proba/univariate-cdf.qmd
            - teaching/ece-proba/univariate-central-tendency.qmd
            - teaching/ece-proba/probability.qmd
            - teaching/ece-proba/density-function.qmd
            - teaching/ece-proba/normal-distribution.qmd
        - section: "Deux variables"
          contents:
            - teaching/ece-proba/bivariate.qmd
            - teaching/ece-proba/joint-continuous-random-variables.qmd
            - teaching/ece-proba/double-integrals-over-r2.qmd
            - teaching/ece-proba/pair-continuous-rv-joint-distribution.qmd
            - teaching/ece-proba/pair-continuous-rv-marginal-distribution.qmd
            - teaching/ece-proba/revision-two-variables.qmd
        - section: "Convergence et théorèmes limites"
          contents:
            - teaching/ece-proba/convergence-random-variables.qmd
        - section: "Statistique inférentielle"
          contents:
            - teaching/ece-proba/sampling-distribution.qmd
            - teaching/ece-proba/point-estimation.qmd
        - section: "Ressources"
          contents:
            - teaching/ece-proba/notation.qmd
            - teaching/ece-proba/tables.qmd
            - teaching/ece-proba/glossary.qmd
            - teaching/ece-proba/leaderboard.qmd
            - teaching/ece-proba/final-revision.qmd
            - teaching/ece-proba/final-revision-correction.qmd
            - teaching/ece-proba/final-revision-2.qmd
            - teaching/ece-proba/final-revision-2-correction.qmd


      #--- Mathematical Analysis course ---#
    - id: mathematical-analysis
      title: "Mathematical Analysis"
      contents:
        - teaching/mathematical-analysis/index.qmd
        - section: "**Module 1 - Derivées et Élasticité**"
          contents:
            - teaching/mathematical-analysis/derivatives.qmd
            - teaching/mathematical-analysis/elasticity.qmd
        - section: "**Module 2 - Optimisation univariée**"
          contents:
            - teaching/mathematical-analysis/intro-optimization.qmd
        - section: "**Module 3 - Fonctions bivariées**"
          contents:
            - teaching/mathematical-analysis/bivariate.qmd
        - section: "**Module 4 - Optimisation bivariée**"
          contents:
            - teaching/mathematical-analysis/matrices.qmd
        - section: "**Module 5 - Recherche operationnelle**"
          contents:
            - teaching/mathematical-analysis/operations-research.qmd
        - section: "**Révisions**"
          contents:
            - teaching/mathematical-analysis/revision-midterm.qmd
            - teaching/mathematical-analysis/revision-final.qmd
            - teaching/mathematical-analysis/revision-final-2.qmd



  page-footer:
    left: "Built with [Quarto](https://quarto.org) · Source on [<i class='bi bi-github'></i> GitHub](https://github.com/guillaumegilles/guillaumegilles.github.io)"
    center: "This site respects your privacy — no cookies, no tracking."

  # -------------------------- SOCIAL METADA ------------------------ #
  # The favicon for your site provides an icon for browser tabs and
  # other sites that link to yours
  favicon: assets/favicon.png

  # Enhanced appearance when someone links to your site on Twitter
  twitter-card:
    image: assets/og-image.jpg
    card-style: summary_large_image

  # Open Graph protocol is a specification that enables richer sharing
  # of links to articles on the web
  open-graph:
    image: assets/og-image.jpg

# ------------------------------------------------------------------- #
#                             HTML Configuration                      #
# ------------------------------------------------------------------- #
format:
  html:
    toc: true
    toc-depth: 3
    smooth-scroll: true
    citations-hover: true
    citation-location: margin
    theme: assets/dark.scss
    include-in-header: assets/lang-switch.html
