project:
  type: website
  output-dir: docs
  render:
    - "!second-brain/"
    - "!digital-garden/*/*.md"

website:
  title: "Guillaume Gilles"
  site-url: https://guillaumegilles.github.io/
  repo-url: https://github.com/guillaumegilles/guillaumegilles.github.io/
  repo-actions: [edit]
  description: "Understanding the world with the help of data."
  search: true
  favicon: images/cat.png
  page-navigation: true
  open-graph: true
  google-analytics: G-6BXJC408ED
  navbar:
    title: false
    right:
      - text: "About"
        href: about.qmd
      - text: "Digital Garden"
        href: index.qmd

  page-footer:
    center: "&#169; 2024 Guillaume Gilles"
    right:
      - icon: github
        href: https://github.com/guillaumegilles
      - icon: linkedin
        href: https://www.linkedin.com/in/guillaumegilles
      - icon: rss
        href: index.xml
      - text: Kaggle
        href: https://www.kaggle.com/guillaumegilles
      - text: Contact
        href: mailto:guillaumegilles@me.com
      - text: Curriculum Vitae
        href: curriculum-vitae.qmd
      - text: License
        href: LICENSE.md

  comments:
    utterances:
      repo: guillaumegilles/guillaumegilles.github.io
      label: comments
      theme: github-light
      issue-term: og:title

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc: true
    toc-depth: 3
    link-external-icon: true
    css: ./assets/css/styles.css
