---
# title: Curriculum Vitae
format: pdf
---

## Expérience Professionnelle

**Économiste et Statisticien**
Banque de France
2020 – Aujourd’hui

- Responsable des analyses macroéconomiques et des prévisions pour la région Nouvelle-Aquitaine, couvrant des sujets tels que l’inflation, la croissance et les tendances économiques.
- Rédaction mensuelle de rapports de synthèse sur les tendances économiques régionales, destinés à éclairer les décisions stratégiques des chefs d’entreprise.
- Participation active à l’élaboration de scénarios économiques et à l’analyse de données, en collaboration avec d’autres institutions régionales.

**Chargé d’Enseignement en Statistiques**
ESSCA Bordeaux
2024 – Aujourd’hui

- Enseignement des statistiques descriptives et inférentielles aux étudiants du programme Grande École, avec une approche pédagogique adaptée aux différents niveaux des étudiants.
- Conception de supports pédagogiques et d’études de cas pratiques, mettant l’accent sur l'application des concepts statistiques dans la prise de décision.

**Chargé d’Enseignement en Analyse Financière**
INSEEC MSc & MBA
2019 – Aujourd’hui

- Cours théoriques et pratiques en analyse financière pour des étudiants de niveau master, couvrant l’analyse des états financiers, l’évaluation des entreprises et la gestion des risques financiers.
- Élaboration de cas pratiques basés sur des données réelles pour renforcer la compréhension des concepts clés et leur application dans le monde professionnel.

**Analyste Financier Senior**
Banque de France
2011 – 2020

- Analyse approfondie de la solvabilité des grandes entreprises françaises, avec une spécialisation dans les comptes consolidés (IAS/IFRS et normes françaises).
- Évaluation des risques de défaut et formulation de recommandations sur les limites de crédit, permettant aux banques commerciales d'accéder aux financements du marché interbancaire.
- Production de rapports financiers détaillés, facilitant la prise de décisions stratégiques par les institutions bancaires.

## Formations

- Certification en Data Science
ENSAE – ENSAI Formation Continue (CEPE)
2023

- Expertise en apprentissage automatique (machine learning) et apprentissage profond (deep learning), incluant SVM, boosting, et réseaux de neurones. Réalisation d’un projet fil rouge tout au long de la formation pour appliquer les concepts théoriques.
Master MIAGE 	Université de Bordeaux	2020 – 2022
Master Finance 	IAE Bordeaux	2018 – 2019

## Langues & Compétences Techniques

- **Français** : Langue maternelle
- **Anglais** : Courant (C1)
- **Python** : pandas, scikit-learn
- **R** : tidyverse, tidymodels