---
Title: "Guillaume Gilles"
---

## Expérience Professionnelle

### Statisticien et Économiste	Banque de France	2020 – Aujourd’hui

Analyses macroéconomiques des prévisions pour la région Nouvelle-Aquitaine, couvrant des sujets tels que l’inflation, la croissance et les tendances économiques. Chaque mois, je rédige des rapports de synthèse sur les tendances économiques régionales, destinés à éclairer les décisions stratégiques des chefs d’entreprise.

### Chargé d’Enseignement	ESSCA Bordeaux	2024 – Aujourd’hui

J’enseigne statistiques, descriptives et inférentielles, ainsi que le management du système d’information aux étudiants du programme Grande École. Je privilégie une approche pédagogique adaptée aux différents niveaux des étudiants pour que chaque étudiant puisse s’épanouir.

### Chargé d’Enseignement	INSEEC MSc & MBA	2019 – Aujourd’hui

J’approfondis l’analyse financière pour des étudiants de niveau master pour les rapprocher de cas concrets et renforcer la compréhension des concepts clés et leur application dans le monde profes-sionnel.

### Analyste Financier Senior	Banque de France	2011 – 2020

J’analysais la solvabilité des grandes entreprises françaises, avec une spécialisation dans les comptes consolidés (IAS/IFRS et normes françaises). Au travers de rapports financiers détaillés, mes études permettaient de formaliser des recommandations sur le risque de crédit facilitant ainsi la prise de décisions stratégiques par les institutions bancaires.

### Comptable	KPMG	2009

•	Stage de fin d’étude (cf. Licence) sur le contrôle et la comptabilisation des factures fournisseurs.
•	Facturation clients et suivi règlement ainsi que participation aux clôtures mensuelles et an-nuelles.

## Formations
### Certification Data Scientist	ENSAE – ENSAI Formation Continue (CEPE)	2023
### Master MIAGE 	Université de Bordeaux	2020 – 2022
### Master Finance 	IAE Bordeaux	2018 – 2019
### Certification Analyste financier confirmé	ESSEC	2015 - 2016
### Licence Science de Gestion	IAE Amiens	2006 - 2009

## Soft Skills

Français (langue maternelle) / Anglais (courant - C1) / Travail en équipe et collaboration, pédagogie, résolution de problème, passionné par le machine learning et le deep learning

## Hard Skills

VBA, Python (pandas, scikit-learn, PyTorch, 🤗 Transformers), R (tidyverse, tidymodels), Git
Learning Management System (LMS): Moodle(https://moodle.org/), Boostcamp