---
title: "G&#178;"
# Citations
bibliography: references.bib
citation-location: margin
---

# Hello there!

Welcome on my personal website, I am Guillaume Gilles.

I’m designing my website with the philosophy of "[digital garden](https://maggieappleton.com/garden-history)".
The concept dates back to 1998 when [Mark Bernstein](https://www.markbernstein.org/) introduced the idea of the "hypertext garden", advocating for online spaces where individuals can explore and discover at their own pace.
A digital garden differs from a traditional blog. Instead of offering polished articles arranged in reverse chronological order, these sites function more like freeform, evolving wikis—constantly in progress and open to growth. [@appletonBriefHistoryEthos2020]

## Some navigation guidelines

::: {.callout-tip}
- To get to know me, I invite you to read my [about](about) page.
- To know more about what I am tinkering, jump down to [Now](index#now) section
- [Yellow Pages](index.qmd#digital-gardens) section is where a keep track of interesting website.
- [Digital Garden](digital-garden) page (⬆ menu in the navbar) to discover and deep dive into my different projects.
- [Teaching](teaching) page (⬆ menu in the navbar) lists my materials for my Business Schools' classes.
:::

## Now

### Reading

Yann Le Cun, ‘Quand la machine apprend: la révolution des neurones artificiels et de l'apprentissage profond’

### Programming

[Creating a AI agent](https://guillaumegilles.github.io/kaggle-llm-20-questions/) based on open source LLM: just an excuse to work on LLM, prompt engineering, fine-tuning, RAG, etc.

### Listening

**The Beatles, ‘Sgt. Pepper’s Lonely Hearts Club Band’** - CAPITOL, 1967

For the Beatles, it was a decisive goodbye to screaming crowds, world tours, and assembly-line record making.
“We were fed up with being Beatles,” Paul McCartney said decades later.
“We were not boys, we were men … artists rather than performers.”
Sgt. Pepper christened the Summer of Love with the lavish psychedelic daydream “Lucy in the Sky With Diamonds,” the jaunty Ringo Starr-sung communality anthem “With a Little Help From My Friends,” the album-closing multilayered masterwork, “A Day in the Life,” and the title track, which introduced the alter egos the Beatles had developed for the ambitious project.
“It liberated you,” McCartney said. “You could do anything.”
It is hard to imagine a more perfect setting for the Victorian jollity of John Lennon’s “Being for the Beneﬁt of Mr. Kite!” (inspired by an 1843 circus poster) or the sumptuous melancholy of McCartney’s “Fixing a Hole,” with its blend of antique shadows (a harpsichord played by the Beatles’ producer George Martin) and modern sunshine lead guitar executed with ringing precision by George Harrison).
The Sgt. Pepper premise was a license to take their music in every direction — rock spent the rest of the Sixties trying to keep up. [@stone500GreatestAlbums2023]

## Yellow Pages

::: {.callout-note}
The [yellow pages](https://en.wikipedia.org/wiki/Yellow_pages) are telephone directories of businesses, organized by category rather than alphabetically by business name.
The directories were originally printed on yellow paper, as opposed to white pages for non-commercial listings.
The traditional term "yellow pages" is now also applied to online directories of businesses.
:::

### Machine Learning & Deep Learning

- [Andrej Karpathy](https://karpathy.ai/)
- [Andrew Ng](https://www.andrewng.org/)
- [Ian Goodfellow](https://www.iangoodfellow.com/)
- [Julia Silge](https://juliasilge.com/)
- [Wes McKinney](https://wesmckinney.com/)
- [Ilya Sutskever](https://www.cs.toronto.edu/~ilya/)

#### Deep Learning Conspiracy [@lecunQuandMachineApprend2019]

- [Geoffrey Hinton](https://www.cs.toronto.edu/~hinton/)
- [Yann Le Cun](https://yann.lecun.com/)
- [Yoshua Bengio](https://yoshuabengio.org/)

#### Stunning explanations

- [Distill](https://distill.pub/)
- [R2D3](http://www.r2d3.us/)
- [Christopher Olah Blog](https://colah.github.io/)
- [Anthropic Research Blog](https://www.anthropic.com/research)

### Digital Gardens

- [Maggie Appleton](https://maggieappleton.com/)
- [Tom Critchlow](https://tomcritchlow.com/)
- [Gwern Branwen](https://gwern.net/index)

### POSSE

- [Tantek Çelik](http://tantek.com/)
- [Cory Doctorow](https://craphound.com/)
- [Matt Mullenweg](https://ma.tt/)

## Colophon

::: {.callout-note}
In publishing, a [colophon](https://en.wikipedia.org/wiki/Colophon_(publishing)) (/ˈkɒləfən, -fɒn/) is a brief statement containing information about the publication of a book such as an "imprint" (the place of publication, the publisher, and the date of publication).
A colophon may include the device logo  of a printer or publisher.
Colophons are traditionally printed at the ends of books, but sometimes the same information appears elsewhere and many modern (post-1800) books bear this information on the title page or on the verso of the title leaf, which is sometimes called a biblio page or the copyright page.
:::

<!-- kottke.org is hosted by Arcustech and published using Movable Type. Memberful powers kottke.org memberships. I send out the newsletter with Sendy. If you would like to advertise on kottke.org, contact the folks at Carbon Ads.

Thanks to all of the guest editors over the years who have lent their energy and perspective to the site, including Edith Zimmerman, Chrysanthe Tenentes, Patrick Tanguay, Tim Carmody, Sarah Pavis, Ainsley Drew, Aaron Cohen, Susannah Breslin, Choire Sicha, and Adam Lisagor. And to Chris Piascik for the awesome illustrations.

Other indispensables: GitHub, Dropbox, Gmail, Chrome, AWS, Sketch, Apple MacBook Air M1, Instapaper, Transmit, TextMate, Emeco Navy Chair, Spotify, Muji Ultrasonic Aroma Diffuser, and Apple AirPods Pro. -->

