---
title: "Untitled"
format: html
---


- linkedIN
- website
- github
- kaggle

Guillaume Gilles
59 Cours le Rouzic
33100 Bordeaux
Mobile : +33 (0)6 34 99 79 74
Courriel : guillaumegilles@me.com
LinkedIn | Github | Kaggle


Expériences
Économiste et statisticien – data analyst	Banque de France	2020 – Aujourd’hui
•	Publication mensuelle de l’évolution de l’activité économique en Nouvelle-Aquitaine, sur la base de données collectées par la Banque de France ;
•	Collecte des chiffres d'affaires mensuels des commerçants de Nouvelle-Aquitaine pour la pu-blication nationale du Commerce de détails, grâce à des outils développés en interne en VBA ;
•	Réalisation de tableaux de bord économique mensuels pour la visualisation des données de la région Nouvelle-Aquitaine. Créé avec PowerPoint, il permet de soutenir les présentations dans les instances régionales et chambres consulaires.
Intervenant pédagogique 	INSEEC MSc & MBA	2019 – Aujourd’hui
•	Animation des cours d’analyse financières et stratégie d’investissement auprès des élèves de Master ;
•	Création du syllabus ainsi que tous les supports de cour ;
Analyste financier senior	Banque de France	2011 – 2020
•	Analyses financière critique et retraitements des comptes consolidés en IAS/IFRS et en normes françaises pour attribuer la cotation Banque de France sur un portefeuille de 40 grandes en-treprises (comptes consolidés) ;
•	Échanges réguliers et participation aux réunions d'analystes financiers et aux entretiens bilaté-raux avec les directeurs et directeurs financiers des groupes.
•	Participation aux groupes de réflexion et de travaux pour améliorer la méthodologie et la ro-bustesse de l’analyse financière à la Banque de France afin d'améliorer la prédiction du défaut ;
•	Sensibilisation des publics défavorisés sur des thématiques essentielles d'économie, de gestion et de finance.

Kaggle
Hands on practive on Python, machine learning and deep learning to develop algorithm

Formations
Certification de data science	ENSAE – ENSAI Formation Continue (CEPE)	2023
La certification offre des enseignements approfondis sur le « pipeline » d’un projet de machine learning, de l’analyse exploratoire des données jusqu’au déploiement des algorithmes de machine learning (modèle linéaire généralisé, bagging, boosting, SVM, deep learning, etc.). La théorie est ren-forcée par un projet tutoré.

Projet : « Prédiction de la défaillance d’entreprises »
En utilisant le big data de la Banque de France et de l’INSEE, création d’algorithmes de machine lear-ning en supervised learning pour prédire un événement rare, la défaillance d’une entreprise, c’est-à-dire l’événement judicaire accompagné d’une cessation de paiement.


Master MIAGE 	Université de Bordeaux	2020 – 2022
Matières :
 
•	Informatique décisionnelle
•	Processus stochastique
•	Programmation mathématique et optimisation
•	Réseaux
•	Sécurité des systèmes d’information
•	Audit du système d’information
 

Projet : « Lazy Investment »
Création d’algorithmes de machine learning, en supervised learning, pour déterminer les varia-tions des cours boursiers d’entreprises françaises cotées en fonction d’une analyse des sentiments (natural language processing - NLP).
Master Finance 	IAE Bordeaux	2018 – 2019
Matières :
 
•	Securities and FX Products
•	Derivatives Products
•	Financial Product Life Cycle
•	Risk Management
•	Operational Fund Management
 

Mémoire : « La technologie de la blockchain dans la finance »
Certificat d’analyse financière	ESSEC Business School	2015 – 2016
Mémoire : « Affiner l’analyse du risque de crédit des sociétés foncières à la Banque de France »
Licence Science de Gestion	Université de Picardie Jules Verne	2008 – 2009
Langues
•	Français : maternelle
•	Anglais : courant - C1
Hard Skills
•	Python (Pandas, Scikit-Learn)
•	R (Tidyverse, Tidymodels)
•	Unix system
•	Git
Loisirs
•	Lecture de romans et essais ;
•	Sport (jogging, karaté : 2ème DAN) ;
•	Machine learning ;
•	Science-fiction (Dune, Star Wars, Blade Runner, etc.).

---

---
layout: cv
title: Guillaume Gilles' CV
---

# Guillaume Gilles

Data analyst, Finance lecturer

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>

## Currently

I am passionate about artificial intelligence, machine learning, and deep learning. I am honing my skill in time series and NLP with a personal project inspired by an American publication, Lazy Prices. Based on French financial publications, my machine learning model tries to predict a financial investment strategies.

## Education

`2020 - 2021`
**Master MIAGE: Computer Science Applied to Business Management** University of Bordeaux

`2018 - 2019`
**Master Corporate and Banking Investment** IAE Bordeaux, business school of the University of Bordeaux

## Professional Explerience

`2020 - present`
Economist & Statistician, *Banque de France*, Bordeaux, France

`2019 - present`
Lecturer, *INSEEC*, Bordeaux, France

`2011 - 2020`
Senior Financial Analyst, *Banque de France*, Paris & Bordeaux, France

<!-- ### Footer

Last updated: March 2023 -->