---
title: Preface
comments: false
---

Welcome to **Introduction to Business Statistics**, IBS, a web textbook I've created to use in my statistics classes at ESSCA, Bordeaux.

## About Introduction to Business Statistics

Introduction to Business Statistics is designed to meet the scope and requirements of one-semester statistics course for business, economics, and related majors for undergraduate students in business school. Core statistical concepts and skills have been augmented with practical business examples, scenarios, and exercises. The result is a meaningful understanding of the discipline which will serve students in their business careers and real-world experiences.

## Syllabus

The syllabus can be found [here](syllabus.qmd)

### Course goals & objectives

### Class meetings

This class is taught for students PGE programm during the spring semester at Bordeaux

### Required materials

### Class meetings

### Exams

### Work load

You are expected to put in about 4-6 hours of work / week outside of class. Some of you will do well with less time than this, and some of you will need more

## Acknowledgements

IBS is created with [Quarto](https://quarto.org/docs/books/) and hosted on [Github]().