---
title: MSc2 Manager Financier & Digitalisation Bancaire - Analyse financière et diagnostic
author: Guillaume Gilles
---

# Manager Financier & Digitalisation Bancaire

[syllabus](./analyse-financi%C3%A8re-diagnostic-syllabus.qmd)

## OBJECTIFS

Ce programme innovant en digitalisation bancaire et assurance a pour objectif d’accompagner la révolution actuelle provoquée par la digitalisation de ce secteur. Il prépare les apprenants aux nouveaux métiers bancaires mais aussi aux impacts de la digitalisation sur les processus de front, back et middle office aussi bien pour la banque de détail, la banque d’investissement que de la banque privée.

Il permet de former des experts en banque et assurance en intégrant les compétences métiers de la digitalisation : conseiller professionnels, chargé de grands comptes, conseiller particuliers, expert en assurances.

Les objectifs en termes de compétences sont d’être capable de :

- Analyser les données stratégiques de l’entreprise
- Contrôler et piloter l’activité de l’entreprise
- Assurer la pérennité de l’activité de l’entreprise
- Emettre des recommandations financières et maîtriser la communication

# Plan du cours

1. Découvrir la Banque de France et la cotation
2. Introduction aux comptes consolidés et à leurs analyses financièrs
3. Analyse du compte de résultat
4. Analyse du bilan
5. Analyse du tableau des flux de trésorerie
6. Examen final sur un cas pratique

# Évaluations

1. CC - QCM : 30 % de la note finale ;
2. Examen final - cas pratique : 70 % de la note finale.