---
title: Syllabus du cours Diagnostic stratégique et décision
---

## DIAGNOSTIC STRATEGIQUE ET DECISION

Maitriser les concepts fondamentaux du diagnostic financier afin de mener une analyse globale de l’entreprise et d’établir des prévisions financières. Sources d’information, analyse sectorielle, analyse de la performance économique et financière, élaboration de prévisions.

## Résumé du cours : objectifs pédagogiques et professionnels

> Approfondir l’analyse financière par l’approche bancaire réseau. Connaitre le patrimoine de l’entreprise (bilan) et son cycle d’exploitation. Faire une lecture « commerciale » de la liasse fiscale et établir un plan de financement prévisionnel.

## Connaissances et compétences RNCP visées

- 2.6 Appliquer les bases juridiques indispensables au bon fonctionnement d’une société et contrôler le respect des procédures ;
- 4.16 Appliquer les normes comptables et financières internationales (USGAP, IFRS) ;
- 4.18 Coordonner et animer une équipe dans le cadre d’un projet en :
  - Planifiant les échéances
  - Répartissant, hiérarchisant et priorisant les tâches
  - Suivant l’évolution du projet
  - Réalisant un reporting

## Plan de cours

| Date             | Contenu de la séance                                                        | Type de cours                         | Travail préparatoire                                                                                                                                         |
| ---------------- | --------------------------------------------------------------------------- | ------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| 1re demi-journée | découvrir la Banque de France et sa cotation                                | cours magistral                       | Lecture: [Guide référence](https://www.banque-france.fr/fr/system/files/2023-08/Banque%20de%20France%20%E2%80%93%20Entreprises_guide-fiben-ref-cotation.pdf) |
| 2e demi-journée  | introduction sur les comptes consolidés et l'analyse financière             | cours magistral                       |                                                                                                                                                              |
| 3e demi-journée  | analyse du compte de résultat + CC sur les demi-journées 1 et 2             | cours magistral et exercice en groupe |                                                                                                                                                              |
| 4e demi-journée  | analyse du bilan                                                            | cours magistral et exercice en groupe |                                                                                                                                                              |
| 5e demi-journée  | analyse du tableau des flux de trésorerie + CC sur les demi-journées 3 et 4 | cours magistral et exercice en groupe |                                                                                                                                                              |
| 6e demi-journée  | examen final sur un cas pratique                                            | examen individuel                     |                                                                                                                                                              |

## Bibliographie indicative

- [Vernimmen](https://www.vernimmen.net/Vernimmen/Qu_est_ce_que_le_vernimmen.php)
- [La Lettre Vernimmen.net](https://www.vernimmen.net/Lire/Lettre_Vernimmen.php) (_newsletter mensuelle_)

## Évaluation du module

1. CC - QCM : 30 % de la note finale ;
2. Examen final - cas pratique : 70 % de la note finale.
