---
title: Teaching in Age of Generative AI
draft: true
---

- Khanamigo
- hausse dêutilisation de GPT à la rentrée des classes ou aprés les vacances
- embrace it rather than fight:
- new course design / new evaluation

## Pédagogie - Chose importante

[@dehaeneIdeeDansTete2024]

**= conseil scientifique de l’éducation nationale**

1. contact visuelle : regarder dans les yeux (un chatbot ne peut pas)
2. pomodo technique : 15/20 dêenseignement et on passe à un exercice de mise en appiclation (éviter à tout prix, la lecture magistrale)
3. apprentissage actif:  questions, débats, exercices

## ChatGPT as a TA (teacher assistant)

image du mainecoon pour illuster le TA, son nom I/Othello
- Othello
- I\O origne numérique
- othello = intello en français

Bein g mindful how to use generative AI: it shouldn't be used instead of your brain (critical thinking) but pairing its capability with understing of concepts.
- [@https://www.theintrinsicperspective.com/p/brain-drain]
- [@https://www.microsoft.com/en-us/research/publication/the-impact-of-generative-ai-on-critical-thinking-self-reported-reductions-in-cognitive-effort-and-confidence-effects-from-a-survey-of-knowledge-workers/#:~:text=Specifically%2C%20higher%20confidence%20in%20GenAI,response%20integration%2C%20and%20task%20stewardship.]


## Gamification de la société

[@sheldonMultiplayerClassroomDesigning2020a]

The **class** is the game and the classroom is the game board.

## Encourager la prise de risque:

Ne pas sanctioner les erreurs, elles sont nécessaires pour l’apprentissage
+ Carol Dweck fixed\growth mindset
+ [@dehaeneIdeeDansTete2024]
fixed mindest : l’erreur est décourager, alors on ne prend pas de risque de peur de faire une erreur. L’erreur est stigmatisante.
growth: erreur est une étape essentielle et nécessaire de l’apprentissage, la personne n’a pas peur de sorit de sa zone de confiance et essayer de nouvelles choses.
