{
  "hash": "1b6cb99a0adcb248ad1c8da82b91c514",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Statistiques descriptives à deux variables\"\nabstract: |\n  Ce chapitre prolonge la statistique descriptive au cas de deux caractères\n  observés simultanément sur une même population. On introduit la\n  **distribution conjointe** d'un couple de variables via les tableaux de\n  contingence, puis les **distributions marginales** et\n  **conditionnelles**, indispensables pour décrire les relations entre\n  variables. Le chapitre formalise ensuite la notion d'**indépendance** et la\n  caractérisation par factorisation des fréquences. Enfin, il présente le\n  **test du khi-deux d'indépendance** (conditions, construction des effectifs\n  théoriques, statistique, degrés de liberté, règle de décision) avec une\n  méthodologie complète d'interprétation.\ndate-modified: 2026-03-22\n---\n\n[📍 Retour à la carte du cours](index.html)\n> Dans tout ce chapitre, on étudie deux variables observées sur une même population finie de taille $n$.\n\n## Distribution conjointe\n\nLorsqu'on observe **deux variables simultanément** sur chaque individu d'une population, on ne peut pas les étudier séparément sans perdre l'information sur leur relation. La distribution conjointe capture précisément cette information : elle recense le nombre (ou la fréquence) d'individus pour chaque combinaison de modalités des deux variables. Son outil de représentation naturel est le **tableau de contingence**.\n\nSoit $P$ une population et $(x,y)$ un couple de variables, c'est-à-dire une application\n$$\n(x,y):P\\to E_x\\times E_y,\n\\qquad\nu\\mapsto (x(u),y(u)).\n$$\n\nLes variables peuvent être qualitatives ou quantitatives (discrètes ou regroupées en classes). On parle de **couple statistique** : chaque individu est décrit par **deux** caractères simultanément, ce qui permet d'étudier la relation entre eux.\n\n::: {.callout-note}\n### Définitions\n\nSi $x_1,\\dots,x_p$ sont les modalités de $x$ et $y_1,\\dots,y_q$ celles de $y$ :\n\n- $n_{ij}$ est l'**effectif conjoint** du couple $(x_i,y_j)$ : le nombre d'individus ayant simultanément $x=x_i$ et $y=y_j$,\n- $f_{ij}=n_{ij}/n$ est la **fréquence conjointe**,\n- l'ensemble des triplets $(x_i,y_j,n_{ij})$ forme la **distribution conjointe**.\n\nOn a toujours :\n$$\n\\sum_{i=1}^p\\sum_{j=1}^q n_{ij}=n,\n\\qquad\n\\sum_{i=1}^p\\sum_{j=1}^q f_{ij}=1.\n$$\n:::\n\nLa représentation standard est le **tableau de contingence** : un tableau à double entrée de dimensions $p\\times q$ dont la cellule $(i,j)$ contient $n_{ij}$ (ou $f_{ij}$), complété par les totaux marginaux en marge.\n\n::: {.callout-caution}\n### Exemple 1 - Tableau conjoint et fréquence globale\n\nUne enquête porte sur 2000 habitants. On observe :\n\n| Quartier / Revenu annuel | $[10000,20000[$ | $[20000,50000[$ | $[50000,100000[$ | Total |\n|---|---:|---:|---:|---:|\n| A | 413 | 298 | 288 | ? |\n| B | 227 | 193 | 170 | ? |\n| C | 167 | 132 | 112 | ? |\n| Total | ? | ? | ? | 2000 |\n\n1. Compléter le tableau.\n2. Calculer la fréquence d'habitants ayant un revenu d'au moins 20 000.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution - Exemple 1 (résultats)\n\n- Totaux lignes :\n  - A : 999,\n  - B : 590,\n  - C : 411.\n- Totaux colonnes :\n  - $[10000,20000[$ : 807,\n  - $[20000,50000[$ : 623,\n  - $[50000,100000[$ : 570.\n- Fréquence revenu $\\ge 20000$ :\n$$\n\\frac{623+570}{2000}=\\frac{1193}{2000}=0{,}5965.\n$$\n:::\n\n## Distributions marginales\n\nUne fois le tableau de contingence construit, on peut retrouver la distribution de chaque variable **individuellement** en faisant la somme sur l'autre variable. Ces distributions dites **marginales** correspondent aux totaux de lignes et de colonnes du tableau — elles figurent littéralement dans les **marges** du tableau. Elles permettent de calculer les indicateurs habituels — moyenne, médiane, écart-type — pour chaque variable, indépendamment de l'autre.\n\nÀ partir de la distribution conjointe, on obtient les distributions de chaque variable prise séparément.\n\n::: {.callout-note}\n## Définitions\n\n- Effectif marginal de $x_i$ :\n  $$n_{i\\cdot}=\\sum_{j=1}^q n_{ij}, \\qquad f_{i\\cdot}=\\frac{n_{i\\cdot}}{n}.$$\n- Effectif marginal de $y_j$ :\n  $$n_{\\cdot j}=\\sum_{i=1}^p n_{ij}, \\qquad f_{\\cdot j}=\\frac{n_{\\cdot j}}{n}.$$\n\nLes couples $(x_i,n_{i\\cdot})$ et $(y_j,n_{\\cdot j})$ définissent les **distributions marginales** de $x$ et $y$.\n:::\n\n::: {.callout-important}\n## Propriété fondamentale\n\nLes distributions marginales vérifient :\n$$\n\\sum_{i=1}^p n_{i\\cdot} = \\sum_{j=1}^q n_{\\cdot j} = n,\n\\qquad\n\\sum_{i=1}^p f_{i\\cdot} = \\sum_{j=1}^q f_{\\cdot j} = 1.\n$$\n\nOn retrouve bien des distributions complètes sur chacune des deux variables.\n:::\n\nCes marginales permettent de calculer les indicateurs usuels de chaque variable (moyenne, médiane, écart-type, etc.) si le type de variable le permet. Pour une variable quantitative regroupée en classes, on utilise les **centres de classes** $c_j$ comme valeurs représentatives :\n$$\n\\bar x = \\sum_{i=1}^p c_i\\, f_{i\\cdot}.\n$$\n\n::: {.callout-caution}\n## Exemple 2 - Exploiter les marginales\n\nReprendre l'exemple 1.\n\n1. Déterminer les distributions marginales de \"Quartier\" et de \"Revenu annuel\".\n2. Pour « Revenu annuel » (en classes), estimer la moyenne à l'aide des centres de classes.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution - Exemple 2 (idée)\n\n- Marginale de \"Quartier\" : totaux de lignes / 2000.\n- Marginale de \"Revenu annuel\" : totaux de colonnes / 2000.\n- Moyenne approximative du revenu :\n$$\n\\bar y\\approx\\sum_j c_j f_{\\cdot j},\n$$\noù $c_j$ est le centre de la classe $j$.\n:::\n\n## Distributions conditionnelles\n\nLes distributions marginales décrivent chaque variable dans l'ensemble de la population. Mais que se passe-t-il **au sein d'un sous-groupe** ? La distribution conditionnelle répond à cette question : elle décrit la répartition d'une variable lorsqu'on **fixe la modalité de l'autre**. Comparer les distributions conditionnelles de $y$ pour différentes valeurs de $x$ est le premier outil pour détecter visuellement une association entre les deux variables.\n\nUne ligne (resp. colonne) du tableau de contingence décrit la répartition conditionnelle de $y$ sachant $x=x_i$ (resp. de $x$ sachant $y=y_j$).\n\n::: {.callout-note}\n## Définitions\n\n- Fréquence conditionnelle de $y_j$ sachant $x_i$ :\n  $$f_{y_j\\mid x_i}=\\frac{n_{ij}}{n_{i\\cdot}}.$$\n- Fréquence conditionnelle de $x_i$ sachant $y_j$ :\n  $$f_{x_i\\mid y_j}=\\frac{n_{ij}}{n_{\\cdot j}}.$$\n:::\n\n::: {.callout-important}\n## Propriétés\n\nPour chaque $i$ fixé, les fréquences conditionnelles de $y$ sachant $x_i$ forment une distribution complète :\n$$\n\\sum_{j=1}^q f_{y_j\\mid x_i} = \\frac{1}{n_{i\\cdot}}\\sum_{j=1}^q n_{ij} = \\frac{n_{i\\cdot}}{n_{i\\cdot}} = 1.\n$$\n\nOn peut donc calculer la **moyenne conditionnelle** de $y$ sachant $x=x_i$ :\n$$\n\\bar y_{|x_i} = \\sum_{j=1}^q c_j\\, f_{y_j\\mid x_i},\n$$\noù $c_j$ est la valeur (ou le centre de classe) de $y_j$.\n:::\n\nLes distributions conditionnelles servent à comparer les profils entre sous-populations. Si ces profils sont très différents d'une modalité de $x$ à l'autre, cela suggère une association entre $x$ et $y$. Si au contraire ils sont tous semblables à la distribution marginale de $y$, les deux variables semblent indépendantes.\n\n::: {#cell-fig-bivariate-overview .cell .column-screen-inset execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![Distribution conjointe, marginales et conditionnelles illustrées sur les données de l'exemple 1 (2000 habitants). **Gauche** : fréquences conjointes $f_{ij}$ (intensité de la couleur). **Droite** : distributions conditionnelles du revenu pour chaque quartier — si les barres étaient identiques d'un quartier à l'autre, les variables seraient indépendantes.](bivariate_files/figure-html/fig-bivariate-overview-output-1.png){#fig-bivariate-overview width=1046 height=417 fig-align='center'}\n:::\n:::\n\n\n::: {.callout-caution}\n## Exemple 3 - Profil conditionnel\n\nDans l'exemple 1, déterminer la distribution conditionnelle du revenu sachant que l'on est dans le quartier A.\nPuis identifier la classe de revenu majoritaire dans ce quartier.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution - Exemple 3 (résultats)\n\nComme $n_{A\\cdot}=999$ :\n$$\n\\left(\\frac{413}{999},\\frac{298}{999},\\frac{288}{999}\\right)\n\\approx (0{,}413,0{,}298,0{,}288).\n$$\nLa classe majoritaire est $[10000,20000[$.\n:::\n\n## Indépendance de deux variables\n\nDeux variables sont **indépendantes** si connaître la modalité de l'une n'apporte aucune information sur la distribution de l'autre — autrement dit, si toutes les distributions conditionnelles sont identiques à la distribution marginale. En pratique, cette condition se traduit par une relation de **factorisation** des fréquences conjointes, ce qui permet de la vérifier cellule par cellule dans le tableau de contingence.\n\n::: {.callout-note}\n## Définition\n\nLes variables $x$ et $y$ sont **indépendantes** si, pour toute modalité $x_i$, la distribution conditionnelle de $y$ sachant $x_i$ est égale à la distribution marginale de $y$ :\n$$\nf_{y_j\\mid x_i} = f_{\\cdot j} \\quad \\text{pour tout } i,j.\n$$\nAutrement dit, la valeur prise par $x$ ne modifie pas la répartition de $y$.\n:::\n\n::: {.callout-important}\n## Caractérisation équivalente (admise)\n\nLes propriétés suivantes sont équivalentes :\n\n1. $x$ et $y$ sont indépendantes.\n2. Pour tout $i,j$,\n   $$f_{ij}=f_{i\\cdot}f_{\\cdot j}.$$\n3. Pour tout $i,j$,\n   $$n_{ij}=\\frac{n_{i\\cdot}n_{\\cdot j}}{n}.$$\n\n**Pourquoi ?** Si $f_{y_j\\mid x_i}=f_{\\cdot j}$, alors :\n$$\nf_{ij}=\\frac{n_{ij}}{n}=\\frac{n_{ij}}{n_{i\\cdot}}\\cdot\\frac{n_{i\\cdot}}{n}=f_{y_j\\mid x_i}\\cdot f_{i\\cdot}=f_{\\cdot j}\\cdot f_{i\\cdot}.\n$$\nLa fréquence conjointe se **factorise** en le produit des deux fréquences marginales. C'est cette propriété que le test du $\\chi^2$ va exploiter quantitativement.\n:::\n\nEn pratique, l'indépendance se traduit par des profils de lignes (ou colonnes) identiques les uns aux autres.\n\n::: {.callout-caution}\n## Exemple 4 - Vérification rapide\n\nDans un tableau $2\\times 2$ avec\n$$\n\\begin{pmatrix}\n30 & 20\\\\\n15 & 35\n\\end{pmatrix},\n\\quad n=100,\n$$\nvérifier si l'indépendance est satisfaite exactement.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution - Exemple 4\n\nTotaux : lignes $(50,50)$, colonnes $(45,55)$.\nSous indépendance, la case (1,1) devrait valoir $50\\times45/100=22{,}5$ (et non 30).\nDonc les variables ne sont pas indépendantes.\n:::\n\n---\n\n## Test du khi-deux d'indépendance\n\n### Motivation\n\nL'inspection visuelle des distributions conditionnelles ne suffit pas : les écarts observés peuvent être dus au **hasard de l'échantillonnage**. Même si les variables sont parfaitement indépendantes dans la population, un échantillon produira toujours des fréquences conjointes légèrement différentes du produit des marginales. La question est donc : les écarts observés sont-ils **trop grands** pour être attribués au seul hasard ?\n\nLe test du $\\chi^2$ d'indépendance de Pearson fournit une réponse rigoureuse à cette question. L'idée est de :\n\n1. calculer ce que l'on observerait **si l'indépendance était exacte** (effectifs théoriques),\n2. mesurer l'**écart global** entre ces valeurs théoriques et les valeurs réellement observées,\n3. décider si cet écart est significatif en le comparant à une valeur critique issue de la loi $\\chi^2$.\n\nOn teste :\n\n- $H_0$ : indépendance entre $x$ et $y$,\n- $H_1$ : dépendance (association).\n\n### Effectifs théoriques\n\nSous $H_0$, si les variables étaient indépendantes, la fréquence conjointe $f_{ij}$ devrait valoir $f_{i\\cdot}f_{\\cdot j}$ (factorisation). On en déduit l'effectif que l'on devrait observer dans la case $(i,j)$ :\n\n$$\nE_{ij}=n\\,f_{i\\cdot}f_{\\cdot j}=n\\cdot\\frac{n_{i\\cdot}}{n}\\cdot\\frac{n_{\\cdot j}}{n}=\\frac{n_{i\\cdot}\\,n_{\\cdot j}}{n}.\n$$\n\n**Interprétation :** $E_{ij}$ est la part du total $n$ que l'on attribuerait à la case $(i,j)$ si les lignes et les colonnes étaient « proportionnelles » les unes aux autres. Les totaux marginaux $n_{i\\cdot}$ et $n_{\\cdot j}$ sont fixés (ils ne dépendent pas de $H_0$) ; seule la répartition interne change.\n\n::: {.callout-important}\n## Propriété de conservation des marges\n\nLes effectifs théoriques conservent les mêmes totaux que les effectifs observés :\n$$\n\\sum_{j=1}^q E_{ij}=n_{i\\cdot} \\quad\\text{et}\\quad \\sum_{i=1}^p E_{ij}=n_{\\cdot j}.\n$$\nLes marges du tableau ne sont pas modifiées par l'hypothèse $H_0$ : seule la distribution *interne* des cellules est affectée.\n:::\n\n::: {.callout-tip}\n## Règle de Cochran\n\nL'approximation par la loi $\\chi^2$ n'est valide que si les effectifs théoriques sont suffisamment grands :\n\n- au moins **80 %** des $E_{ij}$ sont $\\ge 5$,\n- **aucun** $E_{ij}$ n'est nul ou très proche de zéro.\n\nSi cette condition n'est pas satisfaite, il faut **regrouper** des modalités (fusionner des lignes ou colonnes) jusqu'à ce qu'elle le soit. Un tableau $2\\times 2$ avec tous les $E_{ij}<5$ nécessite le test exact de Fisher.\n:::\n\n### Statistique de test\n\nOn mesure l'écart global entre les effectifs observés $O_{ij}=n_{ij}$ et les effectifs théoriques $E_{ij}$ par la **statistique de Pearson** :\n\n$$\n\\chi^2_{obs}=\\sum_{i=1}^p\\sum_{j=1}^q\\frac{(O_{ij}-E_{ij})^2}{E_{ij}}.\n$$\n\n**Décomposition de la formule :**\n\n- $(O_{ij}-E_{ij})^2$ mesure l'**écart au carré** entre observé et attendu. On élève au carré pour éviter que les écarts positifs et négatifs ne se compensent, et pour pénaliser davantage les grands écarts.\n- On divise par $E_{ij}$ pour **normaliser** : un écart de 10 est beaucoup plus remarquable dans une cellule attendue à 15 que dans une cellule attendue à 500. La division rend les contributions comparables.\n- Plus $\\chi^2_{obs}$ est **grand**, plus les données s'éloignent de l'hypothèse d'indépendance.\n- Si l'indépendance était parfaite ($O_{ij}=E_{ij}$ pour tout $i,j$), on obtiendrait $\\chi^2_{obs}=0$.\n\n### Loi de la statistique sous $H_0$\n\n::: {.callout-note}\n## Résultat (admis)\n\nSous $H_0$ et lorsque les effectifs sont suffisamment grands (condition de Cochran), la statistique $\\chi^2_{obs}$ suit **approximativement** une loi du khi-deux à $\\nu$ degrés de liberté :\n$$\n\\chi^2_{obs} \\underset{H_0}{\\sim} \\chi^2_\\nu,\n\\qquad\n\\nu=(p-1)(q-1).\n$$\n:::\n\n**Pourquoi $(p-1)(q-1)$ degrés de liberté ?**\n\nLe tableau $p\\times q$ contient $pq$ cellules, mais les effectifs ne sont pas libres : les totaux marginaux (lignes et colonnes) sont fixés, ce qui impose $p+q-1$ contraintes (les $p$ totaux de lignes et les $q$ totaux de colonnes, moins 1 car la somme des deux est la même, $n$). Le nombre de cellules « libres » est donc :\n$$\npq - (p+q-1) = (p-1)(q-1).\n$$\nOn peut remplir librement les $(p-1)(q-1)$ premières cellules ; toutes les autres sont alors déterminées par les contraintes sur les marges.\n\n**La loi $\\chi^2_\\nu$ :** c'est une loi continue sur $\\mathbb{R}_+$, asymétrique à droite, dont la densité est nulle en zéro et décroît vers zéro pour les grandes valeurs. Plus $\\nu$ est grand, plus la distribution est étalée vers la droite. La valeur critique $\\chi^2_{1-\\alpha,\\nu}$ est le quantile d'ordre $1-\\alpha$ de cette loi, tabule en annexe.\n\n::: {#cell-fig-chisq-dist .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Densité de la loi $\\chi^2_\\nu$ pour différents degrés de liberté. La zone grisée représente la région de rejet au seuil $\\alpha=5\\%$ pour $\\nu=4$ : on rejette $H_0$ lorsque $\\chi^2_{obs}$ tombe dans cette zone.](bivariate_files/figure-html/fig-chisq-dist-output-1.png){#fig-chisq-dist width=757 height=370 fig-align='center'}\n:::\n:::\n\n\n### Règle de décision\n\nAu seuil $\\alpha$ (risque de première espèce : probabilité de rejeter $H_0$ à tort) :\n\n- on lit la valeur critique $\\chi^2_{1-\\alpha,\\nu}$ dans la table (ou on la calcule),\n- si $\\chi^2_{obs}>\\chi^2_{1-\\alpha,\\nu}$, on **rejette $H_0$** : les données sont incompatibles avec l'hypothèse d'indépendance,\n- si $\\chi^2_{obs}\\le\\chi^2_{1-\\alpha,\\nu}$, on **ne rejette pas $H_0$** : les données sont compatibles avec l'indépendance.\n\n::: {.callout-warning}\n## Vocabulaire important\n\n- **Rejeter $H_0$** ne signifie pas prouver $H_1$ avec certitude : cela signifie que les données observées seraient très improbables si $H_0$ était vraie.\n- **Ne pas rejeter $H_0$** ne signifie pas prouver l'indépendance : cela signifie simplement que les données ne fournissent pas assez de preuves contre $H_0$. L'absence de preuve n'est pas la preuve de l'absence.\n- Le test du $\\chi^2$ détecte l'existence d'une association mais **n'en mesure pas l'intensité**. Un test très significatif sur un grand échantillon peut correspondre à une dépendance très faible en pratique.\n:::\n\n### Valeurs critiques usuelles\n\n| $\\nu$ | $\\alpha=10\\%$ | $\\alpha=5\\%$ | $\\alpha=1\\%$ |\n|---:|---:|---:|---:|\n| 1 | 2,706 | 3,841 | 6,635 |\n| 2 | 4,605 | 5,991 | 9,210 |\n| 3 | 6,251 | 7,815 | 11,345 |\n| 4 | 7,779 | 9,488 | 13,277 |\n| 6 | 10,645 | 12,592 | 16,812 |\n| 9 | 14,684 | 16,919 | 21,666 |\n\n### Méthodologie complète\n\nPour conduire un test du $\\chi^2$ d'indépendance, suivre systématiquement les étapes suivantes :\n\n1. **Poser les hypothèses** : $H_0$ (indépendance) et $H_1$ (dépendance).\n2. **Construire le tableau** avec les effectifs observés $O_{ij}$ et calculer les totaux marginaux.\n3. **Calculer les effectifs théoriques** $E_{ij}=n_{i\\cdot}n_{\\cdot j}/n$.\n4. **Vérifier Cochran** : au moins 80 % des $E_{ij}\\ge 5$ et aucun nul. Sinon, regrouper.\n5. **Calculer la statistique** $\\chi^2_{obs}=\\sum (O_{ij}-E_{ij})^2/E_{ij}$.\n6. **Déterminer les degrés de liberté** $\\nu=(p-1)(q-1)$.\n7. **Lire la valeur critique** $\\chi^2_{1-\\alpha,\\nu}$ dans la table.\n8. **Conclure** en comparant $\\chi^2_{obs}$ à $\\chi^2_{1-\\alpha,\\nu}$, et reformuler dans le contexte du problème.\n\n::: {.callout-caution}\n## Exemple 5 - Application complète\n\nReprendre le tableau de l'exemple 1 et tester l'indépendance entre « Quartier » et « Revenu annuel » au seuil $\\alpha=5\\%$.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution - Exemple 5\n\n**Données (tableau observé)**\n\n| Quartier / Revenu | $[10k;20k[$ | $[20k;50k[$ | $[50k;100k[$ | Total |\n|---|---:|---:|---:|---:|\n| A | 413 | 298 | 288 | 999 |\n| B | 227 | 193 | 170 | 590 |\n| C | 167 | 132 | 112 | 411 |\n| **Total** | **807** | **623** | **570** | **2000** |\n\n**Étape 1 — Hypothèses**\n\n$H_0$ : indépendance entre le quartier et la tranche de revenu. $H_1$ : dépendance.\n\n**Étape 2 — Effectifs théoriques** $E_{ij}=n_{i\\cdot}n_{\\cdot j}/2000$\n\n| | $[10k;20k[$ | $[20k;50k[$ | $[50k;100k[$ |\n|---|---:|---:|---:|\n| A | $999\\times807/2000=403{,}05$ | $999\\times623/2000=311{,}45$ | $999\\times570/2000=284{,}72$ |\n| B | $590\\times807/2000=238{,}07$ | $590\\times623/2000=183{,}79$ | $590\\times570/2000=168{,}15$ |\n| C | $411\\times807/2000=165{,}84$ | $411\\times623/2000=128{,}03$ | $411\\times570/2000=117{,}14$ |\n\nTous les $E_{ij}>5$ (min : 117,14) — condition de Cochran largement satisfaite.\n\n**Étape 3 — Statistique**\n\n$$\n\\chi^2_{obs}\n=\\frac{(413-403{,}05)^2}{403{,}05}\n+\\frac{(298-311{,}45)^2}{311{,}45}\n+\\frac{(288-284{,}72)^2}{284{,}72}\n+\\frac{(227-238{,}07)^2}{238{,}07}\n+\\frac{(193-183{,}79)^2}{183{,}79}\n+\\frac{(170-168{,}15)^2}{168{,}15}\n+\\frac{(167-165{,}84)^2}{165{,}84}\n+\\frac{(132-128{,}03)^2}{128{,}03}\n+\\frac{(112-117{,}14)^2}{117{,}14}\n$$\n$$\n= 0{,}246+0{,}585+0{,}038+0{,}514+0{,}460+0{,}020+0{,}008+0{,}123+0{,}226\n= 2{,}22.\n$$\n\n**Étape 4 — Degrés de liberté et valeur critique**\n\n$\\nu=(3-1)(3-1)=4$. Au seuil 5 % : $\\chi^2_{0{,}95;\\,4}=9{,}488$.\n\n**Étape 5 — Décision et conclusion**\n\n$\\chi^2_{obs}=2{,}22 < 9{,}488$ : on **ne rejette pas $H_0$** au seuil 5 %.\n\nLes données sont compatibles avec l'hypothèse d'indépendance entre le quartier de résidence et la tranche de revenu. Les écarts observés entre les effectifs observés et théoriques peuvent s'expliquer par les fluctuations d'échantillonnage.\n:::\n\n::: {.callout-caution}\n## Exercice 1\n\nCent fruits sont triés selon :\n- leur poids (en grammes),\n- leur qualité (accepté/refusé).\n\n| Poids (g) | Accepté | Refusé |\n|---|---:|---:|\n| $[200;240[$ | 8 | 23 |\n| $[240;280[$ | 7 | 45 |\n| $[280;360[$ | 4 | 13 |\n\n1. Identifier les caractères étudiés et leur type.\n2. Déterminer la distribution marginale de la variable « poids » et le poids médian.\n3. Déterminer la proportion de fruits dans la classe $[240;280[$ pour chaque qualite.\n   Les variables « poids » et « qualité » semblent-elles indépendantes ?\n4. Tester l'indépendance de « qualité » et \"poids\" au risque $\\alpha=5\\%$ (test du khi-deux).\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution — Exercice 1\n\n**1. Caractères et types**\n\n- *Poids* : variable quantitative continue, regroupée en classes.\n- *Qualité* : variable qualitative nominale binaire (accepté / refusé).\n\n**2. Distribution marginale du poids et médiane**\n\nTotaux lignes et colonnes :\n\n| Poids (g) | Accepté | Refusé | Total | $f_{i\\cdot}$ | $F_{i\\cdot}$ |\n|---|---:|---:|---:|---:|---:|\n| $[200;240[$ | 8 | 23 | 31 | 0,31 | 0,31 |\n| $[240;280[$ | 7 | 45 | 52 | 0,52 | 0,83 |\n| $[280;360[$ | 4 | 13 | 17 | 0,17 | 1,00 |\n| **Total** | **19** | **81** | **100** | | |\n\nLa fréquence cumulée dépasse 0,5 dans la classe $[240;280[$. La médiane vaut :\n$$\nM_e = 240 + \\frac{0{,}50 - 0{,}31}{0{,}52}\\times 40\n= 240 + \\frac{0{,}19}{0{,}52}\\times 40\n\\approx 254{,}6\\text{ g}.\n$$\n\n**3. Distributions conditionnelles et indépendance visuelle**\n\nLa proportion de fruits dans $[240;280[$ pour chaque qualité :\n\n- Acceptés : $\\dfrac{7}{19} \\approx 0{,}368$.\n- Refusés : $\\dfrac{45}{81} \\approx 0{,}556$.\n\nSous indépendance, on attendrait la même proportion que dans la marginale ($52/100 = 0{,}52$) pour les deux qualités. Les valeurs $0{,}368$ et $0{,}556$ s'en écartent sensiblement, ce qui suggère une dépendance entre poids et qualité.\n\n**4. Test du khi-deux**\n\n*Hypothèses :* $H_0$ : indépendance entre poids et qualité ; $H_1$ : dépendance.\n\n*Effectifs théoriques* $E_{ij} = n_{i\\cdot}n_{\\cdot j}/100$ :\n\n| Poids | Accepté | Refusé |\n|---|---:|---:|\n| $[200;240[$ | $31\\times19/100 = 5{,}89$ | $31\\times81/100 = 25{,}11$ |\n| $[240;280[$ | $52\\times19/100 = 9{,}88$ | $52\\times81/100 = 42{,}12$ |\n| $[280;360[$ | $17\\times19/100 = 3{,}23$ | $17\\times81/100 = 13{,}77$ |\n\n*Condition de Cochran :* $E_{31}=3{,}23<5$ (une cellule sur six). Le test est à utiliser avec prudence ; on peut regrouper $[200;240[$ et $[280;360[$ si l'on veut strictement satisfaire la règle. On procède ici avec les données telles quelles.\n\n*Statistique :*\n$$\n\\chi^2_{obs}\n= \\frac{(8-5{,}89)^2}{5{,}89}\n+ \\frac{(23-25{,}11)^2}{25{,}11}\n+ \\frac{(7-9{,}88)^2}{9{,}88}\n+ \\frac{(45-42{,}12)^2}{42{,}12}\n+ \\frac{(4-3{,}23)^2}{3{,}23}\n+ \\frac{(13-13{,}77)^2}{13{,}77}\n\\approx 0{,}756+0{,}177+0{,}839+0{,}197+0{,}184+0{,}043\n= 2{,}20.\n$$\n\n*Degrés de liberté :* $\\nu=(3-1)(2-1)=2$.\n\n*Valeur critique :* $\\chi^2_{0{,}95;\\,2}\\approx 5{,}991$.\n\n*Décision :* $2{,}20 < 5{,}991$, on **ne rejette pas** $H_0$ au seuil 5 %.\n\n*Conclusion :* Les données ne fournissent pas de preuve significative d'une dépendance entre le poids et la qualité des fruits.\n:::\n\n::: {.callout-caution}\n## Exercice 2\n\nLe tableau suivant donne la distribution conjointe (fréquences) du temps de\ntrajet domicile-travail et du mode de transport :\n\n| Temps (h) | $[0;0{,}5[$ | $[0{,}5;1[$ | $[1;2[$ |\n|---|---:|---:|---:|\n| Collectif | 0,05 | 0,09 | 0,14 |\n| Individuel | 0,25 | 0,24 | 0,23 |\n\n1. Déterminer le temps moyen pour chacun des deux modes de transport.\n2. En supposant un échantillon de 1000 personnes, tester l'indépendance entre\n   mode de transport et classe de temps au risque $\\alpha=5\\%$.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution — Exercice 2\n\n**1. Temps moyen par mode de transport**\n\nCentres de classes : $c_1=0{,}25$ h, $c_2=0{,}75$ h, $c_3=1{,}5$ h.\n\nMarginales (somme sur les colonnes de chaque ligne) :\n\n- Collectif : $f_{\\text{col}\\cdot} = 0{,}05+0{,}09+0{,}14 = 0{,}28$.\n- Individuel : $f_{\\text{ind}\\cdot} = 0{,}25+0{,}24+0{,}23 = 0{,}72$.\n\nFréquences conditionnelles pour le transport *collectif* (on divise chaque cellule par 0,28) :\n\n$$\nf_{[0;0{,}5[\\mid\\text{col}}} = \\frac{0{,}05}{0{,}28}\\approx 0{,}179,\\quad\nf_{[0{,}5;1[\\mid\\text{col}}} = \\frac{0{,}09}{0{,}28}\\approx 0{,}321,\\quad\nf_{[1;2[\\mid\\text{col}}} = \\frac{0{,}14}{0{,}28} = 0{,}500.\n$$\n\n$$\n\\bar t_{\\text{col}}\n= 0{,}25\\times 0{,}179 + 0{,}75\\times 0{,}321 + 1{,}5\\times 0{,}500\n= \\frac{0{,}25\\times 0{,}05 + 0{,}75\\times 0{,}09 + 1{,}5\\times 0{,}14}{0{,}28}\n= \\frac{0{,}0625+0{,}0675+0{,}21}{0{,}28}\n= \\frac{0{,}29}{0{,}28}\n\\approx 1{,}036\\text{ h}.\n$$\n\nFréquences conditionnelles pour le transport *individuel* (on divise par 0,72) :\n\n$$\n\\bar t_{\\text{ind}}\n= \\frac{0{,}25\\times 0{,}25 + 0{,}75\\times 0{,}24 + 1{,}5\\times 0{,}23}{0{,}72}\n= \\frac{0{,}0625+0{,}18+0{,}345}{0{,}72}\n= \\frac{0{,}5875}{0{,}72}\n\\approx 0{,}816\\text{ h}.\n$$\n\nLes usagers des transports collectifs ont en moyenne un trajet **26 % plus long** que ceux en transport individuel.\n\n**2. Test du khi-deux (n = 1000)**\n\n*Hypothèses :* $H_0$ : indépendance entre mode et classe de temps ; $H_1$ : dépendance.\n\n*Tableau d'effectifs observés* (fréquences $\\times$ 1000) :\n\n| | $[0;0{,}5[$ | $[0{,}5;1[$ | $[1;2[$ | Total |\n|---|---:|---:|---:|---:|\n| Collectif | 50 | 90 | 140 | 280 |\n| Individuel | 250 | 240 | 230 | 720 |\n| **Total** | **300** | **330** | **370** | **1000** |\n\n*Effectifs théoriques* $E_{ij}=n_{i\\cdot}n_{\\cdot j}/1000$ :\n\n| | $[0;0{,}5[$ | $[0{,}5;1[$ | $[1;2[$ |\n|---|---:|---:|---:|\n| Collectif | 84 | 92,4 | 103,6 |\n| Individuel | 216 | 237,6 | 266,4 |\n\nTous les $E_{ij}\\ge 5$ : condition de Cochran satisfaite.\n\n*Statistique :*\n$$\n\\chi^2_{obs}\n=\\frac{(50-84)^2}{84}+\\frac{(90-92{,}4)^2}{92{,}4}+\\frac{(140-103{,}6)^2}{103{,}6}\n+\\frac{(250-216)^2}{216}+\\frac{(240-237{,}6)^2}{237{,}6}+\\frac{(230-266{,}4)^2}{266{,}4}\n$$\n$$\n\\approx 13{,}76+0{,}06+12{,}79+5{,}35+0{,}02+4{,}97 = 36{,}95.\n$$\n\n*Degrés de liberté :* $\\nu=(2-1)(3-1)=2$.\n\n*Valeur critique :* $\\chi^2_{0{,}95;\\,2}\\approx 5{,}991$.\n\n*Décision :* $36{,}95 \\gg 5{,}991$, on **rejette** $H_0$ au seuil 5 %.\n\n*Conclusion :* Il existe une dépendance significative entre le mode de transport et la classe de temps de trajet. Les usagers du collectif tendent à avoir des trajets plus longs que ceux en transport individuel.\n:::\n\n::: {.callout-caution}\n## Exercice 3\n\nVoici les résultats d'une enquête sur les intentions de vote selon la classe\nd'âge :\n\n| Liste / Âge | $[18;35[$ | $[35;50[$ | $[50;80[$ |\n|---|---:|---:|---:|\n| Vers l'avenir | 110 | 113 | 145 |\n| Pour la démocratie | 127 | 120 | 220 |\n| En avant | 57 | 41 | 67 |\n\n1. Déterminer la proportion de personnes entre 18 et 35 ans pour chacune des\n   listes. Commenter.\n2. Les variables « intentions de vote » et « âge » sont-elles indépendantes ?\n3. Réaliser un test du khi-deux d'indépendance au risque $\\alpha=5\\%$.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Solution — Exercice 3\n\n**Totaux du tableau**\n\n| Liste / Âge | $[18;35[$ | $[35;50[$ | $[50;80[$ | Total |\n|---|---:|---:|---:|---:|\n| Vers l'avenir | 110 | 113 | 145 | **368** |\n| Pour la démocratie | 127 | 120 | 220 | **467** |\n| En avant | 57 | 41 | 67 | **165** |\n| **Total** | **294** | **274** | **432** | **1000** |\n\n**1. Proportion de 18–35 ans par liste**\n\n$$\nf_{[18;35[\\mid\\text{Avenir}}} = \\frac{110}{368}\\approx 0{,}299,\\quad\nf_{[18;35[\\mid\\text{Démocratie}}} = \\frac{127}{467}\\approx 0{,}272,\\quad\nf_{[18;35[\\mid\\text{En avant}}} = \\frac{57}{165}\\approx 0{,}345.\n$$\n\nLa proportion marginale des 18–35 ans est $294/1000=0{,}294$. Les trois proportions conditionnelles s'en approchent mais présentent des écarts notables (de 0,272 à 0,345), ce qui laisse présager une légère dépendance entre l'intention de vote et la classe d'âge.\n\n**2. Indépendance visuelle**\n\nSous indépendance, on attendrait la même distribution d'âge dans chaque liste (proportions $0{,}294$, $0{,}274$, $0{,}432$). Les profils conditionnels des trois listes s'en écartent modérément, sans rupture flagrante. L'indépendance est plausible mais doit être confirmée par le test.\n\n**3. Test du khi-deux**\n\n*Hypothèses :* $H_0$ : indépendance entre intention de vote et âge ; $H_1$ : dépendance.\n\n*Effectifs théoriques* $E_{ij}=n_{i\\cdot}n_{\\cdot j}/1000$ :\n\n| | $[18;35[$ | $[35;50[$ | $[50;80[$ |\n|---|---:|---:|---:|\n| Vers l'avenir | $368\\times294/1000=108{,}19$ | $368\\times274/1000=100{,}83$ | $368\\times432/1000=158{,}98$ |\n| Pour la démocratie | $467\\times294/1000=137{,}30$ | $467\\times274/1000=127{,}96$ | $467\\times432/1000=201{,}74$ |\n| En avant | $165\\times294/1000=48{,}51$ | $165\\times274/1000=45{,}21$ | $165\\times432/1000=71{,}28$ |\n\nTous les $E_{ij}\\ge 5$ : condition de Cochran satisfaite.\n\n*Statistique :*\n$$\n\\chi^2_{obs}\n=\\frac{(110-108{,}19)^2}{108{,}19}\n+\\frac{(113-100{,}83)^2}{100{,}83}\n+\\frac{(145-158{,}98)^2}{158{,}98}\n+\\frac{(127-137{,}30)^2}{137{,}30}\n+\\frac{(120-127{,}96)^2}{127{,}96}\n+\\frac{(220-201{,}74)^2}{201{,}74}\n+\\frac{(57-48{,}51)^2}{48{,}51}\n+\\frac{(41-45{,}21)^2}{45{,}21}\n+\\frac{(67-71{,}28)^2}{71{,}28}\n$$\n$$\n\\approx 0{,}030+1{,}468+1{,}229+0{,}772+0{,}495+1{,}652+1{,}486+0{,}392+0{,}257\n= 7{,}78.\n$$\n\n*Degrés de liberté :* $\\nu=(3-1)(3-1)=4$.\n\n*Valeur critique :* $\\chi^2_{0{,}95;\\,4}\\approx 9{,}488$.\n\n*Décision :* $7{,}78 < 9{,}488$, on **ne rejette pas** $H_0$ au seuil 5 %.\n\n*Conclusion :* Au seuil de 5 %, les données ne permettent pas de conclure à une dépendance significative entre l'intention de vote et la classe d'âge. Les différences observées dans les profils sont compatibles avec les fluctuations d'échantillonnage sous l'hypothèse d'indépendance.\n:::\n\n---\n\n## Lecture et interprétation des résultats\n\nObtenir une valeur de $\\chi^2_{obs}$ et une décision (rejet ou non de $H_0$) n'est que le début de l'analyse. Une **bonne interprétation statistique** requiert de contextualiser la décision : un test significatif indique une dépendance, mais pas son intensité ni sa nature. Il faut ensuite examiner quelles cellules contribuent le plus à l'écart global et formuler une conclusion dans le langage du problème étudié.\n\n::: {.callout-important}\n## Bonnes pratiques d'analyse\n\n1. Toujours commenter **l'ampleur** des écarts, pas seulement la décision binaire du test.\n2. Examiner les distributions conditionnelles pour identifier les associations les plus marquantes.\n3. Vérifier la qualité du tableau (effectifs suffisants, classes pertinentes).\n4. Distinguer « absence de preuve de dépendance » et « preuve d'indépendance ».\n5. Rappeler que le test du $\\chi^2$ est **sensible à la taille de l'échantillon** : avec un $n$ très grand, de très petits écarts pratiquement négligeables peuvent devenir statistiquement significatifs.\n:::\n\n### Résidus standardisés\n\nPour identifier quelles cellules contribuent le plus à la valeur de $\\chi^2_{obs}$, on calcule les **résidus standardisés** :\n$$\nR_{ij}=\\frac{O_{ij}-E_{ij}}{\\sqrt{E_{ij}}},\n$$\nqui vérifient $\\chi^2_{obs}=\\sum_{i,j}R_{ij}^2$. Les cellules avec $|R_{ij}|>2$ contribuent le plus à l'écart et méritent une attention particulière dans l'interprétation. Un résidu positif signifie que cette combinaison de modalités est **sur-représentée** par rapport à l'indépendance ; un résidu négatif signifie qu'elle est **sous-représentée**.\n\n### Limites du test\n\n- Le test du $\\chi^2$ **ne quantifie pas l'intensité** de l'association. Pour cela, on peut utiliser le coefficient de contingence $C=\\sqrt{\\chi^2/(n+\\chi^2)}$ ou le $V$ de Cramér $V=\\sqrt{\\chi^2/(n\\cdot\\min(p-1,q-1))}$, qui sont normalisés entre 0 et 1.\n- Il ne s'applique qu'à des **données de comptage** dans un tableau de contingence (et non à des moyennes ou des proportions issues de mesures répétées sur les mêmes individus).\n- Il est **non directionnel** : il détecte l'existence d'une association mais n'en précise pas la direction ni la forme.\n\n",
    "supporting": [
      "bivariate_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}