---
title: PyTorch
draft: true
---

## What is it PyTorch

[PyTorch](https://pytorch.org/) is Facebook AI Research Lab’s answer to [[python.tensorflow]]. It is an open source, general-purpose library for machine learning and data science, specifically deep learning.

Background: Facebook released PyTorch in 2016 — a year after TensorFlow — and it quickly became popular with academics and other researchers who were interested in rapid prototyping. This was due to its streamlined front end and the fact that its default mode executes operations immediately (as opposed to adding them to a graph for later processing, as did TensorFlow).

Features: PyTorch has many features that are analogous those in TensorFlow. Indeed, in the years since they launched, each library has been updated to include the features that users like best about the other.

PyTorch has its own libraries for pre-trained models. The [PyTorch Hub](https://pytorch.org/hub/) is aimed at academic users who want to experiment with the model design, and the [Ecosystem Tools](https://pytorch.org/ecosystem/) contains pre-trained models.
PyTorch is memory-efficient and accommodates training multiple models in parallel.
It supports a variety of hardware types.
Best for: Rapid prototyping of deep learning models. Pytorch code runs quickly and efficiently.

Downsides: Some users report that PyTorch struggles with larger projects, big datasets, and complex workflows. Developers who build AI products to be deployed at scale may prefer TensorFlow.

Best place to learn: [PyTorch tutorials](https://pytorch.org/tutorials/) from PyTorch.org.
