---
title: MS02-001-G - Data Description Syllabus
---

## Teacher:

Guillaume Gilles (guillaume.gilles@essca.eu)

## Course Description

## Course Learning Outcomes, Objectives

## Course Calendar

| Date | Topic                                                                                          |       Textbook's Chapters        |
| :--: | ---------------------------------------------------------------------------------------------- | :------------------------------: |
|  #1  | Excel                                                                                          |                                  |
|  #2  | Excel                                                                                          |                                  |
|  #3  | Excel                                                                                          |                                  |
|  #4  | Représentation et synthese des données                                                         |                                  |
|  #5  | Représentation graphique de données                                                            |                                  |
|  #6  | TP 'application via Excel                                                                      |                                  |
|  #7  | Calcul des valeurs assocees à des pourcentages (quartiles, déciles, etc.) + boîtes à moustache |                                  |
|  #8  | TP 'application via Excel                                                                      |                                  |
|  #9  | Calcul des indicateurs de position centrale (movenne et le mode)                               | 3.2 Measures of Central Tendency |
| #10  | Calcul des indicateurs de dispersion                                                           |                                  |
| #11  | Calcul des indicateurs d'asymétrie                                                             |                                  |
| #12  | TP 'application via Excel                                                                      |                                  |
| #13  | Calcul bivarié                                                                                 |                                  |
| #14  | TP 'application via Excel                                                                      |                                  |
| #15  | TP de révision                                                                                 |                                  |

## Recommended Textbook

- [Applied Statistics and Multivariate Data Analysis](assets/applied-statistics-and-multivariate-data-analysis.pdf)

## Course Grades:

1. MCQ Exam: 35%
2. Final Exam: 65%

## Prerequisites

None

