---
title: MS04-001-G
---

The syllabus can be found [here](decision-making-statistics-syllabus.qmd)

- [ ] Ajouter un emoji entre chaque chapitre pour délimiter visuellement la fin d'une sécance 🏁
- [ ] Embedding khan academy video at the end of each section

## Sets and Combinatorial Analysis

- [wikipedia page](https://en.wikipedia.org/wiki/Set_(mathematics)#cite_ref-Cantor_1-0)
- [Basic set operations](https://www.khanacademy.org/math/statistics-probability/probability-library/basic-set-ops/v/intersection-and-union-of-sets)
- [Unit 8: Counting, permutations, and combinations](https://www.khanacademy.org/math/statistics-probability/counting-permutations-and-combinations)
- [Venn Diagram](https://r-graph-gallery.com/venn-diagram.html)

### Definition

A set is the mathematical model for a collection of different and distinct **things** / **objects** ; a set contains elements or members, which can be mathematical objects of any kind: numbers, symbols, points in space, lines, other geometrical shapes, variables, or even other sets. The set with no elements is the empty set; a set with a single element is a singleton. A set may have a finite number of elements or be an infinite set.

Definitions : 
A set 𝐸 is a collection of objects, called its elements, considered **without order** or **possible repetition** (parce que ce sont des objets). 
If " 𝑥 is an element of the set 𝐸 ", then one can say that "𝑥 belongs to 𝐸 " and we denote 𝑥 ∈ 𝐸 
A set without element is called empty set: notation: ∅ 
A single-element set is called a singleton 
A two-element set, is called a pair 
A subset is a part of the set 

### How to represent a set

Representation of a set :
By extension: give an exhaustive list of all its elements. 
By understanding: give a characteristic property of its elements.
For example : 
𝐴 = {𝑥 ∈ℕ ┤|  x is an even number}  by extension : 𝐴 = {0, 2, 4, 6, 8,…}
𝐵 = {𝑥 ∈ℤ | −2 ≤ 𝑥 ≤ 5}   by extension : 𝐵 = {−2,−1, 0, 1, 2, 3, 4, 5}

### Usual sets in mathematics

Usual sets in mathematics :
ℕ" = {0, 1, 2, 3, 4, . . .}  "the set of nonnegative integers
ℤ" = {..., −2, −1, 0, 1, 2, ...}"  the set of integers 
ℚ={ 𝑎/𝑏, 𝑎∈ℤ, 𝑏∈ℤ, and 𝑏≠0} the set of rational numbers (the fractions)
ℝ "= ]−∞, +∞[ " the set of real numbers
ℝ "\ "{𝑎} the set of all the real numbers in ℝ except 𝑎
ℝ^+ "= [0, +∞["  the set of positif real numbers
ℝ^− "= ]−∞, 0]" the set of negatif real numbers 

### Operations on sets

Operations on Sets : 

#### Inclusion : 𝐴 ⊂ 𝐵 : 
∀ 𝑥∈𝐴 ⇒ 𝑥∈𝐵 

#### Equality  : 𝐴 = 𝐵 
∀ 𝑥∈𝐴 ⟺𝑥∈𝐵

Note that 𝐴 ⊆ 𝐵 implies  " 𝐴 is included in 𝐵 or equal to 𝐵 ". 

Recall that :	   𝐴=𝐵 ⟺ 𝐴⊆𝐵  and  𝐵⊆𝐴. 

#### Intersection : 𝐴 ∩ 𝐵
∀ 𝑥 ∈ 𝐴 ∩ 𝐵⟺𝑥 ∈ 𝐴  and  𝑥 ∈ 𝐵. 

Recall that :
if 𝐴∩𝐵=∅, then one can say that  𝐴 and 𝐵 are disjoint 
𝐴∩𝐵 = 𝐵∩𝐴
𝐴∩∅ = ∅
𝐴∩(𝐵∩𝐶) = (𝐴∩𝐵)∩𝐶

#### Union : 𝐴∪𝐵
∀ 𝑥 ∈𝐴∪𝐵⟺𝑥 ∈ 𝐴   or  𝑥 ∈ 𝐵. 

	Recall that :
𝐴⊆(𝐴∪𝐵),𝐵⊆(𝐴∪𝐵),and 𝐴∩𝐵⊆(𝐴∪𝐵) 
𝐴∪𝐵=𝐵∪𝐴
𝐴∪∅=𝐴
𝐴∪(𝐵∪𝐶)=(𝐴∪𝐵)∪𝐶
𝐴∩(𝐵∪𝐶)=(𝐴∩𝐵)∪(𝐴∩𝐶)

#### Complementarity : Let 𝐴, 𝐵 and 𝐶 be three sets, such that 𝐴 ⊂ 𝐵 and  𝐶⊂ 𝐵. The complement of 𝐴 in 𝐵 is the set of elements of 𝐵 not belonging to 𝐴.
	Notation :  𝐴 ̅  (or 𝐴^𝑐, or 𝐵∖𝐴). 

Recall that :
A ∩ 𝐴 ̅ = ∅
A ∪ 𝐴 ̅ = B
((𝐴 ̅)) ̅ = A 
((𝐴∩𝐶)) ̅  = 𝐴 ̅ ∪ 𝐶 ̅  and  ((𝐴 ∪ 𝐶) ) ̅ = 𝐴 ̅  ∩ 𝐶 ̅

## Calculation of probabilities

- [Maîtrisez les bases des probabilités](https://openclassrooms.com/fr/courses/4525296-maitrisez-les-bases-des-probabilites)
