<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistiques descriptives à deux variables – Guillaume Gilles</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../teaching/statistics-probability/joint-continuous-random-variables.html" rel="next">
<link href="../../teaching/statistics-probability/normal-distribution.html" rel="prev">
<link href="../../assets/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-acebb5f24679ac2f633996cbf56b9a25.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Statistiques descriptives à deux variables – Guillaume Gilles">
<meta property="og:description" content="Ce chapitre prolonge la statistique descriptive au cas de deux caractères observés simultanément sur une même population. On introduit la distribution conjointe d’un couple de variables via les tableaux de contingence, puis les distributions marginales et conditionnelles, indispensables pour décrire les relations entre variables. Le chapitre formalise ensuite la notion d’indépendance et la caractérisation par factorisation des fréquences. Enfin, il présente le test du khi-deux d’indépendance (conditions, construction des effectifs théoriques, statistique, degrés de liberté, règle de décision) avec une méthodologie complète d’interprétation.">
<meta property="og:image" content="https://ggilles.dev/teaching/statistics-probability/assets/og-image.png">
<meta property="og:site_name" content="Guillaume Gilles">
<meta name="twitter:title" content="Statistiques descriptives à deux variables – Guillaume Gilles">
<meta name="twitter:description" content="Ce chapitre prolonge la statistique descriptive au cas de deux caractères observés simultanément sur une même population. On introduit la distribution conjointe d’un couple de variables via les tableaux de contingence, puis les distributions marginales et conditionnelles, indispensables pour décrire les relations entre variables. Le chapitre formalise ensuite la notion d’indépendance et la caractérisation par factorisation des fréquences. Enfin, il présente le test du khi-deux d’indépendance (conditions, construction des effectifs théoriques, statistique, degrés de liberté, règle de décision) avec une méthodologie complète d’interprétation.">
<meta name="twitter:image" content="https://ggilles.dev/teaching/statistics-probability/assets/og-image.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/favicon.png" alt="" class="navbar-logo light-content">
    <img src="../../assets/favicon.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Guillaume Gilles</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Recherche"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Basculer la navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Basculer en mode lecteur">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../teaching/statistics-probability/bivariate.html">Deux variables</a></li><li class="breadcrumb-item"><a href="../../teaching/statistics-probability/bivariate.html">Statistiques descriptives à deux variables</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistiques et Probabilités</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notations mathématiques en statistiques</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Une variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/univariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistiques descriptives à une variable</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rappels de probabilités discrètes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/density-function.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lois à densité</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/normal-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Loi normale et applications</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Deux variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/bivariate.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Statistiques descriptives à deux variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/joint-continuous-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Couples de variables à densité</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Convergence et théorèmes limites</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/convergence-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convergence de variables aléatoires</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistique inférentielle</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/sampling-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distribution d’echantillonnage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/point-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Estimation ponctuelle et par intervalle de confiance</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Examens</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/exam-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Examen — Statistiques et Probabilités</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/exam-1-correction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correction — Examen · Statistiques et Probabilités</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/exam-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Examen (Sujet 2) — Statistiques et Probabilités</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/exam-2-correction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correction — Examen (Sujet 2) · Statistiques et Probabilités</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Ressources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tables statistiques</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossaire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../teaching/statistics-probability/leaderboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Leaderboard</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sur cette page</h2>
   
  <ul>
  <li><a href="#distribution-conjointe" id="toc-distribution-conjointe" class="nav-link active" data-scroll-target="#distribution-conjointe">Distribution conjointe</a></li>
  <li><a href="#distributions-marginales" id="toc-distributions-marginales" class="nav-link" data-scroll-target="#distributions-marginales">Distributions marginales</a></li>
  <li><a href="#distributions-conditionnelles" id="toc-distributions-conditionnelles" class="nav-link" data-scroll-target="#distributions-conditionnelles">Distributions conditionnelles</a></li>
  <li><a href="#indépendance-de-deux-variables" id="toc-indépendance-de-deux-variables" class="nav-link" data-scroll-target="#indépendance-de-deux-variables">Indépendance de deux variables</a></li>
  <li><a href="#test-du-khi-deux-dindépendance" id="toc-test-du-khi-deux-dindépendance" class="nav-link" data-scroll-target="#test-du-khi-deux-dindépendance">Test du khi-deux d’indépendance</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">Motivation</a></li>
  <li><a href="#effectifs-théoriques" id="toc-effectifs-théoriques" class="nav-link" data-scroll-target="#effectifs-théoriques">Effectifs théoriques</a></li>
  <li><a href="#statistique-de-test" id="toc-statistique-de-test" class="nav-link" data-scroll-target="#statistique-de-test">Statistique de test</a></li>
  <li><a href="#loi-de-la-statistique-sous-h_0" id="toc-loi-de-la-statistique-sous-h_0" class="nav-link" data-scroll-target="#loi-de-la-statistique-sous-h_0">Loi de la statistique sous <span class="math inline">\(H_0\)</span></a></li>
  <li><a href="#règle-de-décision" id="toc-règle-de-décision" class="nav-link" data-scroll-target="#règle-de-décision">Règle de décision</a></li>
  <li><a href="#valeurs-critiques-usuelles" id="toc-valeurs-critiques-usuelles" class="nav-link" data-scroll-target="#valeurs-critiques-usuelles">Valeurs critiques usuelles</a></li>
  <li><a href="#méthodologie-complète" id="toc-méthodologie-complète" class="nav-link" data-scroll-target="#méthodologie-complète">Méthodologie complète</a></li>
  </ul></li>
  <li><a href="#lecture-et-interprétation-des-résultats" id="toc-lecture-et-interprétation-des-résultats" class="nav-link" data-scroll-target="#lecture-et-interprétation-des-résultats">Lecture et interprétation des résultats</a>
  <ul class="collapse">
  <li><a href="#résidus-standardisés" id="toc-résidus-standardisés" class="nav-link" data-scroll-target="#résidus-standardisés">Résidus standardisés</a></li>
  <li><a href="#limites-du-test" id="toc-limites-du-test" class="nav-link" data-scroll-target="#limites-du-test">Limites du test</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../teaching/statistics-probability/bivariate.html">Deux variables</a></li><li class="breadcrumb-item"><a href="../../teaching/statistics-probability/bivariate.html">Statistiques descriptives à deux variables</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Statistiques descriptives à deux variables</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Date de publication</div>
    <div class="quarto-title-meta-contents">
      <p class="date">18 février 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modifié</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">22 mars 2026</p>
    </div>
  </div>
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Résumé</div>
    <p>Ce chapitre prolonge la statistique descriptive au cas de deux caractères observés simultanément sur une même population. On introduit la <strong>distribution conjointe</strong> d’un couple de variables via les tableaux de contingence, puis les <strong>distributions marginales</strong> et <strong>conditionnelles</strong>, indispensables pour décrire les relations entre variables. Le chapitre formalise ensuite la notion d’<strong>indépendance</strong> et la caractérisation par factorisation des fréquences. Enfin, il présente le <strong>test du khi-deux d’indépendance</strong> (conditions, construction des effectifs théoriques, statistique, degrés de liberté, règle de décision) avec une méthodologie complète d’interprétation.</p>
  </div>
</div>


</header>


<p><a href="index.html">📍 Retour à la carte du cours</a> &gt; Dans tout ce chapitre, on étudie deux variables observées sur une même population finie de taille <span class="math inline">\(n\)</span>.</p>
<section id="distribution-conjointe" class="level2">
<h2 class="anchored" data-anchor-id="distribution-conjointe">Distribution conjointe</h2>
<p>Lorsqu’on observe <strong>deux variables simultanément</strong> sur chaque individu d’une population, on ne peut pas les étudier séparément sans perdre l’information sur leur relation. La distribution conjointe capture précisément cette information : elle recense le nombre (ou la fréquence) d’individus pour chaque combinaison de modalités des deux variables. Son outil de représentation naturel est le <strong>tableau de contingence</strong>.</p>
<p>Soit <span class="math inline">\(P\)</span> une population et <span class="math inline">\((x,y)\)</span> un couple de variables, c’est-à-dire une application <span class="math display">\[
(x,y):P\to E_x\times E_y,
\qquad
u\mapsto (x(u),y(u)).
\]</span></p>
<p>Les variables peuvent être qualitatives ou quantitatives (discrètes ou regroupées en classes). On parle de <strong>couple statistique</strong> : chaque individu est décrit par <strong>deux</strong> caractères simultanément, ce qui permet d’étudier la relation entre eux.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Définitions
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si <span class="math inline">\(x_1,\dots,x_p\)</span> sont les modalités de <span class="math inline">\(x\)</span> et <span class="math inline">\(y_1,\dots,y_q\)</span> celles de <span class="math inline">\(y\)</span> :</p>
<ul>
<li><span class="math inline">\(n_{ij}\)</span> est l’<strong>effectif conjoint</strong> du couple <span class="math inline">\((x_i,y_j)\)</span> : le nombre d’individus ayant simultanément <span class="math inline">\(x=x_i\)</span> et <span class="math inline">\(y=y_j\)</span>,</li>
<li><span class="math inline">\(f_{ij}=n_{ij}/n\)</span> est la <strong>fréquence conjointe</strong>,</li>
<li>l’ensemble des triplets <span class="math inline">\((x_i,y_j,n_{ij})\)</span> forme la <strong>distribution conjointe</strong>.</li>
</ul>
<p>On a toujours : <span class="math display">\[
\sum_{i=1}^p\sum_{j=1}^q n_{ij}=n,
\qquad
\sum_{i=1}^p\sum_{j=1}^q f_{ij}=1.
\]</span></p>
</div>
</div>
<p>La représentation standard est le <strong>tableau de contingence</strong> : un tableau à double entrée de dimensions <span class="math inline">\(p\times q\)</span> dont la cellule <span class="math inline">\((i,j)\)</span> contient <span class="math inline">\(n_{ij}\)</span> (ou <span class="math inline">\(f_{ij}\)</span>), complété par les totaux marginaux en marge.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exemple 1 - Tableau conjoint et fréquence globale
</div>
</div>
<div class="callout-body-container callout-body">
<p>Une enquête porte sur 2000 habitants. On observe :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Quartier / Revenu annuel</th>
<th style="text-align: right;"><span class="math inline">\([10000,20000[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([20000,50000[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([50000,100000[\)</span></th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">298</td>
<td style="text-align: right;">288</td>
<td style="text-align: right;">?</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">227</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">?</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: right;">167</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">?</td>
</tr>
<tr class="even">
<td>Total</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">2000</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Compléter le tableau.</li>
<li>Calculer la fréquence d’habitants ayant un revenu d’au moins 20 000.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution - Exemple 1 (résultats)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Totaux lignes :
<ul>
<li>A : 999,</li>
<li>B : 590,</li>
<li>C : 411.</li>
</ul></li>
<li>Totaux colonnes :
<ul>
<li><span class="math inline">\([10000,20000[\)</span> : 807,</li>
<li><span class="math inline">\([20000,50000[\)</span> : 623,</li>
<li><span class="math inline">\([50000,100000[\)</span> : 570.</li>
</ul></li>
<li>Fréquence revenu <span class="math inline">\(\ge 20000\)</span> : <span class="math display">\[
\frac{623+570}{2000}=\frac{1193}{2000}=0{,}5965.
\]</span></li>
</ul>
</div>
</div>
</div>
</section>
<section id="distributions-marginales" class="level2">
<h2 class="anchored" data-anchor-id="distributions-marginales">Distributions marginales</h2>
<p>Une fois le tableau de contingence construit, on peut retrouver la distribution de chaque variable <strong>individuellement</strong> en faisant la somme sur l’autre variable. Ces distributions dites <strong>marginales</strong> correspondent aux totaux de lignes et de colonnes du tableau — elles figurent littéralement dans les <strong>marges</strong> du tableau. Elles permettent de calculer les indicateurs habituels — moyenne, médiane, écart-type — pour chaque variable, indépendamment de l’autre.</p>
<p>À partir de la distribution conjointe, on obtient les distributions de chaque variable prise séparément.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Définitions
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Effectif marginal de <span class="math inline">\(x_i\)</span> : <span class="math display">\[n_{i\cdot}=\sum_{j=1}^q n_{ij}, \qquad f_{i\cdot}=\frac{n_{i\cdot}}{n}.\]</span></li>
<li>Effectif marginal de <span class="math inline">\(y_j\)</span> : <span class="math display">\[n_{\cdot j}=\sum_{i=1}^p n_{ij}, \qquad f_{\cdot j}=\frac{n_{\cdot j}}{n}.\]</span></li>
</ul>
<p>Les couples <span class="math inline">\((x_i,n_{i\cdot})\)</span> et <span class="math inline">\((y_j,n_{\cdot j})\)</span> définissent les <strong>distributions marginales</strong> de <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Propriété fondamentale
</div>
</div>
<div class="callout-body-container callout-body">
<p>Les distributions marginales vérifient : <span class="math display">\[
\sum_{i=1}^p n_{i\cdot} = \sum_{j=1}^q n_{\cdot j} = n,
\qquad
\sum_{i=1}^p f_{i\cdot} = \sum_{j=1}^q f_{\cdot j} = 1.
\]</span></p>
<p>On retrouve bien des distributions complètes sur chacune des deux variables.</p>
</div>
</div>
<p>Ces marginales permettent de calculer les indicateurs usuels de chaque variable (moyenne, médiane, écart-type, etc.) si le type de variable le permet. Pour une variable quantitative regroupée en classes, on utilise les <strong>centres de classes</strong> <span class="math inline">\(c_j\)</span> comme valeurs représentatives : <span class="math display">\[
\bar x = \sum_{i=1}^p c_i\, f_{i\cdot}.
\]</span></p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exemple 2 - Exploiter les marginales
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reprendre l’exemple 1.</p>
<ol type="1">
<li>Déterminer les distributions marginales de “Quartier” et de “Revenu annuel”.</li>
<li>Pour « Revenu annuel » (en classes), estimer la moyenne à l’aide des centres de classes.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution - Exemple 2 (idée)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Marginale de “Quartier” : totaux de lignes / 2000.</li>
<li>Marginale de “Revenu annuel” : totaux de colonnes / 2000.</li>
<li>Moyenne approximative du revenu : <span class="math display">\[
\bar y\approx\sum_j c_j f_{\cdot j},
\]</span> où <span class="math inline">\(c_j\)</span> est le centre de la classe <span class="math inline">\(j\)</span>.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="distributions-conditionnelles" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="distributions-conditionnelles">Distributions conditionnelles</h2>
<p>Les distributions marginales décrivent chaque variable dans l’ensemble de la population. Mais que se passe-t-il <strong>au sein d’un sous-groupe</strong> ? La distribution conditionnelle répond à cette question : elle décrit la répartition d’une variable lorsqu’on <strong>fixe la modalité de l’autre</strong>. Comparer les distributions conditionnelles de <span class="math inline">\(y\)</span> pour différentes valeurs de <span class="math inline">\(x\)</span> est le premier outil pour détecter visuellement une association entre les deux variables.</p>
<p>Une ligne (resp. colonne) du tableau de contingence décrit la répartition conditionnelle de <span class="math inline">\(y\)</span> sachant <span class="math inline">\(x=x_i\)</span> (resp. de <span class="math inline">\(x\)</span> sachant <span class="math inline">\(y=y_j\)</span>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Définitions
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Fréquence conditionnelle de <span class="math inline">\(y_j\)</span> sachant <span class="math inline">\(x_i\)</span> : <span class="math display">\[f_{y_j\mid x_i}=\frac{n_{ij}}{n_{i\cdot}}.\]</span></li>
<li>Fréquence conditionnelle de <span class="math inline">\(x_i\)</span> sachant <span class="math inline">\(y_j\)</span> : <span class="math display">\[f_{x_i\mid y_j}=\frac{n_{ij}}{n_{\cdot j}}.\]</span></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Propriétés
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pour chaque <span class="math inline">\(i\)</span> fixé, les fréquences conditionnelles de <span class="math inline">\(y\)</span> sachant <span class="math inline">\(x_i\)</span> forment une distribution complète : <span class="math display">\[
\sum_{j=1}^q f_{y_j\mid x_i} = \frac{1}{n_{i\cdot}}\sum_{j=1}^q n_{ij} = \frac{n_{i\cdot}}{n_{i\cdot}} = 1.
\]</span></p>
<p>On peut donc calculer la <strong>moyenne conditionnelle</strong> de <span class="math inline">\(y\)</span> sachant <span class="math inline">\(x=x_i\)</span> : <span class="math display">\[
\bar y_{|x_i} = \sum_{j=1}^q c_j\, f_{y_j\mid x_i},
\]</span> où <span class="math inline">\(c_j\)</span> est la valeur (ou le centre de classe) de <span class="math inline">\(y_j\)</span>.</p>
</div>
</div>
<p>Les distributions conditionnelles servent à comparer les profils entre sous-populations. Si ces profils sont très différents d’une modalité de <span class="math inline">\(x\)</span> à l’autre, cela suggère une association entre <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span>. Si au contraire ils sont tous semblables à la distribution marginale de <span class="math inline">\(y\)</span>, les deux variables semblent indépendantes.</p>
<div id="cell-fig-bivariate-overview" class="cell page-columns page-full" data-execution_count="1">
<div class="cell-output cell-output-display page-columns page-full">
<div id="fig-bivariate-overview" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-bivariate-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="bivariate_files/figure-html/fig-bivariate-overview-output-1.png" class="quarto-figure quarto-figure-center figure-img column-screen-inset" width="1046" height="417">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bivariate-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution conjointe, marginales et conditionnelles illustrées sur les données de l’exemple 1 (2000 habitants). <strong>Gauche</strong> : fréquences conjointes <span class="math inline">\(f_{ij}\)</span> (intensité de la couleur). <strong>Droite</strong> : distributions conditionnelles du revenu pour chaque quartier — si les barres étaient identiques d’un quartier à l’autre, les variables seraient indépendantes.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exemple 3 - Profil conditionnel
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dans l’exemple 1, déterminer la distribution conditionnelle du revenu sachant que l’on est dans le quartier A. Puis identifier la classe de revenu majoritaire dans ce quartier.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution - Exemple 3 (résultats)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Comme <span class="math inline">\(n_{A\cdot}=999\)</span> : <span class="math display">\[
\left(\frac{413}{999},\frac{298}{999},\frac{288}{999}\right)
\approx (0{,}413,0{,}298,0{,}288).
\]</span> La classe majoritaire est <span class="math inline">\([10000,20000[\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="indépendance-de-deux-variables" class="level2">
<h2 class="anchored" data-anchor-id="indépendance-de-deux-variables">Indépendance de deux variables</h2>
<p>Deux variables sont <strong>indépendantes</strong> si connaître la modalité de l’une n’apporte aucune information sur la distribution de l’autre — autrement dit, si toutes les distributions conditionnelles sont identiques à la distribution marginale. En pratique, cette condition se traduit par une relation de <strong>factorisation</strong> des fréquences conjointes, ce qui permet de la vérifier cellule par cellule dans le tableau de contingence.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Définition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Les variables <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span> sont <strong>indépendantes</strong> si, pour toute modalité <span class="math inline">\(x_i\)</span>, la distribution conditionnelle de <span class="math inline">\(y\)</span> sachant <span class="math inline">\(x_i\)</span> est égale à la distribution marginale de <span class="math inline">\(y\)</span> : <span class="math display">\[
f_{y_j\mid x_i} = f_{\cdot j} \quad \text{pour tout } i,j.
\]</span> Autrement dit, la valeur prise par <span class="math inline">\(x\)</span> ne modifie pas la répartition de <span class="math inline">\(y\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Caractérisation équivalente (admise)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Les propriétés suivantes sont équivalentes :</p>
<ol type="1">
<li><span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span> sont indépendantes.</li>
<li>Pour tout <span class="math inline">\(i,j\)</span>, <span class="math display">\[f_{ij}=f_{i\cdot}f_{\cdot j}.\]</span></li>
<li>Pour tout <span class="math inline">\(i,j\)</span>, <span class="math display">\[n_{ij}=\frac{n_{i\cdot}n_{\cdot j}}{n}.\]</span></li>
</ol>
<p><strong>Pourquoi ?</strong> Si <span class="math inline">\(f_{y_j\mid x_i}=f_{\cdot j}\)</span>, alors : <span class="math display">\[
f_{ij}=\frac{n_{ij}}{n}=\frac{n_{ij}}{n_{i\cdot}}\cdot\frac{n_{i\cdot}}{n}=f_{y_j\mid x_i}\cdot f_{i\cdot}=f_{\cdot j}\cdot f_{i\cdot}.
\]</span> La fréquence conjointe se <strong>factorise</strong> en le produit des deux fréquences marginales. C’est cette propriété que le test du <span class="math inline">\(\chi^2\)</span> va exploiter quantitativement.</p>
</div>
</div>
<p>En pratique, l’indépendance se traduit par des profils de lignes (ou colonnes) identiques les uns aux autres.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exemple 4 - Vérification rapide
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dans un tableau <span class="math inline">\(2\times 2\)</span> avec <span class="math display">\[
\begin{pmatrix}
30 &amp; 20\\
15 &amp; 35
\end{pmatrix},
\quad n=100,
\]</span> vérifier si l’indépendance est satisfaite exactement.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution - Exemple 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Totaux : lignes <span class="math inline">\((50,50)\)</span>, colonnes <span class="math inline">\((45,55)\)</span>. Sous indépendance, la case (1,1) devrait valoir <span class="math inline">\(50\times45/100=22{,}5\)</span> (et non 30). Donc les variables ne sont pas indépendantes.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="test-du-khi-deux-dindépendance" class="level2">
<h2 class="anchored" data-anchor-id="test-du-khi-deux-dindépendance">Test du khi-deux d’indépendance</h2>
<section id="motivation" class="level3">
<h3 class="anchored" data-anchor-id="motivation">Motivation</h3>
<p>L’inspection visuelle des distributions conditionnelles ne suffit pas : les écarts observés peuvent être dus au <strong>hasard de l’échantillonnage</strong>. Même si les variables sont parfaitement indépendantes dans la population, un échantillon produira toujours des fréquences conjointes légèrement différentes du produit des marginales. La question est donc : les écarts observés sont-ils <strong>trop grands</strong> pour être attribués au seul hasard ?</p>
<p>Le test du <span class="math inline">\(\chi^2\)</span> d’indépendance de Pearson fournit une réponse rigoureuse à cette question. L’idée est de :</p>
<ol type="1">
<li>calculer ce que l’on observerait <strong>si l’indépendance était exacte</strong> (effectifs théoriques),</li>
<li>mesurer l’<strong>écart global</strong> entre ces valeurs théoriques et les valeurs réellement observées,</li>
<li>décider si cet écart est significatif en le comparant à une valeur critique issue de la loi <span class="math inline">\(\chi^2\)</span>.</li>
</ol>
<p>On teste :</p>
<ul>
<li><span class="math inline">\(H_0\)</span> : indépendance entre <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span>,</li>
<li><span class="math inline">\(H_1\)</span> : dépendance (association).</li>
</ul>
</section>
<section id="effectifs-théoriques" class="level3">
<h3 class="anchored" data-anchor-id="effectifs-théoriques">Effectifs théoriques</h3>
<p>Sous <span class="math inline">\(H_0\)</span>, si les variables étaient indépendantes, la fréquence conjointe <span class="math inline">\(f_{ij}\)</span> devrait valoir <span class="math inline">\(f_{i\cdot}f_{\cdot j}\)</span> (factorisation). On en déduit l’effectif que l’on devrait observer dans la case <span class="math inline">\((i,j)\)</span> :</p>
<p><span class="math display">\[
E_{ij}=n\,f_{i\cdot}f_{\cdot j}=n\cdot\frac{n_{i\cdot}}{n}\cdot\frac{n_{\cdot j}}{n}=\frac{n_{i\cdot}\,n_{\cdot j}}{n}.
\]</span></p>
<p><strong>Interprétation :</strong> <span class="math inline">\(E_{ij}\)</span> est la part du total <span class="math inline">\(n\)</span> que l’on attribuerait à la case <span class="math inline">\((i,j)\)</span> si les lignes et les colonnes étaient « proportionnelles » les unes aux autres. Les totaux marginaux <span class="math inline">\(n_{i\cdot}\)</span> et <span class="math inline">\(n_{\cdot j}\)</span> sont fixés (ils ne dépendent pas de <span class="math inline">\(H_0\)</span>) ; seule la répartition interne change.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Propriété de conservation des marges
</div>
</div>
<div class="callout-body-container callout-body">
<p>Les effectifs théoriques conservent les mêmes totaux que les effectifs observés : <span class="math display">\[
\sum_{j=1}^q E_{ij}=n_{i\cdot} \quad\text{et}\quad \sum_{i=1}^p E_{ij}=n_{\cdot j}.
\]</span> Les marges du tableau ne sont pas modifiées par l’hypothèse <span class="math inline">\(H_0\)</span> : seule la distribution <em>interne</em> des cellules est affectée.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Règle de Cochran
</div>
</div>
<div class="callout-body-container callout-body">
<p>L’approximation par la loi <span class="math inline">\(\chi^2\)</span> n’est valide que si les effectifs théoriques sont suffisamment grands :</p>
<ul>
<li>au moins <strong>80 %</strong> des <span class="math inline">\(E_{ij}\)</span> sont <span class="math inline">\(\ge 5\)</span>,</li>
<li><strong>aucun</strong> <span class="math inline">\(E_{ij}\)</span> n’est nul ou très proche de zéro.</li>
</ul>
<p>Si cette condition n’est pas satisfaite, il faut <strong>regrouper</strong> des modalités (fusionner des lignes ou colonnes) jusqu’à ce qu’elle le soit. Un tableau <span class="math inline">\(2\times 2\)</span> avec tous les <span class="math inline">\(E_{ij}&lt;5\)</span> nécessite le test exact de Fisher.</p>
</div>
</div>
</section>
<section id="statistique-de-test" class="level3">
<h3 class="anchored" data-anchor-id="statistique-de-test">Statistique de test</h3>
<p>On mesure l’écart global entre les effectifs observés <span class="math inline">\(O_{ij}=n_{ij}\)</span> et les effectifs théoriques <span class="math inline">\(E_{ij}\)</span> par la <strong>statistique de Pearson</strong> :</p>
<p><span class="math display">\[
\chi^2_{obs}=\sum_{i=1}^p\sum_{j=1}^q\frac{(O_{ij}-E_{ij})^2}{E_{ij}}.
\]</span></p>
<p><strong>Décomposition de la formule :</strong></p>
<ul>
<li><span class="math inline">\((O_{ij}-E_{ij})^2\)</span> mesure l’<strong>écart au carré</strong> entre observé et attendu. On élève au carré pour éviter que les écarts positifs et négatifs ne se compensent, et pour pénaliser davantage les grands écarts.</li>
<li>On divise par <span class="math inline">\(E_{ij}\)</span> pour <strong>normaliser</strong> : un écart de 10 est beaucoup plus remarquable dans une cellule attendue à 15 que dans une cellule attendue à 500. La division rend les contributions comparables.</li>
<li>Plus <span class="math inline">\(\chi^2_{obs}\)</span> est <strong>grand</strong>, plus les données s’éloignent de l’hypothèse d’indépendance.</li>
<li>Si l’indépendance était parfaite (<span class="math inline">\(O_{ij}=E_{ij}\)</span> pour tout <span class="math inline">\(i,j\)</span>), on obtiendrait <span class="math inline">\(\chi^2_{obs}=0\)</span>.</li>
</ul>
</section>
<section id="loi-de-la-statistique-sous-h_0" class="level3">
<h3 class="anchored" data-anchor-id="loi-de-la-statistique-sous-h_0">Loi de la statistique sous <span class="math inline">\(H_0\)</span></h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Résultat (admis)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sous <span class="math inline">\(H_0\)</span> et lorsque les effectifs sont suffisamment grands (condition de Cochran), la statistique <span class="math inline">\(\chi^2_{obs}\)</span> suit <strong>approximativement</strong> une loi du khi-deux à <span class="math inline">\(\nu\)</span> degrés de liberté : <span class="math display">\[
\chi^2_{obs} \underset{H_0}{\sim} \chi^2_\nu,
\qquad
\nu=(p-1)(q-1).
\]</span></p>
</div>
</div>
<p><strong>Pourquoi <span class="math inline">\((p-1)(q-1)\)</span> degrés de liberté ?</strong></p>
<p>Le tableau <span class="math inline">\(p\times q\)</span> contient <span class="math inline">\(pq\)</span> cellules, mais les effectifs ne sont pas libres : les totaux marginaux (lignes et colonnes) sont fixés, ce qui impose <span class="math inline">\(p+q-1\)</span> contraintes (les <span class="math inline">\(p\)</span> totaux de lignes et les <span class="math inline">\(q\)</span> totaux de colonnes, moins 1 car la somme des deux est la même, <span class="math inline">\(n\)</span>). Le nombre de cellules « libres » est donc : <span class="math display">\[
pq - (p+q-1) = (p-1)(q-1).
\]</span> On peut remplir librement les <span class="math inline">\((p-1)(q-1)\)</span> premières cellules ; toutes les autres sont alors déterminées par les contraintes sur les marges.</p>
<p><strong>La loi <span class="math inline">\(\chi^2_\nu\)</span> :</strong> c’est une loi continue sur <span class="math inline">\(\mathbb{R}_+\)</span>, asymétrique à droite, dont la densité est nulle en zéro et décroît vers zéro pour les grandes valeurs. Plus <span class="math inline">\(\nu\)</span> est grand, plus la distribution est étalée vers la droite. La valeur critique <span class="math inline">\(\chi^2_{1-\alpha,\nu}\)</span> est le quantile d’ordre <span class="math inline">\(1-\alpha\)</span> de cette loi, tabule en annexe.</p>
<div id="cell-fig-chisq-dist" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-chisq-dist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chisq-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="bivariate_files/figure-html/fig-chisq-dist-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="757" height="370">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisq-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Densité de la loi <span class="math inline">\(\chi^2_\nu\)</span> pour différents degrés de liberté. La zone grisée représente la région de rejet au seuil <span class="math inline">\(\alpha=5\%\)</span> pour <span class="math inline">\(\nu=4\)</span> : on rejette <span class="math inline">\(H_0\)</span> lorsque <span class="math inline">\(\chi^2_{obs}\)</span> tombe dans cette zone.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="règle-de-décision" class="level3">
<h3 class="anchored" data-anchor-id="règle-de-décision">Règle de décision</h3>
<p>Au seuil <span class="math inline">\(\alpha\)</span> (risque de première espèce : probabilité de rejeter <span class="math inline">\(H_0\)</span> à tort) :</p>
<ul>
<li>on lit la valeur critique <span class="math inline">\(\chi^2_{1-\alpha,\nu}\)</span> dans la table (ou on la calcule),</li>
<li>si <span class="math inline">\(\chi^2_{obs}&gt;\chi^2_{1-\alpha,\nu}\)</span>, on <strong>rejette <span class="math inline">\(H_0\)</span></strong> : les données sont incompatibles avec l’hypothèse d’indépendance,</li>
<li>si <span class="math inline">\(\chi^2_{obs}\le\chi^2_{1-\alpha,\nu}\)</span>, on <strong>ne rejette pas <span class="math inline">\(H_0\)</span></strong> : les données sont compatibles avec l’indépendance.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avertissement</span>Vocabulaire important
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Rejeter <span class="math inline">\(H_0\)</span></strong> ne signifie pas prouver <span class="math inline">\(H_1\)</span> avec certitude : cela signifie que les données observées seraient très improbables si <span class="math inline">\(H_0\)</span> était vraie.</li>
<li><strong>Ne pas rejeter <span class="math inline">\(H_0\)</span></strong> ne signifie pas prouver l’indépendance : cela signifie simplement que les données ne fournissent pas assez de preuves contre <span class="math inline">\(H_0\)</span>. L’absence de preuve n’est pas la preuve de l’absence.</li>
<li>Le test du <span class="math inline">\(\chi^2\)</span> détecte l’existence d’une association mais <strong>n’en mesure pas l’intensité</strong>. Un test très significatif sur un grand échantillon peut correspondre à une dépendance très faible en pratique.</li>
</ul>
</div>
</div>
</section>
<section id="valeurs-critiques-usuelles" class="level3">
<h3 class="anchored" data-anchor-id="valeurs-critiques-usuelles">Valeurs critiques usuelles</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\nu\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\alpha=10\%\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\alpha=5\%\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\alpha=1\%\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2,706</td>
<td style="text-align: right;">3,841</td>
<td style="text-align: right;">6,635</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4,605</td>
<td style="text-align: right;">5,991</td>
<td style="text-align: right;">9,210</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">6,251</td>
<td style="text-align: right;">7,815</td>
<td style="text-align: right;">11,345</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">7,779</td>
<td style="text-align: right;">9,488</td>
<td style="text-align: right;">13,277</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">10,645</td>
<td style="text-align: right;">12,592</td>
<td style="text-align: right;">16,812</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">14,684</td>
<td style="text-align: right;">16,919</td>
<td style="text-align: right;">21,666</td>
</tr>
</tbody>
</table>
</section>
<section id="méthodologie-complète" class="level3">
<h3 class="anchored" data-anchor-id="méthodologie-complète">Méthodologie complète</h3>
<p>Pour conduire un test du <span class="math inline">\(\chi^2\)</span> d’indépendance, suivre systématiquement les étapes suivantes :</p>
<ol type="1">
<li><strong>Poser les hypothèses</strong> : <span class="math inline">\(H_0\)</span> (indépendance) et <span class="math inline">\(H_1\)</span> (dépendance).</li>
<li><strong>Construire le tableau</strong> avec les effectifs observés <span class="math inline">\(O_{ij}\)</span> et calculer les totaux marginaux.</li>
<li><strong>Calculer les effectifs théoriques</strong> <span class="math inline">\(E_{ij}=n_{i\cdot}n_{\cdot j}/n\)</span>.</li>
<li><strong>Vérifier Cochran</strong> : au moins 80 % des <span class="math inline">\(E_{ij}\ge 5\)</span> et aucun nul. Sinon, regrouper.</li>
<li><strong>Calculer la statistique</strong> <span class="math inline">\(\chi^2_{obs}=\sum (O_{ij}-E_{ij})^2/E_{ij}\)</span>.</li>
<li><strong>Déterminer les degrés de liberté</strong> <span class="math inline">\(\nu=(p-1)(q-1)\)</span>.</li>
<li><strong>Lire la valeur critique</strong> <span class="math inline">\(\chi^2_{1-\alpha,\nu}\)</span> dans la table.</li>
<li><strong>Conclure</strong> en comparant <span class="math inline">\(\chi^2_{obs}\)</span> à <span class="math inline">\(\chi^2_{1-\alpha,\nu}\)</span>, et reformuler dans le contexte du problème.</li>
</ol>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exemple 5 - Application complète
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reprendre le tableau de l’exemple 1 et tester l’indépendance entre « Quartier » et « Revenu annuel » au seuil <span class="math inline">\(\alpha=5\%\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution - Exemple 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Données (tableau observé)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quartier / Revenu</th>
<th style="text-align: right;"><span class="math inline">\([10k;20k[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([20k;50k[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([50k;100k[\)</span></th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">298</td>
<td style="text-align: right;">288</td>
<td style="text-align: right;">999</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">227</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">590</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: right;">167</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">411</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>807</strong></td>
<td style="text-align: right;"><strong>623</strong></td>
<td style="text-align: right;"><strong>570</strong></td>
<td style="text-align: right;"><strong>2000</strong></td>
</tr>
</tbody>
</table>
<p><strong>Étape 1 — Hypothèses</strong></p>
<p><span class="math inline">\(H_0\)</span> : indépendance entre le quartier et la tranche de revenu. <span class="math inline">\(H_1\)</span> : dépendance.</p>
<p><strong>Étape 2 — Effectifs théoriques</strong> <span class="math inline">\(E_{ij}=n_{i\cdot}n_{\cdot j}/2000\)</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\([10k;20k[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([20k;50k[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([50k;100k[\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;"><span class="math inline">\(999\times807/2000=403{,}05\)</span></td>
<td style="text-align: right;"><span class="math inline">\(999\times623/2000=311{,}45\)</span></td>
<td style="text-align: right;"><span class="math inline">\(999\times570/2000=284{,}72\)</span></td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;"><span class="math inline">\(590\times807/2000=238{,}07\)</span></td>
<td style="text-align: right;"><span class="math inline">\(590\times623/2000=183{,}79\)</span></td>
<td style="text-align: right;"><span class="math inline">\(590\times570/2000=168{,}15\)</span></td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: right;"><span class="math inline">\(411\times807/2000=165{,}84\)</span></td>
<td style="text-align: right;"><span class="math inline">\(411\times623/2000=128{,}03\)</span></td>
<td style="text-align: right;"><span class="math inline">\(411\times570/2000=117{,}14\)</span></td>
</tr>
</tbody>
</table>
<p>Tous les <span class="math inline">\(E_{ij}&gt;5\)</span> (min : 117,14) — condition de Cochran largement satisfaite.</p>
<p><strong>Étape 3 — Statistique</strong></p>
<p><span class="math display">\[
\chi^2_{obs}
=\frac{(413-403{,}05)^2}{403{,}05}
+\frac{(298-311{,}45)^2}{311{,}45}
+\frac{(288-284{,}72)^2}{284{,}72}
+\frac{(227-238{,}07)^2}{238{,}07}
+\frac{(193-183{,}79)^2}{183{,}79}
+\frac{(170-168{,}15)^2}{168{,}15}
+\frac{(167-165{,}84)^2}{165{,}84}
+\frac{(132-128{,}03)^2}{128{,}03}
+\frac{(112-117{,}14)^2}{117{,}14}
\]</span> <span class="math display">\[
= 0{,}246+0{,}585+0{,}038+0{,}514+0{,}460+0{,}020+0{,}008+0{,}123+0{,}226
= 2{,}22.
\]</span></p>
<p><strong>Étape 4 — Degrés de liberté et valeur critique</strong></p>
<p><span class="math inline">\(\nu=(3-1)(3-1)=4\)</span>. Au seuil 5 % : <span class="math inline">\(\chi^2_{0{,}95;\,4}=9{,}488\)</span>.</p>
<p><strong>Étape 5 — Décision et conclusion</strong></p>
<p><span class="math inline">\(\chi^2_{obs}=2{,}22 &lt; 9{,}488\)</span> : on <strong>ne rejette pas <span class="math inline">\(H_0\)</span></strong> au seuil 5 %.</p>
<p>Les données sont compatibles avec l’hypothèse d’indépendance entre le quartier de résidence et la tranche de revenu. Les écarts observés entre les effectifs observés et théoriques peuvent s’expliquer par les fluctuations d’échantillonnage.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exercice 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cent fruits sont triés selon : - leur poids (en grammes), - leur qualité (accepté/refusé).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Poids (g)</th>
<th style="text-align: right;">Accepté</th>
<th style="text-align: right;">Refusé</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\([200;240[\)</span></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="even">
<td><span class="math inline">\([240;280[\)</span></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">45</td>
</tr>
<tr class="odd">
<td><span class="math inline">\([280;360[\)</span></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">13</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Identifier les caractères étudiés et leur type.</li>
<li>Déterminer la distribution marginale de la variable « poids » et le poids médian.</li>
<li>Déterminer la proportion de fruits dans la classe <span class="math inline">\([240;280[\)</span> pour chaque qualite. Les variables « poids » et « qualité » semblent-elles indépendantes ?</li>
<li>Tester l’indépendance de « qualité » et “poids” au risque <span class="math inline">\(\alpha=5\%\)</span> (test du khi-deux).</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution — Exercice 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Caractères et types</strong></p>
<ul>
<li><em>Poids</em> : variable quantitative continue, regroupée en classes.</li>
<li><em>Qualité</em> : variable qualitative nominale binaire (accepté / refusé).</li>
</ul>
<p><strong>2. Distribution marginale du poids et médiane</strong></p>
<p>Totaux lignes et colonnes :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Poids (g)</th>
<th style="text-align: right;">Accepté</th>
<th style="text-align: right;">Refusé</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;"><span class="math inline">\(f_{i\cdot}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(F_{i\cdot}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\([200;240[\)</span></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0,31</td>
<td style="text-align: right;">0,31</td>
</tr>
<tr class="even">
<td><span class="math inline">\([240;280[\)</span></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">0,52</td>
<td style="text-align: right;">0,83</td>
</tr>
<tr class="odd">
<td><span class="math inline">\([280;360[\)</span></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0,17</td>
<td style="text-align: right;">1,00</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>19</strong></td>
<td style="text-align: right;"><strong>81</strong></td>
<td style="text-align: right;"><strong>100</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>La fréquence cumulée dépasse 0,5 dans la classe <span class="math inline">\([240;280[\)</span>. La médiane vaut : <span class="math display">\[
M_e = 240 + \frac{0{,}50 - 0{,}31}{0{,}52}\times 40
= 240 + \frac{0{,}19}{0{,}52}\times 40
\approx 254{,}6\text{ g}.
\]</span></p>
<p><strong>3. Distributions conditionnelles et indépendance visuelle</strong></p>
<p>La proportion de fruits dans <span class="math inline">\([240;280[\)</span> pour chaque qualité :</p>
<ul>
<li>Acceptés : <span class="math inline">\(\dfrac{7}{19} \approx 0{,}368\)</span>.</li>
<li>Refusés : <span class="math inline">\(\dfrac{45}{81} \approx 0{,}556\)</span>.</li>
</ul>
<p>Sous indépendance, on attendrait la même proportion que dans la marginale (<span class="math inline">\(52/100 = 0{,}52\)</span>) pour les deux qualités. Les valeurs <span class="math inline">\(0{,}368\)</span> et <span class="math inline">\(0{,}556\)</span> s’en écartent sensiblement, ce qui suggère une dépendance entre poids et qualité.</p>
<p><strong>4. Test du khi-deux</strong></p>
<p><em>Hypothèses :</em> <span class="math inline">\(H_0\)</span> : indépendance entre poids et qualité ; <span class="math inline">\(H_1\)</span> : dépendance.</p>
<p><em>Effectifs théoriques</em> <span class="math inline">\(E_{ij} = n_{i\cdot}n_{\cdot j}/100\)</span> :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Poids</th>
<th style="text-align: right;">Accepté</th>
<th style="text-align: right;">Refusé</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\([200;240[\)</span></td>
<td style="text-align: right;"><span class="math inline">\(31\times19/100 = 5{,}89\)</span></td>
<td style="text-align: right;"><span class="math inline">\(31\times81/100 = 25{,}11\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\([240;280[\)</span></td>
<td style="text-align: right;"><span class="math inline">\(52\times19/100 = 9{,}88\)</span></td>
<td style="text-align: right;"><span class="math inline">\(52\times81/100 = 42{,}12\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\([280;360[\)</span></td>
<td style="text-align: right;"><span class="math inline">\(17\times19/100 = 3{,}23\)</span></td>
<td style="text-align: right;"><span class="math inline">\(17\times81/100 = 13{,}77\)</span></td>
</tr>
</tbody>
</table>
<p><em>Condition de Cochran :</em> <span class="math inline">\(E_{31}=3{,}23&lt;5\)</span> (une cellule sur six). Le test est à utiliser avec prudence ; on peut regrouper <span class="math inline">\([200;240[\)</span> et <span class="math inline">\([280;360[\)</span> si l’on veut strictement satisfaire la règle. On procède ici avec les données telles quelles.</p>
<p><em>Statistique :</em> <span class="math display">\[
\chi^2_{obs}
= \frac{(8-5{,}89)^2}{5{,}89}
+ \frac{(23-25{,}11)^2}{25{,}11}
+ \frac{(7-9{,}88)^2}{9{,}88}
+ \frac{(45-42{,}12)^2}{42{,}12}
+ \frac{(4-3{,}23)^2}{3{,}23}
+ \frac{(13-13{,}77)^2}{13{,}77}
\approx 0{,}756+0{,}177+0{,}839+0{,}197+0{,}184+0{,}043
= 2{,}20.
\]</span></p>
<p><em>Degrés de liberté :</em> <span class="math inline">\(\nu=(3-1)(2-1)=2\)</span>.</p>
<p><em>Valeur critique :</em> <span class="math inline">\(\chi^2_{0{,}95;\,2}\approx 5{,}991\)</span>.</p>
<p><em>Décision :</em> <span class="math inline">\(2{,}20 &lt; 5{,}991\)</span>, on <strong>ne rejette pas</strong> <span class="math inline">\(H_0\)</span> au seuil 5 %.</p>
<p><em>Conclusion :</em> Les données ne fournissent pas de preuve significative d’une dépendance entre le poids et la qualité des fruits.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exercice 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Le tableau suivant donne la distribution conjointe (fréquences) du temps de trajet domicile-travail et du mode de transport :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Temps (h)</th>
<th style="text-align: right;"><span class="math inline">\([0;0{,}5[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([0{,}5;1[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([1;2[\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Collectif</td>
<td style="text-align: right;">0,05</td>
<td style="text-align: right;">0,09</td>
<td style="text-align: right;">0,14</td>
</tr>
<tr class="even">
<td>Individuel</td>
<td style="text-align: right;">0,25</td>
<td style="text-align: right;">0,24</td>
<td style="text-align: right;">0,23</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Déterminer le temps moyen pour chacun des deux modes de transport.</li>
<li>En supposant un échantillon de 1000 personnes, tester l’indépendance entre mode de transport et classe de temps au risque <span class="math inline">\(\alpha=5\%\)</span>.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution — Exercice 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Temps moyen par mode de transport</strong></p>
<p>Centres de classes : <span class="math inline">\(c_1=0{,}25\)</span> h, <span class="math inline">\(c_2=0{,}75\)</span> h, <span class="math inline">\(c_3=1{,}5\)</span> h.</p>
<p>Marginales (somme sur les colonnes de chaque ligne) :</p>
<ul>
<li>Collectif : <span class="math inline">\(f_{\text{col}\cdot} = 0{,}05+0{,}09+0{,}14 = 0{,}28\)</span>.</li>
<li>Individuel : <span class="math inline">\(f_{\text{ind}\cdot} = 0{,}25+0{,}24+0{,}23 = 0{,}72\)</span>.</li>
</ul>
<p>Fréquences conditionnelles pour le transport <em>collectif</em> (on divise chaque cellule par 0,28) :</p>
<p><span class="math display">\[
f_{[0;0{,}5[\mid\text{col}}} = \frac{0{,}05}{0{,}28}\approx 0{,}179,\quad
f_{[0{,}5;1[\mid\text{col}}} = \frac{0{,}09}{0{,}28}\approx 0{,}321,\quad
f_{[1;2[\mid\text{col}}} = \frac{0{,}14}{0{,}28} = 0{,}500.
\]</span></p>
<p><span class="math display">\[
\bar t_{\text{col}}
= 0{,}25\times 0{,}179 + 0{,}75\times 0{,}321 + 1{,}5\times 0{,}500
= \frac{0{,}25\times 0{,}05 + 0{,}75\times 0{,}09 + 1{,}5\times 0{,}14}{0{,}28}
= \frac{0{,}0625+0{,}0675+0{,}21}{0{,}28}
= \frac{0{,}29}{0{,}28}
\approx 1{,}036\text{ h}.
\]</span></p>
<p>Fréquences conditionnelles pour le transport <em>individuel</em> (on divise par 0,72) :</p>
<p><span class="math display">\[
\bar t_{\text{ind}}
= \frac{0{,}25\times 0{,}25 + 0{,}75\times 0{,}24 + 1{,}5\times 0{,}23}{0{,}72}
= \frac{0{,}0625+0{,}18+0{,}345}{0{,}72}
= \frac{0{,}5875}{0{,}72}
\approx 0{,}816\text{ h}.
\]</span></p>
<p>Les usagers des transports collectifs ont en moyenne un trajet <strong>26 % plus long</strong> que ceux en transport individuel.</p>
<p><strong>2. Test du khi-deux (n = 1000)</strong></p>
<p><em>Hypothèses :</em> <span class="math inline">\(H_0\)</span> : indépendance entre mode et classe de temps ; <span class="math inline">\(H_1\)</span> : dépendance.</p>
<p><em>Tableau d’effectifs observés</em> (fréquences <span class="math inline">\(\times\)</span> 1000) :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\([0;0{,}5[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([0{,}5;1[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([1;2[\)</span></th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Collectif</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">140</td>
<td style="text-align: right;">280</td>
</tr>
<tr class="even">
<td>Individuel</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">240</td>
<td style="text-align: right;">230</td>
<td style="text-align: right;">720</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>300</strong></td>
<td style="text-align: right;"><strong>330</strong></td>
<td style="text-align: right;"><strong>370</strong></td>
<td style="text-align: right;"><strong>1000</strong></td>
</tr>
</tbody>
</table>
<p><em>Effectifs théoriques</em> <span class="math inline">\(E_{ij}=n_{i\cdot}n_{\cdot j}/1000\)</span> :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\([0;0{,}5[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([0{,}5;1[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([1;2[\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Collectif</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">92,4</td>
<td style="text-align: right;">103,6</td>
</tr>
<tr class="even">
<td>Individuel</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">237,6</td>
<td style="text-align: right;">266,4</td>
</tr>
</tbody>
</table>
<p>Tous les <span class="math inline">\(E_{ij}\ge 5\)</span> : condition de Cochran satisfaite.</p>
<p><em>Statistique :</em> <span class="math display">\[
\chi^2_{obs}
=\frac{(50-84)^2}{84}+\frac{(90-92{,}4)^2}{92{,}4}+\frac{(140-103{,}6)^2}{103{,}6}
+\frac{(250-216)^2}{216}+\frac{(240-237{,}6)^2}{237{,}6}+\frac{(230-266{,}4)^2}{266{,}4}
\]</span> <span class="math display">\[
\approx 13{,}76+0{,}06+12{,}79+5{,}35+0{,}02+4{,}97 = 36{,}95.
\]</span></p>
<p><em>Degrés de liberté :</em> <span class="math inline">\(\nu=(2-1)(3-1)=2\)</span>.</p>
<p><em>Valeur critique :</em> <span class="math inline">\(\chi^2_{0{,}95;\,2}\approx 5{,}991\)</span>.</p>
<p><em>Décision :</em> <span class="math inline">\(36{,}95 \gg 5{,}991\)</span>, on <strong>rejette</strong> <span class="math inline">\(H_0\)</span> au seuil 5 %.</p>
<p><em>Conclusion :</em> Il existe une dépendance significative entre le mode de transport et la classe de temps de trajet. Les usagers du collectif tendent à avoir des trajets plus longs que ceux en transport individuel.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Mise en garde</span>Exercice 3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Voici les résultats d’une enquête sur les intentions de vote selon la classe d’âge :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Liste / Âge</th>
<th style="text-align: right;"><span class="math inline">\([18;35[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([35;50[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([50;80[\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vers l’avenir</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">145</td>
</tr>
<tr class="even">
<td>Pour la démocratie</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">220</td>
</tr>
<tr class="odd">
<td>En avant</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">67</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Déterminer la proportion de personnes entre 18 et 35 ans pour chacune des listes. Commenter.</li>
<li>Les variables « intentions de vote » et « âge » sont-elles indépendantes ?</li>
<li>Réaliser un test du khi-deux d’indépendance au risque <span class="math inline">\(\alpha=5\%\)</span>.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution — Exercice 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Totaux du tableau</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Liste / Âge</th>
<th style="text-align: right;"><span class="math inline">\([18;35[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([35;50[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([50;80[\)</span></th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vers l’avenir</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">145</td>
<td style="text-align: right;"><strong>368</strong></td>
</tr>
<tr class="even">
<td>Pour la démocratie</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;"><strong>467</strong></td>
</tr>
<tr class="odd">
<td>En avant</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;"><strong>165</strong></td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>294</strong></td>
<td style="text-align: right;"><strong>274</strong></td>
<td style="text-align: right;"><strong>432</strong></td>
<td style="text-align: right;"><strong>1000</strong></td>
</tr>
</tbody>
</table>
<p><strong>1. Proportion de 18–35 ans par liste</strong></p>
<p><span class="math display">\[
f_{[18;35[\mid\text{Avenir}}} = \frac{110}{368}\approx 0{,}299,\quad
f_{[18;35[\mid\text{Démocratie}}} = \frac{127}{467}\approx 0{,}272,\quad
f_{[18;35[\mid\text{En avant}}} = \frac{57}{165}\approx 0{,}345.
\]</span></p>
<p>La proportion marginale des 18–35 ans est <span class="math inline">\(294/1000=0{,}294\)</span>. Les trois proportions conditionnelles s’en approchent mais présentent des écarts notables (de 0,272 à 0,345), ce qui laisse présager une légère dépendance entre l’intention de vote et la classe d’âge.</p>
<p><strong>2. Indépendance visuelle</strong></p>
<p>Sous indépendance, on attendrait la même distribution d’âge dans chaque liste (proportions <span class="math inline">\(0{,}294\)</span>, <span class="math inline">\(0{,}274\)</span>, <span class="math inline">\(0{,}432\)</span>). Les profils conditionnels des trois listes s’en écartent modérément, sans rupture flagrante. L’indépendance est plausible mais doit être confirmée par le test.</p>
<p><strong>3. Test du khi-deux</strong></p>
<p><em>Hypothèses :</em> <span class="math inline">\(H_0\)</span> : indépendance entre intention de vote et âge ; <span class="math inline">\(H_1\)</span> : dépendance.</p>
<p><em>Effectifs théoriques</em> <span class="math inline">\(E_{ij}=n_{i\cdot}n_{\cdot j}/1000\)</span> :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\([18;35[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([35;50[\)</span></th>
<th style="text-align: right;"><span class="math inline">\([50;80[\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vers l’avenir</td>
<td style="text-align: right;"><span class="math inline">\(368\times294/1000=108{,}19\)</span></td>
<td style="text-align: right;"><span class="math inline">\(368\times274/1000=100{,}83\)</span></td>
<td style="text-align: right;"><span class="math inline">\(368\times432/1000=158{,}98\)</span></td>
</tr>
<tr class="even">
<td>Pour la démocratie</td>
<td style="text-align: right;"><span class="math inline">\(467\times294/1000=137{,}30\)</span></td>
<td style="text-align: right;"><span class="math inline">\(467\times274/1000=127{,}96\)</span></td>
<td style="text-align: right;"><span class="math inline">\(467\times432/1000=201{,}74\)</span></td>
</tr>
<tr class="odd">
<td>En avant</td>
<td style="text-align: right;"><span class="math inline">\(165\times294/1000=48{,}51\)</span></td>
<td style="text-align: right;"><span class="math inline">\(165\times274/1000=45{,}21\)</span></td>
<td style="text-align: right;"><span class="math inline">\(165\times432/1000=71{,}28\)</span></td>
</tr>
</tbody>
</table>
<p>Tous les <span class="math inline">\(E_{ij}\ge 5\)</span> : condition de Cochran satisfaite.</p>
<p><em>Statistique :</em> <span class="math display">\[
\chi^2_{obs}
=\frac{(110-108{,}19)^2}{108{,}19}
+\frac{(113-100{,}83)^2}{100{,}83}
+\frac{(145-158{,}98)^2}{158{,}98}
+\frac{(127-137{,}30)^2}{137{,}30}
+\frac{(120-127{,}96)^2}{127{,}96}
+\frac{(220-201{,}74)^2}{201{,}74}
+\frac{(57-48{,}51)^2}{48{,}51}
+\frac{(41-45{,}21)^2}{45{,}21}
+\frac{(67-71{,}28)^2}{71{,}28}
\]</span> <span class="math display">\[
\approx 0{,}030+1{,}468+1{,}229+0{,}772+0{,}495+1{,}652+1{,}486+0{,}392+0{,}257
= 7{,}78.
\]</span></p>
<p><em>Degrés de liberté :</em> <span class="math inline">\(\nu=(3-1)(3-1)=4\)</span>.</p>
<p><em>Valeur critique :</em> <span class="math inline">\(\chi^2_{0{,}95;\,4}\approx 9{,}488\)</span>.</p>
<p><em>Décision :</em> <span class="math inline">\(7{,}78 &lt; 9{,}488\)</span>, on <strong>ne rejette pas</strong> <span class="math inline">\(H_0\)</span> au seuil 5 %.</p>
<p><em>Conclusion :</em> Au seuil de 5 %, les données ne permettent pas de conclure à une dépendance significative entre l’intention de vote et la classe d’âge. Les différences observées dans les profils sont compatibles avec les fluctuations d’échantillonnage sous l’hypothèse d’indépendance.</p>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="lecture-et-interprétation-des-résultats" class="level2">
<h2 class="anchored" data-anchor-id="lecture-et-interprétation-des-résultats">Lecture et interprétation des résultats</h2>
<p>Obtenir une valeur de <span class="math inline">\(\chi^2_{obs}\)</span> et une décision (rejet ou non de <span class="math inline">\(H_0\)</span>) n’est que le début de l’analyse. Une <strong>bonne interprétation statistique</strong> requiert de contextualiser la décision : un test significatif indique une dépendance, mais pas son intensité ni sa nature. Il faut ensuite examiner quelles cellules contribuent le plus à l’écart global et formuler une conclusion dans le langage du problème étudié.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Bonnes pratiques d’analyse
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Toujours commenter <strong>l’ampleur</strong> des écarts, pas seulement la décision binaire du test.</li>
<li>Examiner les distributions conditionnelles pour identifier les associations les plus marquantes.</li>
<li>Vérifier la qualité du tableau (effectifs suffisants, classes pertinentes).</li>
<li>Distinguer « absence de preuve de dépendance » et « preuve d’indépendance ».</li>
<li>Rappeler que le test du <span class="math inline">\(\chi^2\)</span> est <strong>sensible à la taille de l’échantillon</strong> : avec un <span class="math inline">\(n\)</span> très grand, de très petits écarts pratiquement négligeables peuvent devenir statistiquement significatifs.</li>
</ol>
</div>
</div>
<section id="résidus-standardisés" class="level3">
<h3 class="anchored" data-anchor-id="résidus-standardisés">Résidus standardisés</h3>
<p>Pour identifier quelles cellules contribuent le plus à la valeur de <span class="math inline">\(\chi^2_{obs}\)</span>, on calcule les <strong>résidus standardisés</strong> : <span class="math display">\[
R_{ij}=\frac{O_{ij}-E_{ij}}{\sqrt{E_{ij}}},
\]</span> qui vérifient <span class="math inline">\(\chi^2_{obs}=\sum_{i,j}R_{ij}^2\)</span>. Les cellules avec <span class="math inline">\(|R_{ij}|&gt;2\)</span> contribuent le plus à l’écart et méritent une attention particulière dans l’interprétation. Un résidu positif signifie que cette combinaison de modalités est <strong>sur-représentée</strong> par rapport à l’indépendance ; un résidu négatif signifie qu’elle est <strong>sous-représentée</strong>.</p>
</section>
<section id="limites-du-test" class="level3">
<h3 class="anchored" data-anchor-id="limites-du-test">Limites du test</h3>
<ul>
<li>Le test du <span class="math inline">\(\chi^2\)</span> <strong>ne quantifie pas l’intensité</strong> de l’association. Pour cela, on peut utiliser le coefficient de contingence <span class="math inline">\(C=\sqrt{\chi^2/(n+\chi^2)}\)</span> ou le <span class="math inline">\(V\)</span> de Cramér <span class="math inline">\(V=\sqrt{\chi^2/(n\cdot\min(p-1,q-1))}\)</span>, qui sont normalisés entre 0 et 1.</li>
<li>Il ne s’applique qu’à des <strong>données de comptage</strong> dans un tableau de contingence (et non à des moyennes ou des proportions issues de mesures répétées sur les mêmes individus).</li>
<li>Il est <strong>non directionnel</strong> : il détecte l’existence d’une association mais n’en précise pas la direction ni la forme.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ggilles\.dev");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../teaching/statistics-probability/normal-distribution.html" class="pagination-link" aria-label="Loi normale et applications">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Loi normale et applications</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../teaching/statistics-probability/joint-continuous-random-variables.html" class="pagination-link" aria-label="Couples de variables à densité">
        <span class="nav-page-text">Couples de variables à densité</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Built with <a href="https://quarto.org">Quarto</a> · Source on <a href="https://github.com/guillaumegilles/guillaumegilles.github.io"><i class="bi bi-github"></i> GitHub</a></p>
</div>   
    <div class="nav-footer-center">
<p>This site respects your privacy — no cookies, no tracking.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>