project:
  type: book

book:
  title: Communating
  author: "Guillaume Gilles"
  date: "12/11/2024"
  
  chapters:
    - index.qmd
    - preface.qmd
  
    - part: WRITTING w/ Markdown
      chapters:
        - markdown.qmd
        - quarto.qmd
        - latex.qmd
  
    - part: VISUALYSING w/ ggplot
      chapters: 
        - ggplot.qmd

    - part: INTERACTION w/ Shniy
      chapters:
        - shniy.qmd

  appendices:
    - markdown-cheatsheet.qmd


bibliography: references.bib
citation-location: margin

format:
  html:
    theme: 
      light: united
      dark: solar