# GitHub Copilot

```bash
./
|_ .github/
   |_ copilot-instructions.md
```

## Instructions Files

When GitHub Copilot processes a request, it reads instructions files and
incorporates their content into its responses, producing suggestions that align
with your project's conventions without requiring you to repeat the same
context in every prompt.

### `.github/copoilot-instructions.md`
The primary instructions file for GitHub Copilot is the
`.github/copoilot-instructions.md` markdown file. The instructions are
automatically included in every GitHub Copilot prompt acting as **always-on**
guidelines.

::: {.callout}
You can write these instructions in natural language using markdown formatting
without affecting the behavior of Copilot because whitespace between instrcutions
is ignored when sent to the model. Hence you can focus on readability without
degrading performance.
:::

For example you can specify "Use PascalCase for naming variables" or "Always use
the repository pattern for data classes", etc.

You can use `/init` GitHub Copilot commands to initialize a new project or
repository with the appropriate instructions file.

::: {.callout}

:::
