---
title: "Get the Most of Brilliant App: Keep it Free"
draft: true
---

Brilliant is a great app for these who are intimidated by Mathematics, its
formula, its logic.

I’ve started using it mostly to find inspiration how to teach and illustration of mathematical concept
Basiccaly, Brilliant consit of bite-sized science lessons, from Grade 5 to college.

But i am cheap, and utterly against the subscription economy therefor i do not upgradeade to their Premium
tier and use the app under the free version.

To remind you what Premium is:

| Benefits                            | Free | Premium |
|-------------------------------------|------|---------|
|Daily lesson                         |  ✅  |   ✅    |
|Unlimited learning                   |  ❌  |   ✅    |
|Tutoring by Koji                     |  ❌  |   ✅    |
|No ads                               |  ❌  |   ✅    |
|Jump ahead and personalized practice |  ❌  |   ✅    |

### Unlimited learning

it means you can work through as many lesson as you what. but you day has only 24 hours in it,
unlimited is misleading ina finite wordl.

### Tutoring by Koji

THe AI experience of Brilliant. what do you need it when you know what you want to work on it

### No ads

Actually the ads are funny. it isn’t pain to go through its

### Jump ahead and personalized practice

## So Keep it Free?

> Because it the **BEST** way to learn!

Our brain is design to learn with repetition
imagine you spend 4 hours on the app:

  - you went through dozen of bite-sized lessons,
  - jump somes, because you are bored.
  - crush multiple exercices one after another,
  - closed the app,
  - come back at it 2 weeks later.

Great, you check everything on todo list for the next 2 weeks.
But when you open the app again 2 week later, you feel nervous, 
i am not sure to remember what i have seen last time.
it is daunting.
You have enjoyed Premium experience but did you maximize your learning experience?

Free tier force you to go through lessons slowly, one at a time everyday.
It helps your brain building connection between concept 

What are you trying to accomplish, publish Einstein grade thesis tomorrow. if it were. you wouldn’t need Brilliant in the first place
so start learning and using Brilliant how it should be design for learning,
5 minutes everyday with a cup of coffee, or tea. take your time, enjoy a free learning
experince.


The goal is not the destination but the journey! Enjoy the ride, savor every daily lessons
