project:
  type: book

book:
  title: "Decision Making with Statistics"
  author: "Guillaume Gilles"
  date: "1/15/2024"
  reader-mode: true
  chapters:
    - index.qmd
    - 01-sets-combinatorial-analysis.qmd
    - 03-discrete-random-variable.qmd
    - references.qmd
  appendices:
    - syllabus.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
