# Hypothesis testing - Comparison test

The Department of Education looks at the average (first hire) salary of students graduating in 2021 (in higher education)

In particular, the Ministry wishes to compare the salaries of engineering school graduates with those of business school graduates

Indeed, the department check whether on average :

There is a salary difference
Engineering school graduates have an advantage
Business school graduates have an advantage
We note that in this context, there are no reference values. Thus, in order to answer the ministry's questions, we have to compare two unknown averages.

Transforming the problem into a modeling framework:

Unknown parameters :

𝑚_1=𝔼(𝑋_1) and 𝜎_1= 𝜎(𝑋_1)
〖 𝑚〗\_2=𝔼(𝑋_2) and 𝜎_2= 𝜎(𝑋_2)

The department's questions can be translated as follows:

On average, there is a difference in salary  𝒎*𝟏 ≠𝒎*𝟐
On average, the salary of engineering school graduates is better 〖 𝒎〗*𝟏>𝒎*𝟐
On average, the salary of business school graduates is better  𝒎*𝟏<𝒎*𝟐

Approach 1 :

If we have perfect knowledge of the distributions "𝔏1" and "𝔏2", then the problem becomes purely "probabilistic"

 Simply calculate 𝑚_1=𝔼(𝑋_1) and 〖 𝑚〗\_2=𝔼(𝑋_2) (afterwards perform the comparison between the calculated means)

Approach 2 :

We can proceed by census: in other words, study the unknown parameter(s) on the whole of each sub-population

Approach 3 :

We can proceed by sampling: in other words, study the unknown parameter(s) on a part of each sub-population

Remark :

Given that perfect knowledge of the "𝕷" distribution is rather utopian.
The sampling procedure is often preferred for processing

This procedure allows to bypass a number of difficulties / disadvantages of the census procedure:

Accessibility to the entire population
The cost
The time
…

The "reliability" of this procedure obviously depends on the "selection quality" of the individuals and the number of individuals.

Step 1 : calculation of the (empirical) test statistic

Where

𝑥 ̅ is the empirical mean, 𝑠_𝑥 is the empirical standard deviation (calculated from data set 1)

𝑦 ̅ is the empirical mean, 𝑠_𝑦 is the empirical standard deviation (calculated from data set 2)

The Ministry of Education wishes to check whether there is a difference in the average salary (of the first employment contract) between students graduating in 2021 (in higher education) from engineering schools and business schools

To do this, the Ministry conducted two separate empirical studies.

In the first study, the Ministry selected (randomly) 100 graduates (in 2021) from engineering schools and took their gross monthly salaries (from the first contract after graduation) . This first study gave an average of 3350 euros and a standard deviation of 400.

In the second study, the ministry selected (randomly) 120 graduates (in 2021) from business schools and took their gross monthly salaries (from the first contract after graduation). This first study gave an average of 3550 euro and a standard deviation of 650 .

Can we say, with a 1% risk, that there is a difference in average salary (of the first hiring contract) between students graduating in 2021 from engineering schools and business schools?

Transforming the problem into a modeling framework:

Unknown parameters:

𝑚_1=𝔼(𝑋_1) and 𝜎_1= 𝜎(𝑋_1)
〖 𝑚〗\_2=𝔼(𝑋_2) and 𝜎_2= 𝜎(𝑋_2)

Formulation: we wish to carry out a two-tailed test of comparison between two unknown means:

Treatment in conclusion:

Calculation of the (empirical) test statistic : 𝑢_𝑜𝑏𝑠=−2.794858

With 𝛼=1%, we have 𝑢=2.575. It implies that |𝑢_𝑜𝑏𝑠 |>𝑢
Therefore, we reject the null hypothesis.

In other words, the data allow us to confirm, with a 1% risk, that there is a difference in average salary (of the first hiring contract) between students graduating in 2021 from engineering schools and business schools.

The French Ministry of Education is interested in the hiring rate following graduation (in higher education) among students of the class of 2021.

In particular, the Ministry wishes to compare this hiring rate between engineering school graduates and business school graduates

Indeed, the department will check if :

There is a difference
The hiring rate is higher for engineering school graduates
The hiring rate is higher for business school graduates

We note that in this context, there are no reference values. Thus, in order to answer the ministry's questions, we have to compare two unknown proportions

Transforming the problem into a modeling framework:

Unknown parameters :

𝑝_1 = ℙ(𝑋_1 = 1)
𝑝_2 = ℙ(𝑋_2 = 1)

The department's questions can be translated as follows:

The hiring rate is different  𝒑*𝟏 ≠𝒑*𝟐
The hiring rate is higher for engineering school graduates 〖 𝒑〗*𝟏>𝒑*𝟐
The hiring rate is higher for business school graduates  𝒑*𝟏<𝒑*𝟐

# 09/exercices

The price of a product, noted PP, depends on the evolution of the price of fuel.
The Ministry of Economy wishes to study the evolution of the price of the product PP between April 2022 and May 2022. To do this, the Ministry conducted two separate studies. Explicitly, the ministry randomly sampled 100 PP products during the month of April and 70 PP products during the month of May.

We have:
𝑥*𝑖 the price of the ith PP product selected in April
𝑦*𝑗 the price of the jth PP product selected in May

Let's assume that:

Question :

Can we confirm, with a 5% risk (then 10%), that the average price between April and May has decreased?

Empirical results (April data set):

The size of the data set : 𝑛*1 = 100 (> 30)
The empirical mean (estimation of 𝑚_1= 𝔼(𝑋_1 )) : 𝑥 ̅ = 31.719
The empirical standard deviation (estimation of "σ" \_1="σ" (𝑋_1 )) : 𝑠*𝑥 = √3.776309

Empirical results (May data set):

The size of the data set : 𝑛*2 = 70 (> 30)
The empirical mean (estimation of 𝑚_2= 𝔼(𝑋_2 )) : 𝑦 ̅ = 31.36301
The empirical standard deviation (estimation of "σ" \_2="σ" (𝑋_2 )) : 𝑠*𝑦 = √1.851842

We wish to perform a right one-tailed test of comparison between two means

The (empirical) test statistic : 𝑢_𝑜𝑏𝑠=1.404776

A firm specialized in commercial strategy wishes to test the effectiveness of an advertisement broadcasted (with the same frequency, in the media and on social networks) on the whole French territory. In particular, the firm focuses on two distinct geographical areas, noted A and B. Three weeks after the ad was broadcast, the firm conducted two separate surveys.

The first study involved 1100 randomly selected people who had seen the ad (at least once) and who resided in area A. This study showed that 658 people remembered the slogan of the ad.

The second study was conducted with 1,000 randomly selected people who had seen the ad (at least once) and who resided in Area B. This study showed that 526 people remembered the slogan of the ad.

Question :

Can we confirm, with a 5% risk (then 1%), that advertising is more effective in the area A?

Empirical results (Area A dataset):

The size of the data set : 𝑛_1 = 1100 (> 30)
The number of people who remember the advertising slogan : 𝑘_1=658
The empirical proportion (estimation of 𝑝_1) : 𝑝 ̂_1="0.5981818"

Empirical results (Area B dataset):

The size of the data set : 𝑛_2 = 1000 (> 30)
The number of people who remember the advertising slogan : 𝑘_2=526
The empirical proportion (estimation of 𝑝_2) : 𝑝 ̂_2="0.526"

# 09 / moodle

Exercise 1 :

A laboratory proposes a new treatment to fight against overweight. The laboratory wishes to evaluate the effectiveness of its treatment according to the age of overweight people.
To do this, the laboratory has conducted two separate studies.
A first study was carried out with 70 young overweight people (between 20 and 30 years old) chosen at random. Following the treatment, the laboratory observed 40 good results in these participants.
A second study was conducted with 100 randomly selected overweight people (over 65 years old). Following the treatment, the laboratory observed 43 good results in these participants.
Thus, we can deduce that:
Overweight people represent the study population
A. True
B. False  
Feedback : untreated overweight people are not part of the population.

To check if the treatment is more effective in young overweight people then a right one-tailed test of comparison between two means should be performed.
A. True
B. False  
Feedback : the "good outcome" rates are the unknowns.

3. If we wish to evaluate the treatment is more effective in younger overweight individuals, then the (empirical) test statistic, denoted 𝑢_𝑜𝑏𝑠, is equal to 2.88
   A. True
   B. False  
   Feedback : Check the calculations (using the formula to find the test statistic associated with a comparison test between two proportions)

4. The data allow us, with a 1% risk, to confirm that the treatment is more effective in young overweight people.
   A. True
   B. False  
   Feedback : With a risk of 1%, we see that there is no rejection of the initial hypothesis ....

5. The data do not allow us, with a 5% risk, to confirm that the treatment is more effective in young overweight people.
   A. True
   B. False  
   Feedback : With a risk of 5%, we find that the initial hypothesis is rejected ....

Exercise 2

A factory manufactures steel cables. The plant's quality manager wants to check t2. Let 𝑚_1 be the unknown average breaking load weight under low temperature and 𝑚_2 the unknown average breaking load weight under high temperature. To test whether the quality of the steel wire ropes manufactured at the factory is better under low temperature, a right one-tailed test of comparison between two unknown means is performed.
A. True
B. False  
Feedback : we put in the alternative hypothesis what we want to demonstrate

he breaking load that these cables can withstand as a function of the ambient temperature.

To do this, he has carried out two separate studies.

For the first study, the quality manager randomly selected 100 steel cables manufactured at the plant and measured their breaking loads at low temperatures (-2°C). This study gave an average of 58 tons and a standard deviation of 3 tons.
For the second study, the quality manager randomly selected 120 steel cables manufactured at the plant and measured their breaking loads under high temperature (40°C). This study gave an average of 57 tons and a standard deviation of 5 tons.

Thus, we can deduce that:

1. To check if the quality of the steel wire ropes manufactured in the factory is better under low temperature, we have to perform a two-tailed comparison test between two unknown means.
   A. True
   B. False  
   Feedback : the proposed test allows to check if the quality is different according to the temperature.

2. The data allows us, with a 5% risk, to confirm that the quality of the steel cables manufactured in the factory is better at low temperatures.
   A. True
   B. False  
   Feedback : After checking the calculations (using the formula for finding the test statistic associated with a comparison test between two averages), we find that the initial hypothesis is rejected (with a 5% risk)

3. The data allows us, with a 1% risk, to confirm that the quality of the steel cables manufactured in the factory is better at low temperatures.
   A. True
   B. False  
   Feedback : After checking the calculations (using the formula for finding the test statistic associated with a comparison test between two averages), we see that the initial hypothesis is not rejected (with a 1% risk)