# Preface {.unnumbered}

Welcome to **Introduction to Business Statistics**, IBS, a web textbook I've created to use in my statistics classes at ESSCA, Bordeaux.

## About Introduction to Business Statistics

Introduction to Business Statistics is designed to meet the scope and requirements of one-semester statistics course for business, economics, and related majors for undergraduate students in business school. Core statistical concepts and skills have been augmented with practical business examples, scenarios, and exercises. The result is a meaningful understanding of the discipline which will serve students in their business careers and real-world experiences.

## Syllabus

### Course goals & objectives

### Class meetings

This class is taught for students PGE programm during the spring semester at Bordeaux

### Required materials

### Class meetings

### Exams

### Work load

You are expected to put in about 4-6 hours of work / week outside of class. Some of you will do well with less time than this, and some of you will need more

## Acknowledgements

IBS is created with [Quarto](https://quarto.org/docs/books/) and hosted on [Github]().







This is a Quarto book.

To learn more about Quarto books visit <https://quarto.org/docs/books>.

https://quarto.org/docs/books/book-structure.html: This page should include the preface, acknowledgements, etc. and headings in the index.qmd file are unnumbered by default. The HTML version of the book will use the index.qmd as the home page and if provided, will place the cover-image on that page.

The references.qmd file will include the generated bibliography (see References below for details).

- [Introductory Statistics](https://openstax.org/details/books/introductory-statistics-2e?Book%20details)
- https://www.openint.kjro.org/
- https://www.khanacademy.org/profile/me/courses
- https://www.statisticshowto.com/

## Descriptive versus inferential statistics

## Syllabus

The syllabus can be found [here](syllabus.qmd)

- [ ] Embedding khan academy video at the end of each section
- [ ] folded table of content on first level
- [ ] insert link (cross reference) between figure. par dans les random variable quand on parle des combination cf! calculation of probabilities
- [ ] processus stochastic miage
- [ ] openclassroom proba / stat
- [ ] kassie kozolov: medium, youtube, etc.
