# Linear Correlation Coefficient Test 

. Each student (selected for the study) is measured for height and weight.
Can we say (from this sample) that there is a link between student weight and height?

Each driver (selected for the study) is measured for age and the number of car accidents he or she has had.
Can we say (from this sample) that there is a link between age and the number of driver accidents?
Etc…

It is assumed in this lesson that two quantitative variables are measured simultaneously in a population. (For example: height and weight or age and number of accidents)

The goal remains the same as when we studied the Chi-square test, that is:
Study the possible link between these two variables.

In other words, the linear correlation coefficient test is used to study the existence or not of a link between two quantitative variables in a given population.

Modeling Framework :
Population
Variables studied simultaneously: X and Y real random variables (i.e. both variables are quantitative)
Postulate: the couple Z = (X,Y) has an « L » Distribution
Goal: to study the dependence between X and Y
The unknown value :   ρ (X,Y)

We want to test
H0 : ρ (X,Y) = 0
against
H1 : ρ (X,Y) ≠ 0

The above test is a two-tailed test. It allows us to implicitly study the link between two variables. In other words, the acceptance of H1 implies the existence of a link between the two variables.

We want to test
H0 : ρ (X,Y) = 0
against
H1 : ρ (X,Y) ≠ 0

It is assumed that (X,Y) follows a bivariate Normal distribution. This restriction is less restrictive when the sample size n is large enough (e.g. ≥ 30)

2. 1 Notations

𝑛 is the total number of data
𝑥 ̅ is the mean of the variable X
𝑠*(𝑥 )is the standard deviation of the variable X
𝑦 ̅ is the mean of the variable Y
𝑠*(𝑦 )is the standard deviation of the variable Y

𝐶𝑜𝑣 (𝑥,𝑦)=1/𝑛 ∑2*(𝑖=1)^𝑛▒〖𝑥*𝑖 𝑦*𝑖 〗 −(𝑥 ̅×𝑦 ̅)
𝑟(𝑥,𝑦)=(𝐶𝑜𝑣 (𝑥,𝑦))/(𝑠*𝑥×𝑠_𝑦 )

Reminder Calculation of the Covariance
Data at a raw state : 𝐶𝑜𝑣 (𝑥,𝑦)=1/𝑛 ∑2*(𝑖=1)^𝑛▒〖𝑥*𝑖 𝑦_𝑖 〗 −(𝑥 ̅×𝑦 ̅)

Example :
In this example, we find :

𝑥 ̅=1624,8

𝑦 ̅=1658,4

𝐶𝑜𝑣 (𝑥,𝑦)=1/5(1624×1667+1625×1652+1622×1654+1613×1656+1640×1663−(1624,8×1658,4)=20,48

Reminder Calculation of the Covariance
Data in a contingency table : 𝐶𝑜𝑣 (𝑥,𝑦)=1/𝑛 ∑2*(𝑖=1)^𝑛▒〖〖𝑛*𝑖𝑗 𝑥〗*𝑖 𝑦*𝑖 〗 −(𝑥 ̅×𝑦 ̅ )

Example :

𝐶𝑜𝑣 (𝑥,𝑦)= 1/20[(5×1×1+1×(−0,25)×1+1×(−0,25)×1+2×(−0,25)×(−0,25)] −(0,3×0,55) = 0.06625

2. 2 The formulas to perform the test
   The following expression must be calculated:

Where

Decision rule: We reject H0 if |uobs | ≥ t, otherwise we do not reject H0
The rejection of H0 implies the acceptance of H1 and consequently we can deduce the dependence of the variables. The non-rejection of H0 does not necessarily imply the absence of a link between X and Y .

where
t is defined as follows F(t) = 1−𝛼/2, where F is the distribution function of the Student’s distribution, with
n-2 degrees of freedom

t is calculated from the Student’s distribution table.

Student
Distribution
Table

with

𝟏−𝜶/𝟐
Degrees of freedom = n-2

When the sample size is sufficiently large (e.g. ≥ 30), the decision rule for the test becomes:

We reject H0 if |uobs| > u , otherwise we do not reject H0

where
u is a real defined as follows F(u) = 1−𝛼/2, with F is the distribution function of the normal distribution

u is calculated from the table of the Normal distribution.

Normal Distribution
Table

with

𝟏−𝜶/𝟐

2. 3 Conclusion of the test

As a reminder, the test is written :
H0 : ρ (X,Y) = 0
against
H1 : ρ (X,Y) ≠ 0

H0 rejected : the data confirm that the two variables are not independent
 This implies that there is a link between the two variables

H0 not rejected : the data do not confirm that the two variables are not independent
 In other words, the data do not confirm a link between the two variables with an α% risk.

Let X be the net salary of women and Y the net salary of men in the same household. It is assumed that the couple (X,Y) follows a normal distribution. The two variables are studied on 15 households. The results are presented in the following table:

At the 5% risk, can we say that there is a link between salaries and gender?

The test is written:

    H0 : ρ (X,Y) = 0
    	against
    H1 : ρ (X,Y) ≠ 0

3. 1 Notations

𝑛 is the total number of data  n = 15 < 30
𝑥 ̅ is the mean of the variable X  𝑥 ̅ = 1/15 (1624+…+1613)= 1631,93
𝑠*(𝑥 ) is the standard deviation of the variable X  𝑠*𝑥=√(1/15 (〖1624〗^2+…+〖1613〗^2 )−1631,93²)=√247,79=15,74
𝑦 ̅ is the mean of the variable Y  𝑦 ̅ = 1/15 (1667+…+1667)= 1670
𝑠*(𝑦 ) is the standard deviation of the variable Y  𝑠*𝑦=√(1/15 (〖1667〗^2+…+〖1667〗^2 )−1670²)=√254,54=15,95

𝐶𝑜𝑣 (𝑥,𝑦)=1/𝑛 ∑2*(𝑖=1)^𝑛▒〖𝑥*𝑖 𝑦*𝑖 〗 −(𝑥 ̅×𝑦 ̅ )= 1/15(1624×1667+…+1613×1667) −(1631,93×1670)=196,73
𝑟(𝑥,𝑦)=(𝐶𝑜𝑣 (𝑥,𝑦))/(𝑠*𝑥×𝑠_𝑦 ) = 196,73/(15,74×15,95) = 196,73/251,05=0,78

3. 2 The formulas to perform the test

The following expression must be calculated:

In our example:

Student Distribution
Table

with

𝟏−𝜶/𝟐 = 𝟏−(𝟎,𝟎𝟓)/𝟐=𝟎,𝟗𝟕𝟓
Degrees of freedom = n-2 = 15-2=13

We find t = 2,16

3. 3 Conclusion of the test

With a risk α = 5%, we reject the H0 hypothesis.

In other words, with a 5% risk, the data confirm that there is a link between women’s salary and men’s salary within the same household. So, there is a link between the salaries and the gender.

A famous brand specialized in the distribution of cultural and electronic products to the general public has commissioned a study from a firm specialized in marketing. The goal is to study the existence of a link between the amount spent and the age of the store's customers. A survey was conducted on a sample of 120 customers. Let 𝑥*𝑖 be the amount spent by the ith customer and 𝑦*𝑖 represent their age. We obtain the following results:

At 1% risk, can we say that the age and the amount spent are linked ?

The test is written:

    H0 : ρ (X,Y) = 0
    	against
    H1 : ρ (X,Y) ≠ 0

Let X be the variable dedicated to the amount spent
Let Y be the variable dedicated to the age of the client

4. 1 Notations

𝑛 is the total number of data  n = 120 > 30
𝑥 ̅ is the mean of the variable X  𝑥 ̅ = 1/120×2956= 24,63
𝑠*(𝑥 ) is the standard deviation of the variable X  𝑠*𝑥=√(1/120 75752−24,63²)=√24,46=4,95
𝑦 ̅ is the mean of the variable Y  𝑦 ̅ = 1/120×4383= 36,525
𝑠*(𝑦 ) is the standard deviation of the variable Y  𝑠*𝑦=√(1/120 164699−36,525²)=√38,416=6,198

𝐶𝑜𝑣 (𝑥,𝑦)=1/𝑛 ∑2*(𝑖=1)^𝑛▒〖𝑥*𝑖 𝑦*𝑖 〗 −(𝑥 ̅×𝑦 ̅ )= 1/120(111464) −(24,63×36,525)=29,26
𝑟(𝑥,𝑦)=(𝐶𝑜𝑣 (𝑥,𝑦))/(𝑠*𝑥×𝑠_𝑦 ) = 29,26/(4,95×6,198) = 29,26/30,68=0,95

4. 2 The formulas to perform the test
   The following expression must be calculated :

In our example:

Normal Distribution
Table

with

𝟏−𝜶/𝟐 = 0,995

We obtain u = 2,58

4. 3 Conclusion of the test

With a risk α = 1%, we reject the hypothesis H0
The two variables are not independent.

In other words, with a 1% risk, the data confirms that there is a link between the amount spent by a customer and their age.

# 13 / exercice

The data below shows the height and high jump score of 40 athletes.

At the 1% risk, can we say that the size and the sports result of the athletes (specialized in high jump) are linked?

The test is written:

    H0 : ρ (X,Y) = 0
    	against
    H1 : ρ (X,Y) ≠ 0

Let X be the variable dedicated to the size of the athletes
Let Y be the variable dedicated to the sports result

1. Notations

𝑛 is the total number of data  n = 40 > 30
𝑥 ̅ is the mean of the variable X  𝑥 ̅ = 1/40 (1,73+…+1,84)= 1,818
𝑠*(𝑥 ) is the standard deviation of the variable X  𝑠*𝑥=√(1/40 (〖1,73〗^2+…+〖1,84〗^2 )−1,818²)=√0,0104=0,102
𝑦 ̅ is the mean of the variable Y  𝑦 ̅ = 1/40 (2,32+…+2,37)= 2,3725
𝑠*(𝑦 ) is the standard deviation of the variable Y  𝑠*𝑦=√(1/40 (〖2,32〗^2+…+〖2,37〗^2 )−3,3725²)=√0,0022=0,047

𝐶𝑜𝑣 (𝑥,𝑦)=1/𝑛 ∑2*(𝑖=1)^𝑛▒〖𝑥*𝑖 𝑦*𝑖 〗 −(𝑥 ̅×𝑦 ̅ )= 1/40(1,73×2,32+…+1,84×2,37) −(1,818×2,3725)=0,0043125
𝑟(𝑥,𝑦)=(𝐶𝑜𝑣 (𝑥,𝑦))/(𝑠*𝑥×𝑠_𝑦 ) = 0,0043125/(0,102×0,047) = 0,0043125/0,0048=0,89

2. The formulas to perform the test
   The following expression must be calculated:

In our example:

The Normal Distribution
Table

with

𝟏−𝜶/𝟐 = 0,995

We obtain u = 2,58

3. Conclusion of the test

With a risk α = 1%, we reject the hypothesis H0
The two variables are not independent.

In other words, with a 1% risk, the data confirm that there is a link between the athlete's height and sports performance.

# 13 / moodle

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.

If we want to know if there is a link between the level of customer satisfaction with the two products, what hypothesis test can be used?

A test of conformity to a reference average 
A comparison test between two means
ANOVA Test
Chi-square test

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.

What is the mean level of satisfaction for the product P1 ?

1,5
2,5
3,5
4,5

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.

What is the mean level of satisfaction of the product P2 ?

1,41
2,41
3,41
4,41

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.

What is the value of the empirical linear correlation coefficient : r(x,y) ?

-0,81
-0,41
0,41
0,81

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.

What is the value of 𝑢_𝑜𝑏𝑠 ?

0,46
9,48
78,46
248,46

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.
At the 1% risk, can we say that there is a link between the level of customer satisfaction with the two products?

To solve such a hypothesis test, which table can be used ?
Normal Distribution Table
Fisher Table
Chi-Square Table

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.
At the 1% risk, can we say that there is a link between the level of customer satisfaction with the two products?

In such a hypothesis test, what is the value of u ?
0,99
0,995
1,37
2,58

We consider the 1 to 4 Likert scale to measure customer satisfaction. The data below show the satisfaction level of 440 randomly selected customers with two products P1 and P2 belonging to two competing brands.
At the 1% risk, can we say that there is a link between the level of customer satisfaction with the two products?

The data confirm a link between the level of satisfaction of the product P1 and that of P2
The data do not confirm a link between the level of satisfaction with P1 and P2
