---
title: MS04-001-G
---

## Teacher:

Guillaume Gilles (guillaume.gilles@essca.eu)

## Course Description

## Course Learning Outcomes, Objectives

## Course Calendar

| Date | Topic                                                                                             |       Textbook's Chapters        | Khan Academy Videos |
| :--: | ------------------------------------------------------------------------------------------------- | :------------------------------: | :------------------ |
|  #1  | [Sets and Combinatorial Analysis](decision-making-statistics.qmd#sets-and-combinatorial-analysis) |                                  |                     |
|  #2  | Représentation graphique de données                                                               |                                  |                     |
|  #3  | TP 'application via Excel                                                                         |                                  |                     |
|  #4  | Calcul des valeurs assocees à des pourcentages (quartiles, déciles, etc.) + boîtes à moustache    |                                  |                     |
|  #5  | TP 'application via Excel                                                                         |                                  |                     |
|  #6  | Calcul des indicateurs de position centrale (movenne et le mode)                                  | 3.2 Measures of Central Tendency |                     |
|  #7  | Calcul des indicateurs de dispersion                                                              |                                  |                     |
|  #8  | Calcul des indicateurs d'asymétrie                                                                |                                  |                     |
|  #9  | TP 'application via Excel                                                                         |                                  |                     |
| #10  | Calcul bivarié                                                                                    |                                  |                     |
| #11  | TP 'application via Excel                                                                         |                                  |                     |
| #12  | TP de révision                                                                                    |                                  |                     |

## Recommended Textbook

- [Applied Statistics and Multivariate Data Analysis](assets/applied-statistics-and-multivariate-data-analysis.pdf)

## Course Grades:

1. MCQ Exam: 35%
2. Final Exam: 65%

## Prerequisites

[MS02-001-G / Data Description](/teaching/data-description.qmd)