---
title: "print('Hello World!')"
description: "The first post to start this blog"
author: "Guillaume Gilles"
date: "01/21/2024"
back-to-top-navigation: false
bibliography: ../../bibliography/website.bib
categories: [news]
---

Hi everyone!

I’ve been thinking to create a blog for a while now, but never crossed the line to actually setting one up and running. I think the desire to have a place of my own to talk about thing that resonnate to me and pet projects I am working on have been stronger than the fear of being judged.

As an aspirying machine learning engineer, blog posts are great opportunities to showcase:

> Examples that convinced me of a candidate’s expertise in certain technology [...] a blog post that covers in-depth detail about X that made our team go: “Whoa, they really know about X.” [@huyenWhatWeLook2023]

[David Robinson](http://varianceexplained.org/about/)'s best advice for someone wanted to start a data science career is to start a [blog](http://varianceexplained.org/r/start-blog/). In his post, he explained his three key opinions:

1. **Practice analyzing data and communicating about it**: it can be easily resumed to "practice makes perfect" or in French: "C'est en forgeant qu'on devient forgeron".
2. **Create a portfolio of your work and skills**: after spending hours and nights practicing your data science craft, a blog is a valuable medium to share your work. This piece of advice works well for established data scientists as well.
3. **Get feedback and evaluation**: creating a community and interacting with an audience helps individuals to reach for better.

[Quarto](https://quarto.org) have reduced the friction of building a website so low that it would be a shame to miss this opportunity. So let’s start building my digital garden.