project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Business Statistics"
  author: "Guillaume P.R. Gilles"
  search: true
  repo-url: https://github.com/guillaumegilles/introduction-business-statistics
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

  sidebar:
    background: light
    border: true
    tools:
      - icon: shop
        href: https://guillaumegilles.github.io/misc.html

  chapters:
    - index.qmd

    - part: sampling-and-data.qmd
      chapters:
        - definitions-statistics-probability-key-terms.qmd
        - data-sampling-and-variation.qmd

    - summary.qmd
    - references.qmd

  appendices:
    - syllabus.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
