---
title: "Banque de France"
lang: fr
---

## Références:
- https://www.citeco.fr/stefan-zweig-et-l%E2%80%99or-de-la-france
- https://www.mollat.com/livres/2869981/hubert-bonin-de-la-banque-de-bordeaux-a-la-banque-de-france-1818-1848-1854-un-demi-siecle-de-banque-d-emission-et-d-escompte
- https://archives-historiques.banque-france.fr/
- https://www.banque-france.fr/fr/banque-de-france/institution-ancree-histoire/histoire-banque-de-france

## Banque de France
- 18 janvier 1800 : Création de la Banque de France
- Dès 1803 : Dans Paris, la Banque de France obtient le privilège d’émission des
  billets. La monnaie d’alors est le franc germinal. C’est le premier pas vers
  le monopole d’émission.
- 1848 : sous la Seconde République, la Banque de France obtient le monopole de
  l'émission de billets et devient la force de réescompte des effets de commerce
  sur l'ensemble du territoire national.
- 1924-1927 : à 27 mètres sous terre, un immense coffre-fort est construit en
  plein Paris. Alphonse Defrasse est l’architecte de la Souterraine avec ses 720
  colonnes soutenant le plafond. En 1932, Stephan Zweig livre un court récit de
  sa visite.
- 1939-1945 : Avec la Seconde Guerre Mondiale et l’arrivé des Allemands à Paris, il faut mettre les quelques 3 000 tonnes d’or, que possède la France à cette époque, à l’abri. Dans le plus grand secret la Souterraine est entièrement vidée. Les caisses sont discrètement chargées sur de bateaux en direction des USA, de la Martinique et de l’Afrique.

## Succursale de Bordeaux
La succursale bordelaise de la Banque de France s’inscrit dans une histoire
bancaire locale riche. Avant son intégration à la Banque de France, Bordeaux
possédait sa propre banque d’émission : la Banque de Bordeaux, fondée en 1818
par des négociants et armateurs pour relancer l’économie girondine après les
guerres napoléoniennes. En 1848, la Banque de France obtient le monopole de
l’émission de billets et absorbe progressivement les banques locales, dont
celle de Bordeaux.

- 1818 : création de la Banque de Bordeaux (banque départementale, créée par
  décret) par une communauté de négociants, d'armateurs et de promoteurs
  immobiliers, pour contribuer au dynamisme de l'économie girondine.
- 1848 : La Banque de Bordeaux, devient succursale de la Banque de France.
- 1864-1908 : succession de transformations pour agrandissement et transformation.
- 1914 : au début de la guerre, le Gouvernement de la République et celui de la
  Banque de France sont transférés à Bordeaux. Pendant 3 mois, environ 200
  personnes venant du siège, travaillent ainsi à Bordeaux, portant les effectif
  à 380 personnes
- 1939-1940 : Bordeaux est un des points de rassemblement puis d’embarcation
  de l’or en provenance des succursales. Environ 180 tonnes d’or sont expédiées,
  le 9 juin 1940, à Casablanca à bord du paquebot français « Ville d’Oran ».
- 1925 : reconstruction compète par l’architecte Alphonse Defrasse (celui même
  en charge de la Souterraine).

## Espaces et métiers associés dans une succursale de la Banque de France

Avec l'ouverture des comptoirs de Château-Thierry et d'Oloron-Sainte-Marie en
1928, le réseau compte 260 succursales en activité atteignant ainsi son apogée.
Un reportage photographique réalisé entre 1925 et 1928 dans les succursales de
la Banque de France permet de collecter plus de 5 000 photographies. Il retrace
le parcours type : du bureau du directeur aux salles d’archives, en passant par
le hall du public et la galerie des recettes. Ces clichés illustrent l’homogénéité
des aménagements et la rigueur du travail dans toutes les succursales.

### Hall du public

Toute personne ou société, qui désire ouvrir un compte courant simple ou avec
faculté d'escompte, doit en faire la demande par écrit au directeur de la
succursale. Cette demande doit être accompagnée d'un certificat signé par trois
personnes déclarant connaître le demandeur et que celui-ci fait honneur à ses
engagements.

À titre exceptionnel, le directeur peut, sous sa responsabilité personnelle,
dispenser de la présentation de ce certificat les personnes notoirement connues.
Les demandes d'admission sont ensuite soumises à l'examen du Comité d'escompte
de la succursale pour admission

### Salon des clients

Le salon d'attente est destiné aux clients les plus importants de la succursale
avant leur rendez-vous avec le directeur. Ce salon était souvent situé près de
l’entrée, avec un mobilier élégant pour refléter la confiance et la stabilité de
l’institution.

### Galerie des recettes

Une partie importante des opérations des succursales de la Banque consiste alors
à escompter, à toutes personnes, des lettres de change et autres effets de
commerce à ordre à des échéances déterminées. Les modalités d'admission à
l'escompte et d'encaissement font l'objet d'instructions très précises visant à
encadrer une activité rémunératrice mais également risquée.

Tous les matins, le caissier classe les effets destinés à l'encaissement et les
répartit par quartier aux agents de la recette. Les garçons de recettes se rendent
alors aux adresses mentionnées pour encaisser le montant des effets. À leur retour,
ils s'installent à leur guichet de la galerie des Recettes pour vérifier le
produit de leur tournée avant de le remettre au caissier. Les guichets n'étaient
pas équipés de poignée de sorte qu'ils ne pouvaient être ouverts de l'extérieur
qu'à l'aide de la clef que les agents détenaient.

### Service de caisse

Le service des caisses est essentiel à l'activité de la succursale dès lors qu'il
est conduit à recevoir, manipuler et vérifier toutes les valeurs, quelle que soit
leur nature, déposées ou retirées aux guichets de la succursale. Toutes les caisses
d'une succursale doivent, sans exception, ne pouvoir s'ouvrir qu'avec deux clés
dont l'une reste dans les mains du directeur et l'autre entre celles du caissier.

Il est absolument interdit à l'un des deux agents, "dans aucune circonstance et
sous aucun prétexte", de réunir les deux clés dans ses mains. Lorsqu'ils ne sont
pas de service, ils doivent emporter leurs clés dans leurs appartements respectifs.

### Salle de travail

Attenante au service de la caisse, la salle de triage, ou salle de travail, permet
de manipuler en toute discrétion les différents documents et valeurs en circulation.

### Serre des titres (salle des titres)

Cette serre reçoit les titres conservés en dépôt libre ou en garantie d'avances
accordées à des clients. Par titre, on entend des actions, des obligations ou des
effets publics (rentes, bons de la défense nationale...). Les titres étaient
conservés dans des armoires métalliques ou des coffres, avec une traçabilité
rigoureuse. Ce lieu était souvent situé en zone semi-souterraine ou dans une pièce
blindée.

### Salle des coffres

La location de coffres-forts fait partie des services rendus à la clientèle
désireuse de conserver valeurs et documents précieux en toute sécurité.
