---
title: "Try Hack Me SEC0"
abstract: |
  To attack or defend any technology, you first need to understand what powers it. Explore computer basics, write your first lines of code, and discover how networking, the web, and real world cyber attacks all connect. Your cyber security journey starts here!
draft: true
---

Prerequisites
No Prior Knowledge

    You need no prerequisite to start this pathway! Just enthusiasm and excitement to learn!

    

- Each room is designed to be byte size knowledgze blocs, you can run through it in 5 minutes or take your time to digest information depending on your initial background!
- number of rooms : 31
- number of points earn : 2174,  from `0x1 [Neophyte]` to `0x6 [Voyager]`
-> bring you to thz top 25%


> ## Pre Security
>
> This path teaches you how technology works from the ground up, no prior experience needed. From computer basics and your first lines of code to networking, the web, and cyber attacks and defences, this is where your cyber security journey begins.

Topics learned

Your first step into cyber. Learn how tech works, then think like an attacker and defender.

    Explore how computers really work
    Write your first lines of code
    Step into networking and web basics
    Think like a hacker or defender



<iframe src="https://tryhackme.com/api/v2/badges/public-profile?userPublicId=7028520" style='border:none;' title="TryHackMe badge"></iframe>

