---
title: "print('Hello World!')"
subtitle: "What this website is about"
bibliography: ../../assets/references.bib
citation-location: margin
categories: [news]
---

::: {.callout-tip}
## TL;DR
:::

##

## References

## Changelog

:::{.callout-note}

:::



::: {.callout-note}
TL;DR
…
:::

Hi everyone!

I’ve been thinking to create a website, and more pricesly a blog, for a while
now. I’ve never crossed the line of hypothesis until now, by fear of being
judged. Expressing one’s thoughts on the web is intimidating and daunting. But I
supposed the desire to have a place of my own to talk about thing that resonnate
to me and pet projects I am working on is a stronger driving force than lack of
self confidence.

As an aspirying machine learning engineer, blog posts are great opportunities to
showcase your work. According to Chip Huyen, it is a great place to demonstrate
“examples that convinced me of a candidate’s expertise in certain technology
[...] a blog post that covers in-depth detail about X that made our team go:
Whoa, they really know about X.”

For David Robinson, a blog is the best advice for someone wanted to start a data
science career. It helps to:

1. **Practice analyzing data and communicating about it**: it can be easily
  resumed to "practice makes perfect" or in French: "C'est en forgeant qu'on
  devient forgeron".
2. **Create a portfolio of your work and skills**: after spending hours and
  nights practicing your data science craft, a blog is a valuable medium to
  share your work. This piece of advice works well for established data
  scientists as well.
3. **Get feedback and evaluation**: creating a community and interacting with an
  audience helps individuals to reach for better.

## References

::: {#refs}
- [@robinsonAdviceAspiringData2017]
- [@huyenWhatWeLook2023]
:::

---
Hi everyone!

I’ve been thinking to create a website, and more pricesly a blog, for a while
now. I’ve never crossed the line of hypothesis until now, by fear of being
judged. Expressing one’s thoughts on the web is intimidating and daunting. But I
supposed the desire to have a place of my own to talk about thing that resonnate
to me and pet projects I am working on is a stronger driving force than lack of
self confidence.

## [[chip-huyen-look-for-in-resume]]

As an aspirying machine learning engineer, blog posts are great opportunities to
showcase your work. According to Chip Huyen, it is a great place to demonstrate
“examples that convinced me of a candidate’s expertise in certain technology
[...] a blog post that covers in-depth detail about X that made our team go:
Whoa, they really know about X.”

## [[advice-to-aspiring-data-scientists]]

For David Robinson, a blog is the best advice for someone wanted to start a data
science career. It helps to:

1. **Practice analyzing data and communicating about it**: it can be easily
   resumed to "practice makes perfect" or in French: "C'est en forgeant qu'on
   devient forgeron".
2. **Create a portfolio of your work and skills**: after spending hours and
   nights practicing your data science craft, a blog is a valuable medium to
   share your work. This piece of advice works well for established data
   scientists as well.
3. **Get feedback and evaluation**: creating a community and interacting with an
   audience helps individuals to reach for better.

## [[garage-door-open]]

These days, one of the consequences of [[social media]] is a curated posts
proliferation of well-curated posts and accomplishments. More and more people
misunderstand what it takes to [[get thing done]] and the work behind the scenes.
We end up with mostly posts announcements of finished work.

On the opposite of this philosophy, [Andy Mutaschak](https://andymatuschak.org/)
loves to "work with the garage door up". What does it mean in the digital area:
publishing ongoing projects or posts that are written for oneself and not an
audience. In his words. it looks like "giving a lecture about the problems you’re
pondering in the shower; it’s thinking out loud about how your project doesn’t
work at all. I want to see the process. I want to see you trim the artichoke."

## References

::: {#refs}

- [@huyenWhatWeLook2023]
- [@robinsonAdviceAspiringData2017]
- [@matuschakWorkGarageDoor]
:::

why a website : 4ème point de la technique de feynman : transmettre
[[feynman-technique]]

[[digital-garden]]

[[digital-garden.goals]]

[[digital-garden-7-lessons]]

- [learning by doing](https://duckduckgo.com/?q=lex+fridman+andrej&t=newext&atb=v411-1&iax=videos&ia=videos&iai=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DI2ZK3ngNvvI) @ 5 minutes

Difference between [[zettelkasten]], [[digital-garden]]. and [[second-brain]] ?

what to find on my website:

1. blog posts
   documente my pet projects
   dendron
   kaggle
   shocase what i learned, lifelong leanre
2. lecture
3. stuff i read
4. photo ?
