---
title: "How Many Rabbits Can You Pull out of a Hat?"
date: 2025-02-28
description: >
  A hat contains a known number of orange, green, and purple rabbits. Rabbits are randomly pulled out one at a time, without replacement. For how many rabbits can you correctly guess the color?
categories:
  - Fiddler
  - Probability
  - Puzzle
---

This week's [Fiddler on the Proof](https://thefiddler.substack.com/p/how-many-rabbits-can-you-pull-out) puzzle 

## Puzzle

I have a hat with six small toy rabbits: two are orange, two are green, and two purple. I shuffle the rabbits around and randomly draw them out one at a time without replacement (i.e., once I draw a rabbit out, I never put it back in again).

Your job is to guess the color of each rabbit I draw out. For each guess, you know the history of the rabbits I’ve already drawn. So if we’re down to the final rabbit in the hat, you should be able to predict its color with certainty.

Every time you correctly predict the color of the rabbit I draw, you earn a point. **If you play optimally** (i.e., to maximize how many points you get), how many points can you expect to earn on average?

### Solution

It is important to note this puzzle requires to maximize our point. Therefore each draw, we should guess the color that has the highest probability of being drawn, given the remaining rabbits. If all remaining colors are equally likely, we must make an arbitrary guess.

1. **First draw**:

The first draw is completely random since **all** colors have equal probability and have a $1/3$ probability of earning 1 point.

2. **Second draw**:

We now have 5 rabbits remaining in the hat. Here the best guess is to pick one of the two remaining colors that still have 2 rabbits left, that gives us $2/5$ chance of earning 1 point.

3. Third draw**:

There are 4 rabbits left, whch leads us into 2 identical situations. First, the previous draws were identical color, for example orange, therefore we arre left with 2 green and 2 pruple rabbit toys. Our best guess can't be better than a random guess between purple and green. Our probability to earn 1 point is $2/4$ or simply $1/2$.

In the second situatuion, the previous 2 draws picked up different colors, for example organe and green. In that case the most represented color is purple wihch also has a $2/4$ to be picked up, or $1/2$.

We can see that in both situation our chances to get 1 point is $1/2$.

4. **Fourth draw**:

With 3 rabbits left, we should again guess the most frequent remaining color. If previous draws picked up different colors, it remains 1 rabbit toys of each colors, meaning our best guest is no better than a random choice between orange, green or puprple, so $1/3$.

But if previous draws ha eliminated one color, for example purples have been dranw 2 times (none left) and one orange, therefore the hat countain 1 orange and 2 green. Our best guess is to select green with a $2/3$ probability of earning 1 point.

4. **Fifth draw**:

Two rabbits remain, Either of a unique color if the other 2 has been pick up or different color. Therefore in the first case we are sure to select the correct answer, the probability of getting one point is $1$. In the other case, the probaility is $1/2$.

5. **Sixth draw**:

At this point it remains only one rabbit toy, the probability of being correct is $1$.

So if we compute all these probability, 

we get :

1. $P_4 = 1/3$ & $P_5 = 1/2$

$$
1/3 + 2/5 + 1/2 + 1/3 + 1/2 + 1
$$

2. 

$$
1/3 + 2/5 + 1/2 + 1/3 + 1/2 + 1
$$
