---
title: Feynman Technique
type:
tags: [lifelong-learning]
---

> _“the first principle is that you must not make a mistake - and it is you who
> the easiest person to deceive. »_ — Richard P. Feynman

The goal of this learning technique is to be able to explain the
concept to someone else in a simple way. It is necessary to understand this

> _"If you can't explain it simply, it's because you don't understand it
> not good enough."_ — Albert Einstein

Feynman's learning technique is broken down into four parts
[@rosieFeynmanLearningTechnique2021]:

1. **Explain the subject to a child**: Choose a topic. On a white sheet, writing
down everything we know about the subject, as if we were teaching this subject
to an 11 year old child years old, or a rubber duck on your desk... It is
important to use simple words, technical words and expressions must be deleted
as well than jargon. Often these terms make it possible to hide a lack of
understanding, they are just a repetition of what we have heard elsewhere.

It is also important to be concise. A child's attention span is limited, he
can only stay focused for a few minutes. Every time we let's discover a few
new things on the subject, it must be added to the note.

2. **Identify holes in explanations**: The difficult passages, those lacking
clarity, are the elements to rework. It is necessary to start again from sources,
books, videos YouTube, articles, etc.

3. **Organization and simplification**: Each note must describe a unique subject,
it is an atomic structure in the meaning of [[zettelkasten-notes]]. We can group
all of these notes by skill areas, by subjects, to create presentations or lessons.

4. **Transmit**: The logical goal of this process is understanding a subject.
The last The stage is the transmission of these new skills to an audience. This
the last step is the best test to determine. People's feedback allow us to check
if we are capable of broadcasting a subject simply.

- [print('Hello World!')](../digital-garden/hello-world/index.qmd)

