---
title: YAML in Foam
type: 
tags: []
---

## Foam Front-matter

At the top of a file, in [Foam](foam.qmd), there are [YAML properties](yaml.qmd)
that serves as [Front-Matter](front-matter.qmd). For example, for this file,
we have:

```{yaml}
---
title: YAML in Foam
type: feature
---
```

This sets the `type` of this document to `feature` and sets **three** keywords
for the document: `hello`, `world`, and `bonjour`. The YAML parser will treat
both spaces and commas as the separators for these YAML properties. If you want
to use multi-word values for these properties, you will need to combine the
words with dashes or underscores (i.e. instead of `hello world`, use
`hello_world` or `hello-world`).


## Foam Properties

Some YAML properties have special meaning for Foam:

- `title`: will assign the name to the note that you will see in the graph,
  regardless of the filename or the first heading.
- `type`: can be used to style notes differently in the
  [graph](foam-graph-visualization.qmd). The default type for a document is `note`
  unless otherwise specified with this property.
- `tags`: can be used to add [tags](foam-tags.qmd).

## Foam [Template](foam-templates#metadata) Properties

Some YAML properties are specific for setting up a note template:

- `filepath`: The filepath to use when creating the new note. If the filepath is
  a [relative filepath](os.relative-path.md), it is relative to the current
  [workspace](vscode-workspace.qmd).
- `name`: A human readable name to show in the template picker.
- `description`: A human readable description to show in the template picker.

