---
# Foam YAML metadata
title: "What is Good Mathematics"
type:
created: 2024-05-07
tags: [essay]

# Quarto YAML metadata
bibliography: ../assets/references.bib

# Foam template YAML metadata
---

## What is Good Math

At first, it could be difficult and subjective to define what good math looks
likes. There are many different perspective: it could be _problem-solving_
oriented, or focuses on _theory_ and _technique_, or being _rigorous_, etc.
Indeed "Mathematics is itself complex and high-dimensional" discipline. For
Terence Tao [@taoWhatGoodMathematics2007], good mathematics "is not merely
measured by one or more of the ‘local’ qualities". Finally What makes good math
is an empirical vision, where good pieces converge and "fits in with other pieces
either by building upon earlier achievements or encouraging the development of
future breakthroughts."

## Why good math matters

Ressources (time, talent, money, attention) are scarced, it is therefore
important to manage them wisely, hence the goal to good mathematics. [@strogatzWhatMakesGood]

## Drawback

We can only judge good math after the converge process which coud take time,
making ressource management even more difficult: how to determine in advance which
piece of math to focus on?
