---
title: Open Source
type:
created: 2024-05-05
tags: [open-source]

# Quarto YAML metadata
bibliography: ../assets/references.bib
---

## Anatomy of an open source project

A typical open source project has the following types of people:

- **Author**: The person/s or organization that created the project.
- **Owner**: The person/s who has administrative ownership over the organization
  or repository (not always the same as the original author).
- **Maintainers**: Contributors who are responsible for driving the vision and
  managing the organizational aspects of the project (They may also be authors
  or owners of the project.)
- **Contributors**: Everyone who has contributed something back to the project.
- **Community Members**: People who use the project. They might be active in
  conversations or express their opinion on the project’s direction.

## Documentation

A project also has documentation. These files are usually listed in the top level
of a repository.

- [LICENSE](license.qmd): By definition, every open source project must have an
  open source license. If the project does not have a license, it is not open
  source.
- [README](readme.qmd): The README is the instruction manual that welcomes new
  community members to the project. It explains why the project is useful and
  how to get started.
- [CONTRIBUTING](contributing.qmd): Whereas READMEs help people use the project,
  contributing docs help people contribute to the project. It explains what types
  of contributions are needed and how the process works. While not every project
  has a CONTRIBUTING file, its presence signals that this is a welcoming project
  to contribute to.
- [CODE_OF_CONDUCT](code-conduct.qmd): The code of conduct sets ground rules for
  participants’ behavior associated and helps to facilitate a friendly, welcoming
  environment. While not every project has a CODE_OF_CONDUCT file, its presence
  signals that this is a welcoming project to contribute to.
- **Other documentation**: There might be additional documentation, such as
  tutorials, walkthroughs, or governance policies, especially on bigger projects.

