---
title: Open Graph within Quarto website
type:
tags: [web]
---

To enable the automatic generation of [Open Graph metadata](open-graph.qmd) for
your content, in [Quarto website](quarto-website.qmd), include the following in
your `_quarto.yml` configuration file:

```{yaml}
website:
  open-graph: true
```

## Additional metadata

- `title`: The title of the page. Quarto will automatically use the title
  metadata from the page metadata. If you’d like you can override this just for
  the Open Graph metadata by including a title in the open-graph metadata.
- `description`: A short description of the content. Quarto will automatically
  use the description metadata from the page metadata. If you’d like you can
  override this just for the Open Graph metadata by including a description in
  the open-graph metadata.
- `image`: The path to a preview image for this content. By default, Quarto will
  use the image value from the document metadata, or if that isn’t specified,
  the image value from the website: metadata. If image is not provided, Quarto
  will automatically attempt to locate a [preview image](quarto-preview-image.qmd).
- `locale`: The locale that the Open Graph metadata is marked up in.
- `site-name`: The name which should be displayed for the overall site. If not
  explicitly provided in the open-graph metadata, Quarto will use the `website:title`
  value.

Here is a more comprehensive example of specifying Open Graph metadata in a
`quarto.yml` file:

```{yaml}
website:
  open-graph:
    locale: es_ES
    site-name: Quarto
```
