---
title: "Sandworm"
type:
created: 2024-04-28
tags: [book]
---

Page 53

Les conséquences d’une cyberattaque sur des infrastructures peuvent être très
incertaines à prédire, tant ces infrastructures sont liées entre elles. De ce
fait, il est difficilement imaginable de pouvoir «  contrôler » les dégâts d’une
cyberattaque sur le réseau électrique par exemple. Aussi, ce type d’attaque
doivent être interdite, tout au moins règlementé, dans les conflits modernes
comme le sont les armes à sous-partition ou biologique.


Page 55

Les précurseurs des cyberattaques pour cibler des infrastrucutures sont les
américains avec le vers Stuxnet, un virus informatique développé en partenariat
avec les services secrets israélien. Il vise à ralentir la production d’Uranian
enrichie par l’Iran dans ses effrots pour se doter de l’arme atomique.


Interview with Whistleblower Edward Snowden on Global Spying - DER SPIEGEL

Obama Ordered Wave of Cyberattacks Against Iran - The New York Times (nytimes.com)


Page 58

Signals Intelligence, SIGINT, regroupe les outils et technique mis en place par
les services secrets d’un pays pour collecter et analyser des renseignements.
Ils interceptent les moyens de communications modernes, les ondes radios,
satellites, dorsal. Ces pratiques sont utilisées avec la 2nde guerre mondiale,
mais elle sont révélé à grande échelle par Edward Snowden.


National Security Agency/Central Security Service > Signals Intelligence > Overview (nsa.gov)


Page 68-69

La robustesse des infrastructures physiques est toute relative face à la
puissance d’un morceau de code d’une trentaine de lignes, soit 140 KB
(kilobytes). Comme le démontre le succès du projet Aurora de Mike Assante
(Cybersecurity Pioneer Michael Assante Passes | ARC Advisory Group (arcweb.com)
dans lequel un moteur diesel de la taille d’un bus est complétement détruit en
quelques secondes à l’aide d’une cyberattaque.


How 30 Lines of Code Blew Up a 27-Ton Generator | WIRED


## Les cyberattaques des hackers se concentrent, pour le moment, sur les
infrastructures de distribution d’électriques, comme le démontre les attaques
de Sandworm en Ukraine (@sandworm). Mais la prochaine étape sera, très
certainement, en amont de la distribution d’électricité. Les hackers cherchent
à perturber, voire endommager, les centrales nucléaires. Quelles seraient les
conséquences d’une cyberattaques sur un EPR ? Dans les conflits à venir, il
n’est plus nécessaire de se doter de l’arme atomique pour un pays, si une
poignée de cyber attaquants peut couper le refroidissement des réacteurs d’une
centrale jusqu’à explosion du cœur du réacteur.


Page 72 :

En 1986, Internet comme on le connait actuellement n’existe pas encore et il
n’existe au 5 000 machine connecté à ce réseau, mais il sert déjà de vecteur
pour de l’espionnage. Des espions d’Allemagne de l’ouest revendent à l’URSS et
au KGB des renseignements qu’ils pillent en se connecter aux machines de
l’université de Berkeley. C’est le début du cyberespionage.


Dans les années 1990, Moonlight Maze est la première affaire de cyberespionage
étatique, avec pour victime les US et probablement la Russie.
