---
title: "Twitter cards"
type:
tags: []
---

To enhance visualization of your [website](website.qmd) within a
[Quarto website](quarto-website.qmd) and attach rich photos, videos and media
experiences to Tweets. Simply add a few lines of [YAML properties](quarto-yaml.qmd):

```{yaml}
website:
  twitter-card: true
```

Users who Tweet links to your content will have a “Card” added to the Tweet
that’s visible to their followers.

## Additional metadata

- `title`: The title of the page. Quarto will automatically use the `title`
  metadata from the page metadata. If you’d like you can override this just for
  the Twitter Card by including a title in the twitter-card metadata.
- `description`: A short description of the content. Quarto will automatically
  use the description metadata from the page metadata. If you’d like you can
  override this just for the Twitter Card by including a description in the
  twitter-card metadata.
- `image`: The path to a preview image for this content. By default, Quarto will
  use the image value from the document metadata, or if that isn’t specified, 
  the image value from the website: metadata. If you provide an image, you may
  also optionally provide an image-width and image-height to improve the
  appearance of your Twitter Card. If image is not provided, Quarto will
  automatically attempt to locate a [preview image](quarto-preview-image.qmd).
- `card-style`: Either `summary` or `summary_large_image`. If this is not provided,
  the best style will automatically selected based upon other metadata.
- `creator`: `@username` of the content creator. Note that strings with special
  characters such as @ must be quoted in yaml.
- `site`: `@username` of website. Note that strings with special characters such
  as @ must be quoted in yaml.

Here is a more comprehensive example of specifying Twitter Card metadata in a
`quarto.yml` file:

```{yaml}
website:
  twitter-card:
    creator: "@dragonstyle"
    site: "@rstudio"
```
