<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.537">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Guillaume Gilles - Session 8 — Asymmetry and Shape</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../assets/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<script>
document.addEventListener('DOMContentLoaded', function () {
  var path = window.location.pathname;
  var isEnTeaching = path.startsWith('/teaching/');
  var isFrTeaching = path.startsWith('/fr/teaching/');

  function translateTool() {
    var icon = document.querySelector('.bi-translate');
    return icon ? icon.closest('.dropdown') : null;
  }

  // Outside the teaching section: hide the translate tool
  if (!isEnTeaching && !isFrTeaching) {
    var tool = translateTool();
    if (tool) tool.style.display = 'none';
    return;
  }

  // Skip RevealJS slides
  if (document.body.classList.contains('reveal')) return;

  // Courses with full page-for-page FR translations [EN prefix, FR prefix]
  var fullPairs = [
    ['/teaching/mathematical-fundamentals/', '/fr/teaching/mathematical-fundamentals/'],
  ];

  function frCounterpart(p) {
    for (var i = 0; i < fullPairs.length; i++) {
      if (p.startsWith(fullPairs[i][0]))
        return fullPairs[i][1] + p.slice(fullPairs[i][0].length);
    }
    var slug = p.replace('/teaching/', '').split('/')[0];
    return '/fr/teaching/' + slug + '/';
  }

  function enCounterpart(p) {
    for (var i = 0; i < fullPairs.length; i++) {
      if (p.startsWith(fullPairs[i][1]))
        return fullPairs[i][0] + p.slice(fullPairs[i][1].length);
    }
    var slug = p.replace('/fr/teaching/', '').split('/')[0];
    return '/teaching/' + slug + '/';
  }

  var enHref = isEnTeaching ? path : enCounterpart(path);
  var frHref = isFrTeaching ? path : frCounterpart(path);

  var tool = translateTool();
  if (!tool) return;

  tool.querySelectorAll('a.dropdown-item').forEach(function (a) {
    var txt = a.textContent.trim();
    if (txt.includes('English')) a.href = enHref;
    else if (txt.includes('Français') || txt.includes('francais')) a.href = frHref;
  });
});
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Guillaume Gilles - Session 8 — Asymmetry and Shape">
<meta property="og:description" content="Data Description | Part II">
<meta property="og:image" content="https://ggilles.dev/teaching/data-description/modules/assets/og-image.jpg">
<meta property="og:site_name" content="Guillaume Gilles">
<meta name="twitter:title" content="Guillaume Gilles - Session 8 — Asymmetry and Shape">
<meta name="twitter:description" content="Data Description | Part II">
<meta name="twitter:image" content="https://ggilles.dev/teaching/data-description/modules/assets/og-image.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../assets/favicon.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Guillaume Gilles</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
    <div class="dropdown">
      <a href="" title="Langue / Language" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Langue / Language"><i class="bi bi-translate"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="../../../teaching.html">
            🇬🇧 English
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="../../../fr/teaching.html">
            🇫🇷 Français
            </a>
          </li>
      </ul>
    </div>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#theory" id="toc-theory" class="nav-link" data-scroll-target="#theory">Theory</a></li>
  <li><a href="#worked-example" id="toc-worked-example" class="nav-link" data-scroll-target="#worked-example">Worked example</a></li>
  <li><a href="#using-excel" id="toc-using-excel" class="nav-link" data-scroll-target="#using-excel">Using Excel</a></li>
  <li><a href="#proof-derivation" id="toc-proof-derivation" class="nav-link" data-scroll-target="#proof-derivation">Proof / derivation</a></li>
  <li><a href="#visual-intuition" id="toc-visual-intuition" class="nav-link" data-scroll-target="#visual-intuition">Visual intuition</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Session 8 — Asymmetry and Shape</h1>
<p class="subtitle lead">Data Description | Part II</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Session 7 established that “The Wandering Fork”’s daily revenue has real, moderate variability: <span class="math inline">\(s=137.09\)</span> and <span class="math inline">\(CV=21.82\%\)</span> — noticeably variable day to day, but not wildly erratic. Knowing <em>how much</em> a distribution spreads out, though, says nothing about <em>how</em> it spreads out: is it balanced evenly around its center, with values fanning out about the same amount on both sides, or is it lopsided, with a longer tail stretching out in one direction? <strong>Skewness</strong> indicators answer exactly that question, and they close the loop on what the mean, median, and mode (Session 6) were quietly hinting at all along.</p>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<ul>
<li>Explain what a symmetric, right-skewed, and left-skewed distribution look like, and how the mean, median, and mode typically order themselves in each case.</li>
<li>Compute and interpret the Fisher-Pearson sample skewness coefficient (Excel’s <code>SKEW</code>), the primary skewness measure used in this course.</li>
<li>Compute the Pearson skewness coefficient and the Yule-Kendall skewness coefficient as alternative, simpler measures, and recognize that different formulas can disagree in sign or magnitude for near-symmetric data.</li>
<li>Read skewness directly off a histogram or boxplot.</li>
</ul>
</section>
<section id="theory" class="level2">
<h2 class="anchored" data-anchor-id="theory">Theory</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition — symmetry and skewness
</div>
</div>
<div class="callout-body-container callout-body">
<p>A distribution is <strong>symmetric</strong> if its left and right halves, measured from the center, are mirror images of each other; in that case the mean, median, and mode coincide. A distribution is <strong>skewed</strong> when one tail is longer or fatter than the other. <strong>Right-skewed</strong> (positive skew) means a longer tail toward high values, typically pulling the mean above the median above the mode (<span class="math inline">\(\bar{x} &gt; Me &gt; Mo\)</span>). <strong>Left-skewed</strong> (negative skew) is the mirror case, with a longer tail toward low values (<span class="math inline">\(\bar{x} &lt; Me &lt; Mo\)</span>).</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formula — Fisher-Pearson sample skewness coefficient
</div>
</div>
<div class="callout-body-container callout-body">
<p>The primary skewness measure used in this course is the <strong>adjusted Fisher-Pearson standardized moment coefficient</strong>, which is what Excel’s <code>SKEW</code> function computes: <span class="math display">\[
SKEW = \frac{n}{(n-1)(n-2)} \sum_{i=1}^{n}
\left(\frac{x_i-\bar{x}}{s}\right)^3.
\]</span> This standardizes every deviation from the mean (dividing by <span class="math inline">\(s\)</span>, so the result is unit-free), cubes it (so, unlike variance, positive and negative deviations do <em>not</em> cancel and large deviations dominate), and averages the result with a small-sample correction factor. A value near <span class="math inline">\(0\)</span> signals near-symmetry; positive means right-skewed; negative means left-skewed.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition — alternative asymmetry coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two simpler, complementary measures are also common. The <strong>Pearson skewness coefficient</strong> compares the mean to the mode, rescaled by the standard deviation. The <strong>Yule-Kendall skewness coefficient</strong> instead compares how the median sits between <span class="math inline">\(Q_1\)</span> and <span class="math inline">\(Q_3\)</span>, using only the five-number summary from Session 5 — useful when the mode is hard to pin down or the data is only available as a boxplot.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formula — Pearson and Yule-Kendall coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\text{Pearson asymmetry} = \frac{\bar{x}-Mo}{s},
\qquad\qquad
YK = \frac{Q_3+Q_1-2\,Me}{Q_3-Q_1}.
\]</span> The Pearson coefficient asks “how many standard deviations separate the mean from the mode?” The Yule-Kendall coefficient asks “is the median closer to <span class="math inline">\(Q_1\)</span> or to <span class="math inline">\(Q_3\)</span>?” — if <span class="math inline">\(Me\)</span> sits closer to <span class="math inline">\(Q_1\)</span> than to <span class="math inline">\(Q_3\)</span>, the upper quarter of the data is more spread out, which is itself a sign of right skew, and vice versa.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Different skewness formulas can genuinely disagree in sign or magnitude, especially for near-symmetric data where all the values involved are close to each other and small estimation differences get amplified by division. Always state <strong>which formula</strong> you used when reporting a skewness value — “the Fisher-Pearson skewness is +0.034” is a precise, checkable claim; “the skewness is positive” is not, unless the formula is named.</p>
</div>
</div>
</section>
<section id="worked-example" class="level2">
<h2 class="anchored" data-anchor-id="worked-example">Worked example</h2>
<p>Using “The Wandering Fork”’s <code>daily_revenue_eur</code> (<span class="math inline">\(n=30\)</span>), with <span class="math inline">\(\bar{x}=628.34\)</span>, <span class="math inline">\(Me=643.63\)</span>, grouped mode <span class="math inline">\(Mo=666.67\)</span> (Session 6), <span class="math inline">\(s=137.09\)</span> (Session 7), and <span class="math inline">\(Q_1=506.60\)</span>, <span class="math inline">\(Q_3=729.99\)</span>, <span class="math inline">\(IQR=223.39\)</span> (Session 5), all verified in <code>data-model.md</code>:</p>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th style="text-align: right;">Value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fisher-Pearson sample skewness</td>
<td style="text-align: right;">+0.034</td>
<td>near-symmetric, very mild right skew</td>
</tr>
<tr class="even">
<td>Pearson skewness coefficient</td>
<td style="text-align: right;">−0.280</td>
<td>mildly left, per this formula</td>
</tr>
<tr class="odd">
<td>Yule-Kendall skewness coefficient</td>
<td style="text-align: right;">−0.227</td>
<td>mildly left, per this formula</td>
</tr>
</tbody>
</table>
<p><strong>Step 1 — the headline measure.</strong> The Fisher-Pearson sample skewness, computed with Excel’s <code>SKEW</code> on all 30 raw observations, is <span class="math inline">\(+0.034\)</span>. Being so close to zero, this is the course’s official conclusion: “The Wandering Fork”’s daily revenue is <strong>essentially symmetric</strong>, with only a very slight lean toward high values.</p>
<p><strong>Step 2 — Pearson asymmetry.</strong> <span class="math inline">\((\bar{x}-Mo)/s = (628.34-666.67)/137.09
\approx -0.280\)</span>: comparing the mean to the <em>grouped-estimated</em> mode instead of using every raw value gives a mildly negative reading.</p>
<p><strong>Step 3 — Yule-Kendall.</strong> <span class="math inline">\((Q_3+Q_1-2Me)/(Q_3-Q_1) =
(729.99+506.60-2\times643.63)/223.39 \approx -0.227\)</span>: comparing only the five-number summary also leans mildly negative.</p>
<p><strong>Step 4 — reconciling the disagreement.</strong> Steps 2 and 3 lean slightly negative while Step 1 leans slightly positive. This is not a contradiction, it is a lesson: the Fisher-Pearson coefficient uses every one of the 30 raw daily revenues, while the Pearson coefficient depends on the grouped mode (<span class="math inline">\(Mo=666.67\)</span>), itself only an <em>estimate</em> from five class frequencies, and the Yule-Kendall coefficient uses just four numbers (<span class="math inline">\(Q_1, Me, Q_3\)</span>, and the range between the first two). For a distribution this close to symmetric, such small formula-specific approximations are enough to flip the sign — which is itself consistent with the headline conclusion that the true skew is very small in absolute terms either way. <strong>The value to report and remember for “The Wandering Fork” is the Fisher-Pearson <span class="math inline">\(+0.034\)</span>.</strong></p>
</section>
<section id="using-excel" class="level2">
<h2 class="anchored" data-anchor-id="using-excel">Using Excel</h2>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Excel function / steps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fisher-Pearson sample skewness</td>
<td><code>=SKEW(range)</code></td>
</tr>
<tr class="even">
<td>Pearson skewness coefficient</td>
<td>No direct function — <code>=(AVERAGE(range)-Mo)/STDEV.S(range)</code>, with <span class="math inline">\(Mo\)</span> computed manually (Session 6)</td>
</tr>
<tr class="odd">
<td>Yule-Kendall skewness coefficient</td>
<td>No direct function — <code>=(QUARTILE.EXC(range,3)+QUARTILE.EXC(range,1)-2*MEDIAN(range))/(QUARTILE.EXC(range,3)-QUARTILE.EXC(range,1))</code></td>
</tr>
</tbody>
</table>
</section>
<section id="proof-derivation" class="level2">
<h2 class="anchored" data-anchor-id="proof-derivation">Proof / derivation</h2>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Derivation — why Excel’s <code>SKEW</code> includes a bias-correction factor (click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The conceptually simplest skewness measure is the <strong>third standardized moment</strong>, <span class="math display">\[
g_1 = \frac{\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^3}
{\left(\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^2\right)^{3/2}}
= \frac{m_3}{m_2^{3/2}},
\]</span> the average cubed deviation (<span class="math inline">\(m_3\)</span>), rescaled by the standard deviation cubed (via <span class="math inline">\(m_2^{3/2}\)</span>) so the result is unit-free. Cubing (rather than squaring, as in variance) is what makes this measure sensitive to <em>direction</em>: a value far above the mean and one equally far below contribute equal-magnitude but opposite-sign terms, so they do not cancel the way squared deviations would.</p>
<p>However, <span class="math inline">\(g_1\)</span> computed directly from a <em>sample</em> is a biased estimator of the true population skewness — it systematically under- or overstates it, especially for small <span class="math inline">\(n\)</span>. Excel’s <code>SKEW</code> applies the standard small-sample correction, replacing <span class="math inline">\(\frac{1}{n}\)</span> with the factor <span class="math inline">\(\frac{n}{(n-1)(n-2)}\)</span> and using the sample standard deviation <span class="math inline">\(s\)</span> (with its own <span class="math inline">\(n-1\)</span> correction, Session 7) in place of the population-style <span class="math inline">\(m_2^{1/2}\)</span>: <span class="math display">\[
SKEW = \frac{n}{(n-1)(n-2)}\sum_{i=1}^n\left(\frac{x_i-\bar x}{s}\right)^3.
\]</span> As <span class="math inline">\(n\)</span> grows large, <span class="math inline">\(\frac{n}{(n-1)(n-2)} \to \frac{1}{n}\)</span> and <span class="math inline">\(s \to
m_2^{1/2}\)</span>, so <span class="math inline">\(SKEW \to g_1\)</span>: the correction matters most for small samples (like “The Wandering Fork”’s <span class="math inline">\(n=30\)</span>) and becomes negligible for very large ones.</p>
</div>
</div>
</div>
</section>
<section id="visual-intuition" class="level2">
<h2 class="anchored" data-anchor-id="visual-intuition">Visual intuition</h2>
<p>On a histogram, skewness is the <strong>direction of the longer tail</strong>: a right-skewed histogram has its bulk of bars on the left and a thin tail trailing off to the right (think: most days are ordinary, a few are exceptionally good); left-skewed is the mirror image. On a boxplot, skewness shows up as an <strong>off-center median line inside the box</strong> and <strong>unequal whisker lengths</strong>: if the whisker toward <span class="math inline">\(Q_3\)</span> is longer than the one toward <span class="math inline">\(Q_1\)</span>, that is visual right skew. For “The Wandering Fork”, the near-equal spacing seen in Session 5’s boxplot (median roughly centered between <span class="math inline">\(Q_1=506.60\)</span> and <span class="math inline">\(Q_3=729.99\)</span>) is the visual signature of the near-zero skewness confirmed numerically here.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>TODO: an interactive skewness visualizer (editable sample, live histogram + skewness value) is a candidate for a future Shinylive demo.</p>
</div>
</div>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1 — Reading the sign and magnitude (click for solution)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A distribution has a Fisher-Pearson sample skewness of <span class="math inline">\(-0.85\)</span>. What does the sign and rough magnitude tell you about its shape, and about the typical ordering of its mean and median?</p>
<p><strong>Solution.</strong> The negative sign means the distribution is <strong>left-skewed</strong>: it has a longer or fatter tail toward low values. A magnitude of <span class="math inline">\(0.85\)</span> (using the common rule of thumb: roughly <span class="math inline">\(|SKEW|&lt;0.5\)</span> near-symmetric, <span class="math inline">\(0.5\)</span>–<span class="math inline">\(1\)</span> moderate skew, <span class="math inline">\(&gt;1\)</span> strong skew) indicates a <strong>moderate</strong> left skew — noticeable, but not extreme. In this case, the typical ordering is <span class="math inline">\(\bar{x} &lt; Me &lt; Mo\)</span>: the few low outlying values pull the mean below the median.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 2 — Reconciling mean/median/mode order with the headline skewness (click for solution)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>“The Wandering Fork”’s mean (628.34), median (643.63), and grouped mode (666.67) follow the order <span class="math inline">\(\bar{x} &lt; Me &lt; Mo\)</span>, which is the classic textbook signature of <em>left</em> skew — yet the Fisher-Pearson coefficient reports <span class="math inline">\(+0.034\)</span>, a very mild <em>right</em> skew. How do you reconcile this?</p>
<p><strong>Solution.</strong> The “<span class="math inline">\(\bar{x}&lt;Me&lt;Mo\)</span> implies left skew” rule is only a rough heuristic, not a guarantee, and it is especially unreliable here for two reasons: (1) the gaps between the three values are tiny relative to the spread of the data (<span class="math inline">\(s=137.09\)</span>), so their exact order can flip with negligible changes in the underlying data; and (2) the mode used is a <em>grouped estimate</em> (<span class="math inline">\(Mo=666.67\)</span>, from five class frequencies), not an exact value computed from all 30 raw observations the way <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(Me\)</span>, and the Fisher-Pearson coefficient are. The Fisher-Pearson value, using every raw observation, is the more precise and authoritative measure here, and at <span class="math inline">\(+0.034\)</span> it confirms the distribution is essentially symmetric — close enough to zero that a heuristic based on three closely-spaced, partly-estimated landmarks should not be trusted to override it.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 3 — Yule-Kendall from a five-number summary (click for solution)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A dataset has <span class="math inline">\(Q_1=40\)</span>, <span class="math inline">\(Me=50\)</span>, <span class="math inline">\(Q_3=55\)</span>. Compute the Yule-Kendall skewness coefficient and interpret its sign.</p>
<p><strong>Solution.</strong> <span class="math display">\[
YK = \frac{Q_3+Q_1-2Me}{Q_3-Q_1}
= \frac{55+40-2\times50}{55-40}
= \frac{95-100}{15}
= -\frac{5}{15} \approx -0.33.
\]</span> The negative sign indicates mild <strong>left</strong> skew by this measure: the median (50) sits closer to <span class="math inline">\(Q_3\)</span> (55) than to <span class="math inline">\(Q_1\)</span> (40), meaning the lower quarter of the data is more spread out than the upper quarter — a longer effective “reach” on the low side.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Built with <a href="https://quarto.org">Quarto</a> · Source on <a href="https://github.com/guillaumegilles/guillaumegilles.github.io"><i class="bi bi-github"></i> GitHub</a></p>
</div>   
    <div class="nav-footer-center">
<p>This site respects your privacy — no cookies, no tracking.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>